//! Quaternion algebra `(a,b)` over `Q`, its ramified places, and its class in
//! `Br(Q)[2]`.
//!
//! Extracted from the Brauer-class logic in `dessin_engine/src/conic.rs`
//! (`/home/john/inverse_galois/M23/dessin_engine/src/conic.rs`) and made a
//! first-class type here, adapted to `rustmath_rationals::Rational`.
//!
//! The quaternion algebra `(a,b/Q)` is generated by `i,j` with `i² = a`,
//! `j² = b`, `ij = -ji`. It ramifies at a place `v` iff the Hilbert symbol
//! `(a,b)_v = -1`. It is a division algebra (anisotropic) iff it ramifies at
//! some place; otherwise it is the split algebra `M₂(Q)`. By Hilbert reciprocity
//! the ramified set is finite, of even cardinality, contained in
//! `{∞, 2} ∪ {p ∣ ab}`.

use crate::hilbert::{
    candidate_places_for_quaternion, hilbert_symbol, HilbertError, Place,
};
use rustmath_rationals::Rational;

/// The quaternion algebra `(a, b / Q)`.
#[derive(Debug, Clone)]
pub struct QuaternionAlgebra {
    pub a: Rational,
    pub b: Rational,
}

/// The class of a quaternion algebra in `Br(Q)[2]`, recorded as its (finite,
/// even) set of ramified places. The trivial (split) class has empty support.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BrauerClass {
    pub ramified_places: Vec<Place>,
}

impl BrauerClass {
    /// The split (trivial) class in `Br(Q)`.
    pub fn is_split(&self) -> bool {
        self.ramified_places.is_empty()
    }
}

impl QuaternionAlgebra {
    pub fn new(a: Rational, b: Rational) -> Self {
        Self { a, b }
    }

    /// `(a,b)_v ∈ {+1,-1}`.
    pub fn hilbert_symbol_at(&self, place: Place) -> Result<i8, HilbertError> {
        hilbert_symbol(&self.a, &self.b, place)
    }

    /// `true` iff `(a,b)_v = -1`.
    pub fn is_ramified_at(&self, place: Place) -> Result<bool, HilbertError> {
        Ok(self.hilbert_symbol_at(place)? == -1)
    }

    /// The full set of ramified places (scanning every candidate).
    pub fn ramified_places(&self) -> Result<Vec<Place>, HilbertError> {
        let mut ramified = Vec::new();
        for place in candidate_places_for_quaternion(&self.a, &self.b) {
            if hilbert_symbol(&self.a, &self.b, place)? == -1 {
                ramified.push(place);
            }
        }
        Ok(ramified)
    }

    /// The class in `Br(Q)[2]` (its ramified support).
    pub fn brauer_class(&self) -> Result<BrauerClass, HilbertError> {
        Ok(BrauerClass {
            ramified_places: self.ramified_places()?,
        })
    }

    /// The algebra splits (is `M₂(Q)`) iff it ramifies nowhere.
    pub fn is_split(&self) -> Result<bool, HilbertError> {
        Ok(self.ramified_places()?.is_empty())
    }

    /// A division algebra iff it ramifies somewhere; equivalently the associated
    /// conic `a x² + b y² = z²` is anisotropic (has no nontrivial `Q`-point).
    pub fn is_division_algebra(&self) -> Result<bool, HilbertError> {
        Ok(!self.ramified_places()?.is_empty())
    }

    /// Alias reading the norm form's isotropy: anisotropic iff a division algebra.
    pub fn is_anisotropic(&self) -> Result<bool, HilbertError> {
        self.is_division_algebra()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn r(n: i64) -> Rational {
        Rational::from_i64(n)
    }

    #[test]
    fn hamilton_quaternion_anisotropic_ramified_2_and_infinity() {
        // The canonical gate: (-1,-1) is Hamilton's quaternions, a division
        // algebra ramified exactly at {2, ∞} (the Müller M23 conic).
        let h = QuaternionAlgebra::new(r(-1), r(-1));
        assert!(h.is_anisotropic().unwrap());
        assert!(h.is_division_algebra().unwrap());
        assert!(!h.is_split().unwrap());

        let ram = h.ramified_places().unwrap();
        assert!(ram.contains(&Place::Real));
        assert!(ram.contains(&Place::Finite(2)));
        assert_eq!(ram.len(), 2);

        assert!(h.is_ramified_at(Place::Real).unwrap());
        assert!(h.is_ramified_at(Place::Finite(2)).unwrap());

        let class = h.brauer_class().unwrap();
        assert!(!class.is_split());
        assert_eq!(class.ramified_places.len(), 2);
    }

    #[test]
    fn split_quaternion_is_matrix_algebra() {
        // (1,-1) is split: x² - y² = z² has the point [1:0:1].
        let s = QuaternionAlgebra::new(r(1), r(-1));
        assert!(s.is_split().unwrap());
        assert!(!s.is_division_algebra().unwrap());
        assert!(s.ramified_places().unwrap().is_empty());
        assert!(s.brauer_class().unwrap().is_split());
    }

    #[test]
    fn ramified_set_has_even_cardinality() {
        // Hilbert reciprocity: the ramified set is finite of even size.
        for (a, b) in [(r(-1), r(-1)), (r(2), r(3)), (r(-6), r(10)), (r(1), r(-1))] {
            let q = QuaternionAlgebra::new(a, b);
            assert_eq!(q.ramified_places().unwrap().len() % 2, 0);
        }
    }
}
