//! The plactic monoid over the positive integers (MAGMA Chapter 145 §145.3).
//!
//! The *plactic monoid* is the quotient of the free monoid on the positive integers by
//! **Knuth equivalence**, generated by the two relations (for an ordered alphabet):
//!
//! ```text
//!   y x z  ∼  y z x      (x < y ≤ z)
//!   x z y  ∼  z x y      (x ≤ y < z)
//! ```
//!
//! Its elements are Knuth-equivalence classes of words, each represented by a canonical
//! representative — the *row word* of the corresponding semistandard Young tableau. The
//! plactic monoid is isomorphic to the monoid of tableaux under Schensted row insertion
//! ("bumping"), and that is exactly how it is realised here: a [`PlacticElement`] stores
//! its insertion tableau `P(w)`, two words are Knuth-equivalent iff they have the same
//! insertion tableau, and the product is Schensted insertion.
//!
//! [`PlacticElement`] implements the `rustmath-core` algebraic tower
//! [`Magma`] → [`Semigroup`] → [`Monoid`]: the operation is the (associative) tableau
//! product, the identity is the empty word, and there is no inverse (a monoid, not a group).
//!
//! Reference: MAGMA Handbook, Chapter 145 §145.3–§145.4; Fulton, *Young Tableaux* [Ful97].

use crate::tableaux::{rs_insert, Tableau};
use rustmath_core::{Magma, Monoid, Semigroup};
use std::fmt;

/// An element of the plactic monoid over the positive integers.
///
/// Internally stored as its canonical representative: the semistandard insertion tableau
/// `P(w)` obtained by row-inserting the word `w` letter by letter. Two words give equal
/// elements iff they are Knuth-equivalent iff they share this tableau, so structural
/// equality of [`PlacticElement`] is exactly equality in the plactic monoid.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PlacticElement {
    tableau: Tableau,
}

impl PlacticElement {
    /// The identity element (the empty word / empty tableau).
    pub fn identity() -> Self {
        PlacticElement {
            tableau: Tableau::new(vec![]).unwrap(),
        }
    }

    /// The element for the Knuth class of a word over the positive integers, obtained by
    /// row-inserting the letters left to right into the empty tableau (`WordToTableau`).
    pub fn from_word(letters: &[usize]) -> Self {
        let mut t = Tableau::new(vec![]).unwrap();
        for &x in letters {
            t = rs_insert(&t, x);
        }
        PlacticElement { tableau: t }
    }

    /// The `i`-th generator `P.i` (the single-letter word `[i]`), `i ≥ 1`.
    pub fn generator(i: usize) -> Self {
        PlacticElement::from_word(&[i])
    }

    /// Build directly from a tableau, validating that it is semistandard
    /// (weakly increasing rows, strictly increasing columns). Returns `None` otherwise.
    pub fn from_tableau(t: Tableau) -> Option<Self> {
        if t.rows().is_empty() || t.is_semistandard() {
            Some(PlacticElement { tableau: t })
        } else {
            None
        }
    }

    /// The canonical insertion tableau `P(w)`.
    pub fn tableau(&self) -> &Tableau {
        &self.tableau
    }

    /// The canonical row word (read bottom-to-top, left-to-right); reinserting it
    /// reconstructs the tableau, and it is Knuth-equivalent to every word in the class.
    pub fn word(&self) -> Vec<usize> {
        self.tableau.reading_word()
    }

    /// `Length(u)` / `#u` — the number of letters (cells), invariant under Knuth equivalence.
    pub fn length(&self) -> usize {
        self.tableau.size()
    }

    /// True iff this is the identity (empty) element.
    pub fn is_empty(&self) -> bool {
        self.tableau.size() == 0
    }

    /// `Content(u)` — occurrence counts of the generators, invariant under Knuth
    /// equivalence. Entry `j` is the number of occurrences of the letter `j+1`; the
    /// returned vector has length equal to the largest letter present (empty if none).
    pub fn content(&self) -> Vec<usize> {
        let entries = self.tableau.content(); // sorted multiset of letters
        match entries.last() {
            None => Vec::new(),
            Some(&max) => {
                let mut counts = vec![0usize; max];
                for x in entries {
                    if x >= 1 {
                        counts[x - 1] += 1;
                    }
                }
                counts
            }
        }
    }

    /// The plactic product `self * other`, realised by row-inserting the canonical word of
    /// `other` into the tableau of `self`. Well defined (independent of representatives)
    /// and associative — this is the tableau/plactic monoid multiplication.
    pub fn product(&self, other: &PlacticElement) -> PlacticElement {
        let mut t = self.tableau.clone();
        for x in other.word() {
            t = rs_insert(&t, x);
        }
        PlacticElement { tableau: t }
    }
}

impl fmt::Display for PlacticElement {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let w = self.word();
        write!(f, "[")?;
        for (i, x) in w.iter().enumerate() {
            if i > 0 {
                write!(f, " ")?;
            }
            write!(f, "{}", x)?;
        }
        write!(f, "]")
    }
}

impl std::ops::Mul for PlacticElement {
    type Output = PlacticElement;
    fn mul(self, rhs: PlacticElement) -> PlacticElement {
        self.product(&rhs)
    }
}

// --- rustmath-core algebraic tower: Magma -> Semigroup -> Monoid --------------------

impl Magma for PlacticElement {
    fn op(&self, other: &Self) -> Self {
        self.product(other)
    }
}

// Schensted insertion realises an associative product (the plactic/tableau monoid law).
impl Semigroup for PlacticElement {}

impl Monoid for PlacticElement {
    fn identity() -> Self {
        PlacticElement::identity()
    }

    fn is_identity(&self) -> bool {
        self.is_empty()
    }
}

/// The plactic monoid over the positive integers (`PlacticIntegerMonoid()`).
///
/// A lightweight handle offering the MAGMA-style constructors; all elements are ordinary
/// [`PlacticElement`]s.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct PlacticIntegerMonoid;

impl PlacticIntegerMonoid {
    pub fn new() -> Self {
        PlacticIntegerMonoid
    }

    /// `Id(P)` — the identity (null word).
    pub fn identity(&self) -> PlacticElement {
        PlacticElement::identity()
    }

    /// `P.i` — the `i`-th generator.
    pub fn generator(&self, i: usize) -> PlacticElement {
        PlacticElement::generator(i)
    }

    /// `P ! [i_1, ..., i_n]` — the class of the word `i_1 ... i_n`.
    pub fn from_word(&self, letters: &[usize]) -> PlacticElement {
        PlacticElement::from_word(letters)
    }
}

// --- Knuth equivalence --------------------------------------------------------------

/// `IsKnuthEquivalent(w1, w2)` — true iff the two words over the positive integers can be
/// transformed into one another by elementary Knuth transformations.
///
/// Decided by the theorem that two words are Knuth-equivalent iff they have the same
/// Schensted insertion tableau `P(·)`.
pub fn is_knuth_equivalent(w1: &[usize], w2: &[usize]) -> bool {
    PlacticElement::from_word(w1) == PlacticElement::from_word(w2)
}

/// All words obtainable from `w` by a single elementary Knuth transformation (either
/// relation, either direction). Every such word is Knuth-equivalent to `w`; iterating this
/// to a fixed point enumerates the whole Knuth class.
pub fn elementary_knuth_moves(w: &[usize]) -> Vec<Vec<usize>> {
    let mut out = Vec::new();
    if w.len() < 3 {
        return out;
    }
    for i in 0..w.len() - 2 {
        let (a, b, c) = (w[i], w[i + 1], w[i + 2]);

        // Relation 1: swap the last two letters (b,c) when  min(b,c) < a ≤ max(b,c).
        //   y x z ∼ y z x   (x < y ≤ z)   [(a,b,c) = (y,x,z) with b<a≤c]
        if (b < a && a <= c) || (c < a && a <= b) {
            let mut v = w.to_vec();
            v.swap(i + 1, i + 2);
            out.push(v);
        }

        // Relation 2: swap the first two letters (a,b) when  min(a,b) ≤ c < max(a,b).
        //   x z y ∼ z x y   (x ≤ y < z)   [(a,b,c) = (x,z,y) with a≤c<b]
        if (a <= c && c < b) || (b <= c && c < a) {
            let mut v = w.to_vec();
            v.swap(i, i + 1);
            out.push(v);
        }
    }
    out
}

/// Enumerate the entire Knuth-equivalence class of a word (BFS over elementary moves).
pub fn knuth_class(w: &[usize]) -> Vec<Vec<usize>> {
    use std::collections::HashSet;
    let mut seen: HashSet<Vec<usize>> = HashSet::new();
    let mut stack = vec![w.to_vec()];
    seen.insert(w.to_vec());
    while let Some(cur) = stack.pop() {
        for nb in elementary_knuth_moves(&cur) {
            if seen.insert(nb.clone()) {
                stack.push(nb);
            }
        }
    }
    let mut v: Vec<Vec<usize>> = seen.into_iter().collect();
    v.sort();
    v
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_identity_and_empty() {
        let id = <PlacticElement as Monoid>::identity();
        assert!(id.is_identity());
        assert!(id.is_empty());
        assert_eq!(id.length(), 0);
        let g = PlacticElement::generator(3);
        assert!(!g.is_identity());
        // Identity law: id * g = g = g * id.
        assert_eq!(id.op(&g), g);
        assert_eq!(g.op(&id), g.clone());
    }

    #[test]
    fn test_from_word_tableau() {
        // Insert 2,1,3: expect P = [[1,3],[2]].
        let e = PlacticElement::from_word(&[2, 1, 3]);
        assert_eq!(e.tableau().rows(), &[vec![1, 3], vec![2]]);
        assert_eq!(e.length(), 3);
        // Canonical row word reconstructs the tableau.
        assert_eq!(PlacticElement::from_word(&e.word()), e);
    }

    #[test]
    fn test_knuth_equivalence_basic() {
        // 213 ∼ 231 (elementary Knuth move); both insert to [[1,3],[2]].
        assert!(is_knuth_equivalent(&[2, 1, 3], &[2, 3, 1]));
        // 213 not equivalent to 123.
        assert!(!is_knuth_equivalent(&[2, 1, 3], &[1, 2, 3]));
    }

    #[test]
    fn test_elementary_moves_preserve_class() {
        let w = vec![2, 1, 3, 1, 2];
        for nb in elementary_knuth_moves(&w) {
            assert!(
                is_knuth_equivalent(&w, &nb),
                "move {:?} -> {:?} changed the class",
                w,
                nb
            );
        }
    }

    #[test]
    fn test_knuth_class_all_same_tableau() {
        let w = vec![3, 1, 2, 2, 1];
        let class = knuth_class(&w);
        let p0 = PlacticElement::from_word(&w);
        assert!(class.len() > 1);
        for member in &class {
            assert_eq!(PlacticElement::from_word(member), p0);
        }
    }

    #[test]
    fn test_associativity() {
        // (a*b)*c = a*(b*c) for the core Magma operation.
        let a = PlacticElement::from_word(&[2, 1, 3]);
        let b = PlacticElement::from_word(&[1, 2]);
        let c = PlacticElement::from_word(&[3, 1]);
        let left = a.op(&b).op(&c);
        let right = a.op(&b.op(&c));
        assert_eq!(left, right);
        // And it agrees with inserting the concatenation directly.
        let mut concat = vec![2, 1, 3];
        concat.extend_from_slice(&[1, 2]);
        concat.extend_from_slice(&[3, 1]);
        assert_eq!(left, PlacticElement::from_word(&concat));
    }

    #[test]
    fn test_product_matches_concatenation() {
        // [u]·[v] = [uv] in the plactic monoid.
        let u = &[3, 1, 4, 1, 5][..];
        let v = &[9, 2, 6][..];
        let prod = PlacticElement::from_word(u).op(&PlacticElement::from_word(v));
        let mut uv = u.to_vec();
        uv.extend_from_slice(v);
        assert_eq!(prod, PlacticElement::from_word(&uv));
    }

    #[test]
    fn test_length_and_content_invariant() {
        // Knuth-equivalent words share Length and Content.
        let w = vec![2, 1, 3, 1, 2];
        let e = PlacticElement::from_word(&w);
        for member in knuth_class(&w) {
            let f = PlacticElement::from_word(&member);
            assert_eq!(e.length(), f.length());
            assert_eq!(e.content(), f.content());
        }
        // Content of 2,1,3,1,2 over {1,2,3}: 1 appears 2, 2 appears 2, 3 appears 1.
        assert_eq!(e.content(), vec![2, 2, 1]);
    }

    #[test]
    fn test_generator_product() {
        let p = PlacticIntegerMonoid::new();
        // P.1 * P.2 = word [1,2] -> tableau [[1,2]].
        let e = p.generator(1).op(&p.generator(2));
        assert_eq!(e.tableau().rows(), &[vec![1, 2]]);
    }

    #[test]
    fn test_from_tableau_validation() {
        // Valid semistandard tableau accepted.
        let t = Tableau::new(vec![vec![1, 1, 2], vec![2, 3]]).unwrap();
        assert!(PlacticElement::from_tableau(t).is_some());
        // Non-semistandard (row not weakly increasing) rejected.
        let bad = Tableau::new(vec![vec![2, 1]]).unwrap();
        assert!(PlacticElement::from_tableau(bad).is_none());
    }
}
