//! Abelian-extension realization: given `(K, m, H)` with `H ≤ Cl_m` of index
//! `n`, construct the abelian extension `L/K` of degree `n` cut out by `H`
//! (Magma `AbelianExtension` / `RayClassField`, Handbook Ch. 39).
//!
//! Two construction routes, selected by the arithmetic of `K`:
//!
//! * **Kummer** — when `μ_n ⊂ K` (`K` contains the `n`-th roots of unity), a
//!   cyclic degree-`n` `L/K` is `K(γ^{1/n})` for some `γ ∈ K^×`. We obtain the
//!   Kummer generator `γ` from the `s_unit`/ray-class data: `γ` is the element
//!   whose ideal `(γ)` represents (the right power of) the class generating
//!   `Cl_m / H`. The defining polynomial of `L` relative to `K` is `xⁿ − γ`.
//!
//! * **Gaussian periods (cyclic over ℚ)** — when `K = ℚ` and the modulus is a
//!   prime conductor `p` with `n | (p − 1)`, the cyclic degree-`n` subfield of
//!   `ℚ(ζ_p)` is generated by the **Gaussian periods** `η_j = Σ_{k ∈ Cⱼ} ζ_p^k`
//!   over the cosets `Cⱼ` of the index-`n` subgroup of `(ℤ/p)^×`. Their
//!   symmetric functions are integers (computed exactly in `ℤ[ζ_p]` via
//!   `Σ_{k=1}^{p−1} ζ^k = −1`), giving the absolute defining polynomial directly.
//!   This realizes e.g. the cyclic cubic of conductor 7 (`x³+x²−2x−1`, disc 49)
//!   and `ℚ(√5)` (conductor 5).
//!
//! The output [`AbelianExtension`] carries the relative and (when available)
//! absolute defining polynomials, the degree, the conductor and the predicted
//! discriminant + signature, with the GRH flag propagated from the ray class
//! group.

use crate::artin::{Conductor, NormGroup};
use crate::rayclass::{ray_class_group, Modulus};
use crate::round2::{field_discriminant, polredabs};
use crate::units::{roots_of_unity_count, signature};
use rustmath_integers::Integer;

// (Phase 1 ABEXT + ARTIN)

/// The construction route used for an abelian layer.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ConstructionMethod {
    /// `K(γ^{1/n})`, `μ_n ⊂ K`. The Kummer generator `γ` is recorded.
    Kummer,
    /// Gaussian periods of `ℚ(ζ_p)` (cyclic over `ℚ`, prime conductor).
    GaussianPeriods,
    /// Structure known but explicit generator not produced (placeholder).
    Abstract,
}

/// An abelian extension `L/K` of degree `n` cut out by a norm subgroup
/// `H ≤ Cl_m`.
#[derive(Clone, Debug)]
pub struct AbelianExtension {
    /// Defining polynomial of `K` (monic, low-to-high).
    pub base: Vec<Integer>,
    /// Degree `[L:K] = n = [Cl_m : H]`.
    pub degree: usize,
    /// Construction route taken.
    pub method: ConstructionMethod,
    /// Relative defining polynomial of `L/K` (coefficients in `K`, here encoded
    /// as integer/rational power-basis vectors of `K`). For Kummer this is
    /// `xⁿ − γ`, with `gamma` the generator. `None` if only an absolute model
    /// was produced.
    pub relative_poly: Option<RelativePoly>,
    /// Absolute defining polynomial of `L` over `ℚ` (monic, low-to-high), when
    /// feasible — `polredabs`-reduced.
    pub absolute_poly: Option<Vec<Integer>>,
    /// The conductor `f(H) | m`.
    pub conductor: Conductor,
    /// Predicted absolute discriminant `|D_L|` (conductor–discriminant formula).
    pub predicted_disc: Integer,
    /// Predicted signature `(r₁, r₂)` of `L`.
    pub predicted_signature: (usize, usize),
    /// GRH-conditional flag (from the ray class group).
    pub grh_conditional: bool,
}

/// A relative defining polynomial `xⁿ − γ` (Kummer) or general monic relative
/// polynomial, with coefficients given as elements of `K` (power-basis
/// rational-coordinate vectors; here we only need the Kummer generator).
#[derive(Clone, Debug)]
pub struct RelativePoly {
    /// Degree `n`.
    pub degree: usize,
    /// The Kummer generator `γ` (integral-basis coords of `K`), so `L = K(γ^{1/n})`
    /// and the relative polynomial is `xⁿ − γ`.
    pub kummer_gamma: Option<Vec<Integer>>,
}

/// Construct the abelian extension `L/K` of degree `n` cut out by `H ≤ Cl_m`.
///
/// `f` is the defining polynomial of `K`; `m` the modulus; `h` the norm
/// subgroup (its index is the degree). Returns `None` when neither construction
/// route applies (e.g. `μ_n ⊄ K` and `K ≠ ℚ` — the explicit ray-class-field
/// route for a nontrivial base is deferred to the Phase-2 driver).
pub fn abelian_extension(
    f: &[Integer],
    m: &Modulus,
    h: &NormGroup,
) -> Option<AbelianExtension> {
    let n = h.index;
    if n == 0 {
        return None;
    }
    let rcg = ray_class_group(f, m)?;
    let grh = rcg.grh_conditional;
    let cond = Conductor::of_norm_group(f, m, n)?;
    let base_deg = f.len() - 1;

    // --- Route selection ---
    // Cyclic over Q with prime conductor: Gaussian periods (exact, absolute).
    if base_deg == 1 && is_prime(cond.finite) && (cond.finite - 1) as usize % n == 0 {
        if let Some(abs_poly) = gaussian_period_poly(cond.finite, n) {
            let reduced = polredabs(&abs_poly);
            let predicted_disc = cond.predicted_disc_cyclic(f, n);
            let predicted_signature = predicted_signature_over_q(&reduced, n);
            return Some(AbelianExtension {
                base: f.to_vec(),
                degree: n,
                method: ConstructionMethod::GaussianPeriods,
                relative_poly: None,
                absolute_poly: Some(reduced),
                conductor: cond,
                predicted_disc,
                predicted_signature,
                grh_conditional: grh,
            });
        }
    }

    // Kummer: μ_n ⊂ K. Pull a Kummer generator from the ray-class / s-unit data.
    if roots_of_unity_count(f) % n == 0 {
        let gamma = kummer_generator(f, m, &rcg, n);
        let predicted_disc = cond.predicted_disc_cyclic(f, n);
        let predicted_signature = predicted_signature_kummer(f, n, &cond);
        return Some(AbelianExtension {
            base: f.to_vec(),
            degree: n,
            method: ConstructionMethod::Kummer,
            relative_poly: Some(RelativePoly { degree: n, kummer_gamma: gamma }),
            absolute_poly: None,
            conductor: cond,
            predicted_disc,
            predicted_signature,
            grh_conditional: grh,
        });
    }

    // Structure known, explicit model deferred.
    let predicted_disc = cond.predicted_disc_cyclic(f, n);
    let predicted_signature = predicted_signature_kummer(f, n, &cond);
    Some(AbelianExtension {
        base: f.to_vec(),
        degree: n,
        method: ConstructionMethod::Abstract,
        relative_poly: None,
        absolute_poly: None,
        conductor: cond,
        predicted_disc,
        predicted_signature,
        grh_conditional: grh,
    })
}

// --------------------------------------------------------------------------- //
// Gaussian periods: cyclic degree-n subfield of Q(ζ_p), p prime, n | (p−1).
// --------------------------------------------------------------------------- //

/// The minimal polynomial (monic, low-to-high) of the Gaussian periods of the
/// cyclic degree-`n` subfield of `ℚ(ζ_p)`. Exact integer arithmetic in `ℤ[ζ_p]`.
///
/// Let `g` be a primitive root mod `p`, `H = ⟨g^n⟩ ≤ (ℤ/p)^×` of index `n`, and
/// `Cⱼ = g^j·H` the `n` cosets. The periods are `η_j = Σ_{k ∈ Cⱼ} ζ^k`. The
/// `η_j` are the roots of a degree-`n` polynomial with integer coefficients
/// `∏ⱼ (x − η_j) = xⁿ − e₁ xⁿ⁻¹ + … ± eₙ`, the `eᵢ` being elementary symmetric
/// integers obtained by reducing products of periods (each a `ℤ`-combination of
/// `ζ` powers) using `Σ_{k=1}^{p−1} ζ^k = −1`.
pub fn gaussian_period_poly(p: i64, n: usize) -> Option<Vec<Integer>> {
    if !is_prime(p) || n == 0 || (p - 1) as usize % n != 0 {
        return None;
    }
    let pu = p as usize;
    let f_len = pu; // cosets index 0..p; we use the additive representation length p
    let g = primitive_root(p)?;
    // build the index-n subgroup cosets of (Z/p)^×.
    let subgroup_size = (pu - 1) / n;
    // powers g^0, g^1, ... mod p (the cyclic ordering of (Z/p)^×).
    let mut powers = Vec::with_capacity(pu - 1);
    let mut cur = 1i64;
    for _ in 0..(pu - 1) {
        powers.push(cur);
        cur = (cur * g) % p;
    }
    // coset C_j = { powers[j + n*t] : t } , j = 0..n
    // period η_j as a vector over ζ-powers: counts[k] = multiplicity of ζ^k.
    let period_vec = |j: usize| -> Vec<i64> {
        let mut v = vec![0i64; f_len];
        for t in 0..subgroup_size {
            let idx = j + n * t;
            let k = powers[idx % (pu - 1)] as usize;
            v[k] += 1;
        }
        v
    };
    let periods: Vec<Vec<i64>> = (0..n).map(period_vec).collect();

    // Multiply two ζ-power vectors mod (Σ_{k=1}^{p-1} ζ^k = −1, ζ^p = 1).
    // Represent in the basis {ζ^0=1, ζ^1, …, ζ^{p-1}} then reduce ζ^0..: we keep
    // length p and reduce powers mod p; the relation 1 + ζ + … + ζ^{p−1} = 0 is
    // applied at the end when extracting an integer (a period product is always a
    // rational integer for these symmetric expressions, so we can subtract the
    // ζ^1..ζ^{p−1} coefficients uniformly).
    let mul = |a: &[i64], b: &[i64]| -> Vec<i64> {
        let mut out = vec![0i64; f_len];
        for (i, &ai) in a.iter().enumerate() {
            if ai == 0 {
                continue;
            }
            for (jx, &bj) in b.iter().enumerate() {
                if bj == 0 {
                    continue;
                }
                out[(i + jx) % pu] += ai * bj;
            }
        }
        out
    };
    let add = |a: &[i64], b: &[i64]| -> Vec<i64> {
        (0..f_len).map(|k| a[k] + b[k]).collect()
    };

    // Elementary symmetric polynomials e_1..e_n of the periods, as ζ-vectors,
    // via Newton's identities are heavy; instead expand ∏ (x − η_j) directly.
    // poly[d] = coefficient of x^d, each a ζ-vector. Start with constant 1.
    let mut poly: Vec<Vec<i64>> = vec![{
        let mut one = vec![0i64; f_len];
        one[0] = 1;
        one
    }];
    for per in &periods {
        // multiply current poly by (x − η_j)
        let mut next: Vec<Vec<i64>> = vec![vec![0i64; f_len]; poly.len() + 1];
        for (d, coeff) in poly.iter().enumerate() {
            // x · coeff  -> degree d+1
            next[d + 1] = add(&next[d + 1], coeff);
            // (−η_j) · coeff -> degree d
            let neg = mul(per, coeff).iter().map(|&x| -x).collect::<Vec<_>>();
            next[d] = add(&next[d], &neg);
        }
        poly = next;
    }

    // Reduce each coefficient ζ-vector to an integer using 1 + ζ + … + ζ^{p−1}=0,
    // i.e. ζ^k (k≥1) contributes; subtract the common value so that a pure
    // integer remains. A symmetric coefficient has the form c0·1 + c·(ζ+…+ζ^{p−1})
    // = c0 − c (since ζ+…+ζ^{p−1} = −1). We verify c1 = c2 = … and use c0 − c1.
    let mut coeffs = Vec::with_capacity(poly.len());
    for coeff in &poly {
        let c0 = coeff[0];
        let c1 = coeff.get(1).copied().unwrap_or(0);
        // sanity: all ζ^k (k≥1) coefficients equal (true for Galois-symmetric
        // expressions); if not, the expression was not in the fixed field.
        for k in 2..pu {
            if coeff[k] != c1 {
                return None;
            }
        }
        coeffs.push(Integer::from(c0 - c1));
    }
    Some(coeffs)
}

/// Smallest primitive root mod prime `p`.
fn primitive_root(p: i64) -> Option<i64> {
    if p == 2 {
        return Some(1);
    }
    let phi = p - 1;
    let factors = distinct_prime_factors(phi);
    for g in 2..p {
        if factors.iter().all(|&q| mod_pow(g, phi / q, p) != 1) {
            return Some(g);
        }
    }
    None
}

fn mod_pow(mut b: i64, mut e: i64, m: i64) -> i64 {
    let mut r = 1i64 % m;
    b %= m;
    while e > 0 {
        if e & 1 == 1 {
            r = (r * b) % m;
        }
        b = (b * b) % m;
        e >>= 1;
    }
    r
}

fn distinct_prime_factors(mut n: i64) -> Vec<i64> {
    let mut out = Vec::new();
    let mut d = 2i64;
    while d * d <= n {
        if n % d == 0 {
            out.push(d);
            while n % d == 0 {
                n /= d;
            }
        }
        d += 1;
    }
    if n > 1 {
        out.push(n);
    }
    out
}

fn is_prime(p: i64) -> bool {
    if p < 2 {
        return false;
    }
    let mut d = 2i64;
    while d * d <= p {
        if p % d == 0 {
            return false;
        }
        d += 1;
    }
    true
}

// --------------------------------------------------------------------------- //
// Kummer generator from the ray-class / s-unit data
// --------------------------------------------------------------------------- //

/// A Kummer generator `γ ∈ K^×` for the cyclic degree-`n` extension cut out by
/// `H` (requires `μ_n ⊂ K`): an element whose ideal class generates `Cl_m / H`
/// to the `n`-th power. We take a generator of a factor-base prime that is
/// nontrivial mod `H`. Returns its integral-basis coordinates, or `None` if no
/// suitable principal generator is found by the small search.
fn kummer_generator(
    f: &[Integer],
    _m: &Modulus,
    rcg: &crate::rayclass::RayClassGroup,
    n: usize,
) -> Option<Vec<Integer>> {
    use crate::classgroup::is_principal;
    use crate::ideals::ideal_mul;
    use crate::round2::maximal_order_data;
    let ord = maximal_order_data(f);
    // Look for a factor-base prime 𝔭 whose n-th power is principal: then its
    // generator γ gives K(γ^{1/n}) ramified exactly where 𝔭 sits.
    for pr in rcg.factor_base() {
        let mut pk = pr.clone();
        for _ in 1..n {
            pk = ideal_mul(&ord, &pk, pr);
        }
        if let Some(gamma) = is_principal(f, &ord, &pk) {
            return Some(gamma);
        }
    }
    None
}

// --------------------------------------------------------------------------- //
// Signature prediction
// --------------------------------------------------------------------------- //

/// Signature `(r₁, r₂)` of a cyclic degree-`n` extension of `ℚ` given by its
/// (absolute) defining polynomial — read directly off the polynomial.
fn predicted_signature_over_q(abs_poly: &[Integer], _n: usize) -> (usize, usize) {
    signature(abs_poly)
}

/// Predicted signature of a degree-`n` abelian `L/K` from `K`'s signature and
/// the real places ramified in the conductor.
///
/// Each real place of `K` **in** the conductor `m_∞` ramifies — it becomes a
/// single complex place upstairs (its `n` extensions pair up). Each real place
/// **not** in `m_∞` stays real and splits into `n` real places. Complex places
/// of `K` each give `n` complex places of `L`.
fn predicted_signature_kummer(
    f: &[Integer],
    n: usize,
    cond: &Conductor,
) -> (usize, usize) {
    let (r1_k, r2_k) = signature(f);
    let ramified: usize = cond.real_places.len().min(r1_k);
    let unramified_real = r1_k - ramified;
    // unramified real places: each splits into n real places.
    let r1_l = unramified_real * n;
    // ramified real places: each contributes n/... extensions that are complex;
    // n real extensions collapse into n/2 complex pairs each (n even) — for the
    // signature lever the count of complex pairs from ramified real places is
    // ramified·(n/2) when n even; for n odd a real place cannot ramify in a real
    // sense, so it stays real (no sign constraint), giving ramified·n real.
    let (extra_r1, extra_r2) = if n % 2 == 0 {
        (0usize, ramified * (n / 2))
    } else {
        (ramified * n, 0usize)
    };
    let r1 = r1_l + extra_r1;
    let r2 = r2_k * n + extra_r2;
    (r1, r2)
}

/// Convenience: absolute discriminant of a field from its polynomial (for
/// cross-checking a constructed absolute model against the prediction).
pub fn absolute_disc(poly: &[Integer]) -> Integer {
    field_discriminant(poly).abs()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::artin::NormGroup;

    fn iz(v: &[i64]) -> Vec<Integer> {
        v.iter().map(|&x| Integer::from(x)).collect()
    }

    fn report(name: &str, ext: &AbelianExtension) {
        println!(
            "[abext] {}: degree={} method={:?} conductor=(f0={}, real_places={:?}) predicted_disc={} signature=(r1={},r2={}) abs_poly={:?} grh={}",
            name,
            ext.degree,
            ext.method,
            ext.conductor.finite,
            ext.conductor.real_places,
            ext.predicted_disc,
            ext.predicted_signature.0,
            ext.predicted_signature.1,
            ext.absolute_poly,
            ext.grh_conditional
        );
    }

    // ---- Cyclic cubic of conductor 7 via Gaussian periods ----
    #[test]
    fn cyclic_cubic_conductor_7_field() {
        // The exact Gaussian-period polynomial for p=7, n=3 is x³+x²−2x−1.
        let poly = gaussian_period_poly(7, 3).expect("period poly");
        // monic low-to-high; compare up to the known model x³ + x² − 2x − 1.
        assert_eq!(poly, iz(&[-1, -2, 1, 1]), "Gaussian period cubic of cond 7");
        // its discriminant is 7² = 49.
        let d = absolute_disc(&poly);
        assert_eq!(d, Integer::from(49), "disc of cyclic cubic cond 7 = 49");

        // full construction path: K = Q, m = (7), H of index 3.
        let f = iz(&[0, 1]); // Q
        let m = Modulus::finite(7);
        let rcg = ray_class_group(&f, &m).expect("rcg");
        let h = NormGroup::of_index(&rcg, 3).expect("index-3 subgroup");
        let ext = abelian_extension(&f, &m, &h).expect("extension");
        report("cyclic cubic cond 7", &ext);
        assert_eq!(ext.degree, 3);
        assert_eq!(ext.method, ConstructionMethod::GaussianPeriods);
        assert_eq!(ext.predicted_disc, Integer::from(49));
        // the absolute (polredabs) model must itself have discriminant 49.
        let abs = ext.absolute_poly.as_ref().expect("abs poly");
        assert_eq!(absolute_disc(abs), Integer::from(49));
        // totally real cyclic cubic: signature (3,0).
        assert_eq!(ext.predicted_signature, (3, 0));
    }

    // ---- Q(√5) (conductor 5) via Gaussian periods (n = 2) ----
    #[test]
    fn quadratic_conductor_5_field() {
        // p=5, n=2: periods give x² + x − 1 (a generator of Q(√5)); disc 5.
        let poly = gaussian_period_poly(5, 2).expect("period poly");
        let d = absolute_disc(&poly);
        assert_eq!(d, Integer::from(5), "disc Q(√5) = 5");

        let f = iz(&[0, 1]); // Q
        let m = Modulus::finite(5);
        let rcg = ray_class_group(&f, &m).expect("rcg");
        let h = NormGroup::of_index(&rcg, 2).expect("index-2 subgroup");
        let ext = abelian_extension(&f, &m, &h).expect("extension");
        report("Q(√5)/Q cond 5", &ext);
        assert_eq!(ext.degree, 2);
        assert_eq!(ext.predicted_disc, Integer::from(5));
        let abs = ext.absolute_poly.as_ref().expect("abs poly");
        assert_eq!(absolute_disc(abs), Integer::from(5));
        // real quadratic ⇒ (2,0).
        assert_eq!(ext.predicted_signature, (2, 0));
    }

    // ---- Cyclic quartic of conductor 5: x⁴+x³+x²+x+1 → Q(ζ_5), degree 4 ----
    #[test]
    fn cyclic_quartic_conductor_5() {
        // p=5, n=4: the full Q(ζ_5), period poly = the cyclotomic x⁴+x³+x²+x+1.
        let poly = gaussian_period_poly(5, 4).expect("period poly");
        assert_eq!(poly, iz(&[1, 1, 1, 1, 1]), "Q(ζ_5) cyclotomic poly");
        // disc(Q(ζ_5)) = 125 = 5³.
        let d = absolute_disc(&poly);
        assert_eq!(d, Integer::from(125), "disc Q(ζ_5) = 5³ = 125");
        // conductor–discriminant: |D| = 1·∏ N(f(χ)) = 5·5·5 (three nontrivial
        // characters of conductor 5) = 125.
        let predicted = crate::disc_score::disc_from_conductors(
            0.0,
            &[Integer::from(1), Integer::from(5), Integer::from(5), Integer::from(5)],
        );
        assert!((predicted - 125.0_f64.ln()).abs() < 1e-9);
    }

    // ---- Kummer route selection over Q(i) (μ_4 ⊂ K is not μ_n for n=2? μ_2⊂K) ----
    #[test]
    fn kummer_route_over_qi() {
        // K = Q(i) contains μ_4 ⊃ μ_2. A degree-2 layer can go Kummer (n=2 | 4).
        let f = iz(&[1, 0, 1]); // Q(i)
        let m = Modulus::finite(5);
        let rcg = ray_class_group(&f, &m).expect("rcg");
        // Cl_m for Q(i), m=(5) has order 4 (from rayclass tests). Take index-2 H.
        if let Some(h) = NormGroup::of_index(&rcg, 2) {
            if let Some(ext) = abelian_extension(&f, &m, &h) {
                report("Kummer over Q(i)", &ext);
                // route should be Kummer (μ_2 ⊂ Q(i)); generator may or may not be
                // found by the small search, but the method is Kummer.
                assert_eq!(ext.degree, 2);
                assert_eq!(ext.method, ConstructionMethod::Kummer);
            }
        }
    }
}
