//! Local field decomposition of a number field at a rational prime, and the
//! unramified extension `ℚ_q = ℚ_p(ω)` arithmetic (Module 9).
//!
//! For `K = ℚ[x]/(f)` and a rational prime `p`, the completion splits as
//! `K ⊗_ℚ ℚ_p = ∏_{𝔭∣p} K_𝔭`, one local field per prime above `p`. Each `K_𝔭/ℚ_p`
//! carries:
//! - ramification index `e` and residue degree `f` (`Σ eᵢ fᵢ = [K:ℚ]`), from the
//!   prime decomposition ([`crate::ideals::prime_decomposition`], valid even at
//!   index-dividing primes via the Montes fallback);
//! - its **residue field** `F_{p^f}` (the `(p, f)` descriptor; the unramified
//!   extension arithmetic below realizes its lift to `ℤ_q`);
//! - a **ramification class**: *unramified* (`e=1`), *tame* (`e>1`, `p∤e`), or
//!   *wild* (`p∣e`);
//! - the **different exponent** `d = v_𝔭(𝔡_{K_𝔭/ℚ_p})`, with local-disc exponent
//!   `f·d`. The local–global formula is `Σ_𝔭 fᵢ dᵢ = v_p(disc_K)`.
//!
//! Different exponents: `d = 0` (unramified), `d = e−1` (tame). The wild exponent
//! is **not** determined by `(e,f)` alone (`x²+1` at 2 has `e=2, d=2`; `x⁴−2` at 2
//! has `e=4, d=11`); when a single wild prime lies above `p` it is recovered exactly
//! from `v_p(disc_K)`. With several wild primes above one `p` the split is left
//! `None` (it needs the higher-order Montes / ramification-filtration data).
//!
//! The **unramified extension** `ℚ_q/ℚ_p` of degree `f` is `ℤ_q = ℤ_p[ω]/(m(ω))` for
//! a monic lift `m` of an irreducible degree-`f` polynomial over `F_p`. Its Galois
//! group is cyclic `C_f`, generated by the **Frobenius** `φ: x ↦ x^p`; the residue
//! field `F_{p^f}` is `ℤ_q/(p)` and `φ` reduces to the residue-field Frobenius. This
//! is the per-prime local piece of the global Frobenius (and the unramified part of
//! every local Galois group). Ported from the p-adelic Engine `UnramifiedElement`.

use crate::ideals::prime_decomposition;
use crate::round2::field_discriminant;
use rustmath_integers::Integer;
use rustmath_polynomials::fp_factor;

/// Is `cand` (little-endian, monic, degree `deg`) irreducible over `F_p`? True iff
/// its factorization is a single factor of the full degree.
fn is_irreducible_fp(cand: &[i64], p: i64) -> bool {
    let deg = fp_factor::degree(cand);
    if deg < 1 {
        return false;
    }
    let fac = fp_factor::factor(cand, p);
    fac.len() == 1 && fp_factor::degree(&fac[0]) == deg
}

/// Ramification class of a local field `K_𝔭/ℚ_p`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Ramification {
    /// `e = 1`.
    Unramified,
    /// `e > 1` and `p ∤ e`.
    Tame,
    /// `p ∣ e`.
    Wild,
}

/// Residue field `F_{p^f}` descriptor (the residue field of `K_𝔭`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ResidueField {
    pub characteristic: i64,
    /// Residue degree `f`, so the field is `F_{p^f}`.
    pub degree: usize,
}

impl ResidueField {
    /// `|F_{p^f}| = p^f`.
    pub fn size(&self) -> Integer {
        Integer::from(self.characteristic).pow(self.degree as u32)
    }
    /// Order of the Frobenius `x ↦ x^p`, i.e. `f` — equivalently the order of the
    /// cyclic Galois group `Gal(F_{p^f}/F_p) ≅ C_f` of the residue extension. For an
    /// **unramified** local field this is also `Gal(K_𝔭/ℚ_p)` (generated by the
    /// Frobenius), which is the per-prime local piece of the global Frobenius.
    pub fn frobenius_order(&self) -> usize {
        self.degree
    }
}

/// One local field `K_𝔭` above `p`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LocalFactor {
    pub e: usize,
    pub f: usize,
    pub ramification: Ramification,
    pub residue_field: ResidueField,
    /// Different exponent `d = v_𝔭(𝔡_{K_𝔭/ℚ_p})`. `None` for an undetermined wild
    /// prime (≥ 2 wild primes above `p`).
    pub different_exp: Option<i64>,
}

impl LocalFactor {
    /// Local discriminant exponent `f·d` (so `Σ disc_exp = v_p(disc_K)`).
    pub fn disc_exp(&self) -> Option<i64> {
        self.different_exp.map(|d| self.f as i64 * d)
    }
    /// Degree `[K_𝔭 : ℚ_p] = e·f`.
    pub fn local_degree(&self) -> usize {
        self.e * self.f
    }
}

/// `v_p(disc_K)` — the exponent of `p` in the field discriminant.
pub fn local_discriminant_exponent(f: &[Integer], p: i64) -> i64 {
    let d = field_discriminant(f);
    if d.is_zero() {
        return 0;
    }
    d.abs().valuation(&Integer::from(p)) as i64
}

/// The local fields `K_𝔭` above `p`, i.e. the factors of `K ⊗ ℚ_p`. Returns `None`
/// if the prime decomposition is unresolved (non-regular polygon needing
/// higher-order Montes — see [`prime_decomposition`]).
pub fn local_decomposition(f: &[Integer], p: i64) -> Option<Vec<LocalFactor>> {
    let dec = prime_decomposition(f, p);
    if !dec.montes_resolved {
        return None;
    }
    let vdisc = local_discriminant_exponent(f, p);
    let pu = p as usize;

    let mut factors: Vec<LocalFactor> = Vec::new();
    let mut known_sum: i64 = 0; // Σ f_i d_i over unramified+tame factors
    let mut wild_idx: Vec<usize> = Vec::new();

    for (e, fdeg) in dec.ef() {
        let ram = if e == 1 {
            Ramification::Unramified
        } else if e % pu != 0 {
            Ramification::Tame
        } else {
            Ramification::Wild
        };
        let d = match ram {
            Ramification::Unramified => Some(0),
            Ramification::Tame => Some((e - 1) as i64),
            Ramification::Wild => None,
        };
        if let Some(dv) = d {
            known_sum += fdeg as i64 * dv;
        } else {
            wild_idx.push(factors.len());
        }
        factors.push(LocalFactor {
            e,
            f: fdeg,
            ramification: ram,
            residue_field: ResidueField { characteristic: p, degree: fdeg },
            different_exp: d,
        });
    }

    // Recover a unique wild prime's different exponent from the global disc valuation.
    if wild_idx.len() == 1 {
        let i = wild_idx[0];
        let fi = factors[i].f as i64;
        let wild_total = vdisc - known_sum;
        if fi > 0 && wild_total % fi == 0 {
            factors[i].different_exp = Some(wild_total / fi);
        }
    }

    Some(factors)
}

// --------------------------------------------------------------------------- //
// Unramified extension ℚ_q = ℚ_p(ω), arithmetic in ℤ_q = ℤ/p^N[ω]/(m(ω))
// --------------------------------------------------------------------------- //

/// An element of the unramified extension `ℤ_q = ℤ_p[ω]/(m(ω))`, truncated to
/// precision `p^N`. Coefficients are `Integer`s reduced into `[0, p^N)`; `coeffs`
/// has length `f = deg m`. `m` is a monic integer lift of an irreducible polynomial
/// over `F_p` (little-endian, `modulus[f] = 1`). Arithmetic is mod `(m, p^N)`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UnramifiedElement {
    pub prime: i64,
    /// Precision: arithmetic is modulo `p^precision`.
    pub precision: u32,
    /// Monic lift of the residue-field defining polynomial (little-endian).
    pub modulus: Vec<Integer>,
    /// Coefficients of `c₀ + c₁ω + … + c_{f−1}ω^{f−1}`, length `f`.
    pub coeffs: Vec<Integer>,
}

impl UnramifiedElement {
    fn f_deg(&self) -> usize {
        self.modulus.len() - 1
    }

    fn norm_coeffs(prime: i64, precision: u32, mut coeffs: Vec<Integer>, f: usize) -> Vec<Integer> {
        let m = Integer::from(prime).pow(precision);
        coeffs.resize(f, Integer::zero());
        for c in coeffs.iter_mut() {
            let r = c.clone() % m.clone();
            *c = if r.signum() < 0 { r + m.clone() } else { r };
        }
        coeffs
    }

    /// Build an element from raw coefficients (reduced mod `(m, p^precision)`).
    pub fn new(prime: i64, precision: u32, modulus: Vec<Integer>, coeffs: Vec<Integer>) -> Self {
        let f = modulus.len() - 1;
        let coeffs = Self::norm_coeffs(prime, precision, coeffs, f);
        UnramifiedElement { prime, precision, modulus, coeffs }
    }

    /// `0`.
    pub fn zero(prime: i64, precision: u32, modulus: Vec<Integer>) -> Self {
        let f = modulus.len() - 1;
        UnramifiedElement { prime, precision, modulus, coeffs: vec![Integer::zero(); f] }
    }

    /// `1`.
    pub fn one(prime: i64, precision: u32, modulus: Vec<Integer>) -> Self {
        Self::new(prime, precision, modulus, vec![Integer::one()])
    }

    /// The canonical generator `ω` (a lift of a residue-field generator).
    pub fn generator(prime: i64, precision: u32, modulus: Vec<Integer>) -> Self {
        Self::new(prime, precision, modulus, vec![Integer::zero(), Integer::one()])
    }

    /// Embed an integer constant.
    pub fn from_int(prime: i64, precision: u32, modulus: Vec<Integer>, n: Integer) -> Self {
        Self::new(prime, precision, modulus, vec![n])
    }

    pub fn is_zero(&self) -> bool {
        self.coeffs.iter().all(|c| c.is_zero())
    }

    pub fn add(&self, other: &Self) -> Self {
        let f = self.f_deg();
        let c: Vec<Integer> =
            (0..f).map(|i| self.coeffs[i].clone() + other.coeffs[i].clone()).collect();
        Self::new(self.prime, self.precision, self.modulus.clone(), c)
    }

    pub fn neg(&self) -> Self {
        let c: Vec<Integer> = self.coeffs.iter().map(|x| -x.clone()).collect();
        Self::new(self.prime, self.precision, self.modulus.clone(), c)
    }

    pub fn sub(&self, other: &Self) -> Self {
        self.add(&other.neg())
    }

    pub fn mul(&self, other: &Self) -> Self {
        let f = self.f_deg();
        // Schoolbook multiply into a 2f−1 buffer, then reduce by the monic modulus.
        let mut raw = vec![Integer::zero(); 2 * f - 1];
        for i in 0..f {
            if self.coeffs[i].is_zero() {
                continue;
            }
            for j in 0..f {
                raw[i + j] = raw[i + j].clone() + self.coeffs[i].clone() * other.coeffs[j].clone();
            }
        }
        // Reduce x^k (k from 2f−2 down to f) using x^f = −Σ_{i<f} m_i x^i.
        for k in (f..=2 * f - 2).rev() {
            let leading = raw[k].clone();
            if leading.is_zero() {
                continue;
            }
            for i in 0..f {
                let idx = (k - f) + i;
                raw[idx] = raw[idx].clone() - leading.clone() * self.modulus[i].clone();
            }
            raw[k] = Integer::zero();
        }
        raw.truncate(f);
        Self::new(self.prime, self.precision, self.modulus.clone(), raw)
    }

    /// Repeated-squaring power (`n ≥ 0`).
    pub fn pow(&self, mut n: u64) -> Self {
        let mut result = Self::one(self.prime, self.precision, self.modulus.clone());
        let mut base = self.clone();
        while n > 0 {
            if n & 1 == 1 {
                result = result.mul(&base);
            }
            n >>= 1;
            if n > 0 {
                base = base.mul(&base);
            }
        }
        result
    }

    /// Constant `n` embedded in this field (same prime/precision/modulus).
    fn constant(&self, n: Integer) -> Self {
        Self::from_int(self.prime, self.precision, self.modulus.clone(), n)
    }

    /// Evaluate the integer polynomial `coeffs` (little-endian) at `self` via Horner,
    /// treating coefficients as `ℤ_p` constants. Returns an element of `ℤ_q`.
    fn eval_int_poly(&self, coeffs: &[Integer]) -> Self {
        let mut result = Self::zero(self.prime, self.precision, self.modulus.clone());
        for c in coeffs.iter().rev() {
            result = result.mul(self).add(&self.constant(c.clone()));
        }
        result
    }

    /// Inverse of a residue-unit (residue ≠ 0) in `F_{p^f}`, lifted as a `ℤ_q`
    /// element with coefficients in `[0, p)` (i.e. the level-0 inverse).
    fn residue_inverse(&self) -> Self {
        let a: Vec<i64> = self.residue();
        let mbar: Vec<i64> =
            self.modulus.iter().map(|c| (c.clone() % Integer::from(self.prime)).to_i64()).collect();
        let (_g, s, _t) = fp_factor::extended_gcd(&a, &mbar, self.prime);
        // s·a ≡ gcd = 1 (mod m̄); reduce s mod m̄ and lift coefficients to ℤ.
        let sred = fp_factor::div_mod(&s, &mbar, self.prime).1;
        let coeffs: Vec<Integer> = sred.iter().map(|&c| Integer::from(c)).collect();
        Self::new(self.prime, self.precision, self.modulus.clone(), coeffs)
    }

    /// Multiplicative inverse in `ℤ_q` to full precision (self must be a unit, i.e.
    /// nonzero residue), by p-adic Newton iteration `v ← v(2 − uv)`.
    pub fn inverse(&self) -> Self {
        let mut v = self.residue_inverse();
        let two = self.constant(Integer::from(2));
        // precision doubles each step from 1; ceil(log2(precision)) + 1 steps suffice.
        let steps = 32 - (self.precision.max(1)).leading_zeros() + 1;
        for _ in 0..steps {
            let uv = self.mul(&v);
            v = v.mul(&two.sub(&uv));
        }
        v
    }

    /// The image of the generator `ω` under Frobenius: the unique root of the modulus
    /// `m` in `ℤ_q` congruent to `ω^p` mod `p`, obtained by Hensel-lifting `ω^p`.
    pub fn frobenius_generator(prime: i64, precision: u32, modulus: Vec<Integer>) -> Self {
        let f = modulus.len() - 1;
        // m'(x) (little-endian).
        let deriv: Vec<Integer> =
            (1..=f).map(|i| modulus[i].clone() * Integer::from(i as i64)).collect();
        let omega = Self::generator(prime, precision, modulus.clone());
        let mut b = omega.pow(prime as u64); // ω^p ≡ a root of m (mod p)
        let steps = 32 - (precision.max(1)).leading_zeros() + 1;
        for _ in 0..steps {
            let mb = b.eval_int_poly(&modulus); // m(b)
            let mpb = b.eval_int_poly(&deriv); // m'(b), a unit
            b = b.sub(&mb.mul(&mpb.inverse()));
        }
        b
    }

    /// The **Frobenius automorphism** `φ` of `ℚ_q/ℚ_p` applied to this element — the
    /// canonical generator of the cyclic Galois group `Gal(ℚ_q/ℚ_p) ≅ C_f`. `φ` fixes
    /// `ℚ_p`, sends `ω ↦ φ(ω)` (the Hensel-lifted root of `m`), and reduces to the
    /// residue-field Frobenius `x ↦ x^p` mod `p`. Unlike a literal `p`-th power this
    /// is a genuine field automorphism (`φ^f = id`, `φ|_{ℚ_p} = id`).
    pub fn frobenius(&self) -> Self {
        let beta = Self::frobenius_generator(self.prime, self.precision, self.modulus.clone());
        // φ(Σ cᵢ ωⁱ) = Σ cᵢ β^i  (φ fixes the ℤ_p coefficients cᵢ). Horner in β.
        let f = self.f_deg();
        let mut result = Self::zero(self.prime, self.precision, self.modulus.clone());
        for i in (0..f).rev() {
            result = result.mul(&beta).add(&self.constant(self.coeffs[i].clone()));
        }
        result
    }

    /// `p`-adic valuation `v_q(self) = v_p(self)` in the unramified `ℚ_q` (unramified,
    /// so `v_q = v_p`): the least `v_p` of the coordinates, or `None` for `0`.
    pub fn pval(&self) -> Option<u32> {
        let pi = Integer::from(self.prime);
        self.coeffs
            .iter()
            .filter(|c| !c.is_zero())
            .map(|c| c.abs().valuation(&pi))
            .min()
    }

    /// Reduction to the residue field `F_{p^f}`: the coefficient vector mod `p`
    /// (little-endian, length `f`).
    pub fn residue(&self) -> Vec<i64> {
        let p = self.prime;
        self.coeffs
            .iter()
            .map(|c| {
                let r = (c.clone() % Integer::from(p)).to_i64();
                ((r % p) + p) % p
            })
            .collect()
    }
}

/// Build a monic integer lift of an irreducible polynomial of degree `f` over `F_p`
/// to use as the unramified modulus `m`. Searches small polynomials for an
/// irreducible (sufficient for the small `f` arising as residue degrees). Returns
/// the little-endian lift (`m[f] = 1`), or `None` if none is found in the search
/// window.
pub fn unramified_modulus(p: i64, f: usize) -> Option<Vec<Integer>> {
    if f == 0 {
        return None;
    }
    if f == 1 {
        return Some(vec![Integer::zero(), Integer::one()]); // x
    }
    // Try x^f + (low-degree tail) over F_p, smallest tails first.
    let pu = p as usize;
    let total = pu.checked_pow(f as u32)?; // p^f candidate tails (coeffs of x^0..x^{f-1})
    for code in 1..total {
        let mut tail = vec![0i64; f];
        let mut c = code;
        for slot in tail.iter_mut() {
            *slot = (c % pu) as i64;
            c /= pu;
        }
        // candidate = x^f + Σ tail_i x^i  (mod p)
        let mut cand: Vec<i64> = tail.clone();
        cand.push(1);
        if is_irreducible_fp(&cand, p) {
            let lift: Vec<Integer> = cand.iter().map(|&c| Integer::from(c)).collect();
            return Some(lift);
        }
    }
    None
}

// --------------------------------------------------------------------------- //
// Ramified (Eisenstein) extensions  K = ℚ_p[π]/(g),  g Eisenstein
// --------------------------------------------------------------------------- //

/// Is `g` (little-endian, monic of degree `e`) **Eisenstein** at `p`:
/// `p ∣ gᵢ` for `0 ≤ i < e` and `p² ∤ g₀`? Such a `g` is irreducible over `ℚ_p` and
/// `K = ℚ_p[π]/(g)` is totally ramified of degree `e` with uniformizer `π`.
pub fn is_eisenstein(g: &[Integer], p: i64) -> bool {
    let e = g.len() - 1;
    if e < 1 || g[e] != Integer::one() {
        return false;
    }
    let pi = Integer::from(p);
    for c in g.iter().take(e) {
        if !(c.clone() % pi.clone()).is_zero() {
            return false;
        }
    }
    let p2 = pi.clone() * pi;
    (g[0].clone() % p2).is_zero() == false && !g[0].is_zero()
}

/// Different exponent `d = v_𝔭(𝔡_{K/ℚ_p}) = v_π(g'(π))` of the totally ramified
/// `K = ℚ_p[π]/(g)` (`g` Eisenstein, `v_π(π)=1`, `v_π(p)=e`). Since `g'(π)` has degree
/// `e−1` (already reduced), `g'(π) = Σᵢ i·gᵢ π^{i−1}` and the terms have distinct
/// `v_π` (distinct residues mod `e`), so
/// `d = min_{i: i·gᵢ≠0} ( e·v_p(i·gᵢ) + (i−1) )`. The discriminant exponent is `d`
/// (residue degree `1`). Tame (`p∤e`) ⇒ `d = e−1`; wild ⇒ larger.
pub fn eisenstein_different_exponent(g: &[Integer], p: i64) -> i64 {
    let e = g.len() - 1;
    let pi = Integer::from(p);
    let mut d: Option<i64> = None;
    for i in 1..=e {
        let coeff = g[i].clone() * Integer::from(i as i64); // i·gᵢ
        if coeff.is_zero() {
            continue;
        }
        let v = e as i64 * coeff.abs().valuation(&pi) as i64 + (i as i64 - 1);
        d = Some(d.map_or(v, |cur| cur.min(v)));
    }
    d.unwrap_or(0)
}

/// An element of a totally ramified extension `K = ℤ_p[π]/(g)`, `g` Eisenstein of
/// degree `e`, truncated to precision `p^N`. `coeffs` (length `e`) are the
/// `c₀ + c₁π + … + c_{e−1}π^{e−1}` coordinates with `cⱼ ∈ ℤ/p^N`. The valuation is
/// `π`-adic: `v_π(π)=1`, `v_π(p)=e`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EisensteinElement {
    pub prime: i64,
    pub precision: u32,
    /// Monic Eisenstein modulus (little-endian).
    pub g: Vec<Integer>,
    pub coeffs: Vec<Integer>,
}

impl EisensteinElement {
    fn e_deg(&self) -> usize {
        self.g.len() - 1
    }

    fn norm(prime: i64, precision: u32, mut coeffs: Vec<Integer>, e: usize) -> Vec<Integer> {
        let m = Integer::from(prime).pow(precision);
        coeffs.resize(e, Integer::zero());
        for c in coeffs.iter_mut() {
            let r = c.clone() % m.clone();
            *c = if r.signum() < 0 { r + m.clone() } else { r };
        }
        coeffs
    }

    pub fn new(prime: i64, precision: u32, g: Vec<Integer>, coeffs: Vec<Integer>) -> Self {
        let e = g.len() - 1;
        let coeffs = Self::norm(prime, precision, coeffs, e);
        EisensteinElement { prime, precision, g, coeffs }
    }

    pub fn zero(prime: i64, precision: u32, g: Vec<Integer>) -> Self {
        let e = g.len() - 1;
        EisensteinElement { prime, precision, g, coeffs: vec![Integer::zero(); e] }
    }

    pub fn one(prime: i64, precision: u32, g: Vec<Integer>) -> Self {
        Self::new(prime, precision, g, vec![Integer::one()])
    }

    /// The uniformizer `π` (a root of `g`).
    pub fn uniformizer(prime: i64, precision: u32, g: Vec<Integer>) -> Self {
        Self::new(prime, precision, g, vec![Integer::zero(), Integer::one()])
    }

    pub fn from_int(prime: i64, precision: u32, g: Vec<Integer>, n: Integer) -> Self {
        Self::new(prime, precision, g, vec![n])
    }

    pub fn is_zero(&self) -> bool {
        self.coeffs.iter().all(|c| c.is_zero())
    }

    pub fn add(&self, other: &Self) -> Self {
        let e = self.e_deg();
        let c = (0..e).map(|i| self.coeffs[i].clone() + other.coeffs[i].clone()).collect();
        Self::new(self.prime, self.precision, self.g.clone(), c)
    }

    pub fn sub(&self, other: &Self) -> Self {
        let e = self.e_deg();
        let c = (0..e).map(|i| self.coeffs[i].clone() - other.coeffs[i].clone()).collect();
        Self::new(self.prime, self.precision, self.g.clone(), c)
    }

    pub fn neg(&self) -> Self {
        let c = self.coeffs.iter().map(|c| -c.clone()).collect();
        Self::new(self.prime, self.precision, self.g.clone(), c)
    }

    pub fn mul(&self, other: &Self) -> Self {
        let e = self.e_deg();
        let mut raw = vec![Integer::zero(); 2 * e - 1];
        for i in 0..e {
            if self.coeffs[i].is_zero() {
                continue;
            }
            for j in 0..e {
                raw[i + j] = raw[i + j].clone() + self.coeffs[i].clone() * other.coeffs[j].clone();
            }
        }
        // Reduce by the monic g: π^e = −Σ_{i<e} gᵢ π^i.
        for k in (e..=2 * e - 2).rev() {
            let leading = raw[k].clone();
            if leading.is_zero() {
                continue;
            }
            for i in 0..e {
                let idx = (k - e) + i;
                raw[idx] = raw[idx].clone() - leading.clone() * self.g[i].clone();
            }
            raw[k] = Integer::zero();
        }
        raw.truncate(e);
        Self::new(self.prime, self.precision, self.g.clone(), raw)
    }

    pub fn pow(&self, mut n: u64) -> Self {
        let mut result = Self::one(self.prime, self.precision, self.g.clone());
        let mut base = self.clone();
        while n > 0 {
            if n & 1 == 1 {
                result = result.mul(&base);
            }
            n >>= 1;
            if n > 0 {
                base = base.mul(&base);
            }
        }
        result
    }

    /// Residue digit in `F_p = O_K/π`: the constant coordinate mod `p`.
    pub fn residue_digit(&self) -> i64 {
        let p = self.prime;
        let r = (self.coeffs[0].clone() % Integer::from(p)).to_i64();
        ((r % p) + p) % p
    }

    /// Multiply every coordinate by the integer `k` (mod `p^precision`).
    pub fn scale_int(&self, k: &Integer) -> Self {
        let c = self.coeffs.iter().map(|c| c.clone() * k.clone()).collect();
        Self::new(self.prime, self.precision, self.g.clone(), c)
    }

    /// Divide every coordinate by `p` exactly (caller guarantees `p | every coeff`,
    /// i.e. `v_K(self) ≥ e`).
    fn div_by_p(&self) -> Self {
        let pi = Integer::from(self.prime);
        let c = self.coeffs.iter().map(|c| c.clone() / pi.clone()).collect();
        Self::new(self.prime, self.precision, self.g.clone(), c)
    }

    /// Divide by the uniformizer `π` (caller guarantees `v_K(self) ≥ 1`). Uses
    /// `π⁻¹ = −w/g₀` with `w = Σ_{j=1}^{e} g_j π^{j−1}` and `g₀ = p·u₀`, so
    /// `self/π = −((self·w)/p)·u₀⁻¹`.
    pub fn div_by_uniformizer(&self) -> Self {
        let e = self.e_deg();
        let p = self.prime;
        let modulus = Integer::from(p).pow(self.precision);
        // w = [g_1, g_2, …, g_e] (little-endian coords of Σ g_j π^{j−1}).
        let w_coords: Vec<Integer> = (1..=e).map(|j| self.g[j].clone()).collect();
        let w = Self::new(p, self.precision, self.g.clone(), w_coords);
        let xw_over_p = self.mul(&w).div_by_p(); // (self·w)/p, valid since v_K ≥ e
        let mut u0 = (self.g[0].clone() / Integer::from(p)) % modulus.clone(); // g_0/p mod p^N
        if u0.signum() < 0 {
            u0 = u0 + modulus.clone();
        }
        let u0inv = u0.mod_inverse(&modulus).expect("g_0/p is a unit");
        xw_over_p.scale_int(&u0inv).neg()
    }

    /// `π`-adic valuation (`v_π(π)=1`, `v_π(p)=e`): `min_j (e·v_p(cⱼ) + j)`; `None`
    /// for `0`. Coefficients with `v_p ≥ precision` are treated as exact zeros.
    pub fn valuation(&self) -> Option<i64> {
        let e = self.e_deg() as i64;
        let pi = Integer::from(self.prime);
        let mut v: Option<i64> = None;
        for (j, c) in self.coeffs.iter().enumerate() {
            if c.is_zero() {
                continue;
            }
            let vj = e * c.abs().valuation(&pi) as i64 + j as i64;
            v = Some(v.map_or(vj, |cur| cur.min(vj)));
        }
        v
    }
}

// --------------------------------------------------------------------------- //
// Mixed-ramification tower  K = ℚ_q[π]/(h),  h Eisenstein over the unramified ℚ_q
// --------------------------------------------------------------------------- //

/// An element of a general local field `K = ℚ_q[π]/(h)` of degree `e·f` over `ℚ_p`,
/// where `ℚ_q` is the unramified extension of degree `f` and `h` is Eisenstein of
/// degree `e` over `ℚ_q` (the **mixed-ramification tower**). Coefficients of
/// `c₀ + c₁π + … + c_{e−1}π^{e−1}` are [`UnramifiedElement`]s of `ℚ_q`. Valuation is
/// `π`-adic: `v_π(π)=1`, `v_π(p)=e`, residue field `F_{p^f}`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TowerElement {
    pub prime: i64,
    pub precision: u32,
    /// Unramified modulus defining `ℚ_q` (lift of an irreducible over `F_p`).
    pub unram_modulus: Vec<Integer>,
    /// Eisenstein modulus `h` over `ℚ_q` (monic, little-endian, `UnramifiedElement` coeffs).
    pub h: Vec<UnramifiedElement>,
    /// Coordinates over the `ℚ_q`-basis `1, π, …, π^{e−1}`.
    pub coeffs: Vec<UnramifiedElement>,
}

impl TowerElement {
    fn e_deg(&self) -> usize {
        self.h.len() - 1
    }
    fn q_zero(&self) -> UnramifiedElement {
        UnramifiedElement::zero(self.prime, self.precision, self.unram_modulus.clone())
    }

    /// Build from `ℚ_q`-coordinates (length padded/truncated to `e`).
    pub fn new(
        prime: i64,
        precision: u32,
        unram_modulus: Vec<Integer>,
        h: Vec<UnramifiedElement>,
        mut coeffs: Vec<UnramifiedElement>,
    ) -> Self {
        let e = h.len() - 1;
        let z = UnramifiedElement::zero(prime, precision, unram_modulus.clone());
        coeffs.resize(e, z);
        TowerElement { prime, precision, unram_modulus, h, coeffs }
    }

    pub fn zero(prime: i64, precision: u32, um: Vec<Integer>, h: Vec<UnramifiedElement>) -> Self {
        let e = h.len() - 1;
        let z = UnramifiedElement::zero(prime, precision, um.clone());
        TowerElement { prime, precision, unram_modulus: um, h, coeffs: vec![z; e] }
    }

    pub fn one(prime: i64, precision: u32, um: Vec<Integer>, h: Vec<UnramifiedElement>) -> Self {
        let mut t = Self::zero(prime, precision, um.clone(), h);
        t.coeffs[0] = UnramifiedElement::one(prime, precision, um);
        t
    }

    /// The ramified uniformizer `π` (a root of `h`).
    pub fn uniformizer(prime: i64, precision: u32, um: Vec<Integer>, h: Vec<UnramifiedElement>) -> Self {
        let mut t = Self::zero(prime, precision, um.clone(), h);
        t.coeffs[1] = UnramifiedElement::one(prime, precision, um);
        t
    }

    /// Embed an element of `ℚ_q` as a constant.
    pub fn from_unram(prime: i64, precision: u32, um: Vec<Integer>, h: Vec<UnramifiedElement>, c: UnramifiedElement) -> Self {
        let mut t = Self::zero(prime, precision, um, h);
        t.coeffs[0] = c;
        t
    }

    pub fn is_zero(&self) -> bool {
        self.coeffs.iter().all(|c| c.is_zero())
    }

    pub fn add(&self, other: &Self) -> Self {
        let c = self.coeffs.iter().zip(&other.coeffs).map(|(a, b)| a.add(b)).collect();
        Self::new(self.prime, self.precision, self.unram_modulus.clone(), self.h.clone(), c)
    }

    pub fn sub(&self, other: &Self) -> Self {
        let c = self.coeffs.iter().zip(&other.coeffs).map(|(a, b)| a.sub(b)).collect();
        Self::new(self.prime, self.precision, self.unram_modulus.clone(), self.h.clone(), c)
    }

    pub fn mul(&self, other: &Self) -> Self {
        let e = self.e_deg();
        let mut raw = vec![self.q_zero(); 2 * e - 1];
        for i in 0..e {
            if self.coeffs[i].is_zero() {
                continue;
            }
            for j in 0..e {
                raw[i + j] = raw[i + j].add(&self.coeffs[i].mul(&other.coeffs[j]));
            }
        }
        // Reduce by monic h: π^e = −Σ_{i<e} h_i π^i.
        for k in (e..=2 * e - 2).rev() {
            let lead = raw[k].clone();
            if lead.is_zero() {
                continue;
            }
            for i in 0..e {
                let idx = (k - e) + i;
                raw[idx] = raw[idx].sub(&lead.mul(&self.h[i]));
            }
            raw[k] = self.q_zero();
        }
        raw.truncate(e);
        Self::new(self.prime, self.precision, self.unram_modulus.clone(), self.h.clone(), raw)
    }

    pub fn pow(&self, mut n: u64) -> Self {
        let mut result = Self::one(self.prime, self.precision, self.unram_modulus.clone(), self.h.clone());
        let mut base = self.clone();
        while n > 0 {
            if n & 1 == 1 {
                result = result.mul(&base);
            }
            n >>= 1;
            if n > 0 {
                base = base.mul(&base);
            }
        }
        result
    }

    /// `π`-adic valuation (`v_π(π)=1`, `v_π(p)=e`): `min_j (e·v_q(c_j) + j)`; `None`
    /// for `0`.
    pub fn valuation(&self) -> Option<i64> {
        let e = self.e_deg() as i64;
        self.coeffs
            .iter()
            .enumerate()
            .filter_map(|(j, c)| c.pval().map(|v| e * v as i64 + j as i64))
            .min()
    }
}

// --------------------------------------------------------------------------- //
// Local Galois group descriptor
// --------------------------------------------------------------------------- //

/// Structure of the local Galois group `Gal(K_𝔭/ℚ_p)` in the rigorously
/// determinable cases.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LocalGroup {
    /// Cyclic of the given order.
    Cyclic(usize),
    /// Metacyclic `C_e ⋊ C_f` of order `e·f` (a Galois tame, non-cyclic case).
    Metacyclic { e: usize, f: usize },
    /// Galois, but the precise structure is not determined here.
    GaloisUndetermined,
    /// Not Galois over `ℚ_p`.
    NotGalois,
    /// Galois-ness undetermined (e.g. wild of degree > 2).
    Undetermined,
}

/// Ramification + Galois data of a local field `K_𝔭/ℚ_p` of residue degree `f` and
/// ramification `e`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LocalGaloisGroup {
    pub e: usize,
    pub f: usize,
    pub ramification: Ramification,
    /// Tame part of `e` (`e / p^{v_p(e)}`).
    pub tame_degree: usize,
    /// Wild part of `e` (`p^{v_p(e)}`, the order of the wild inertia for a Galois ext).
    pub wild_degree: usize,
    pub different_exp: Option<i64>,
    pub group: LocalGroup,
}

/// Classify the local field of ramification `e`, residue degree `f` over `ℚ_p`.
/// `different_exp` is carried through if known.
pub fn local_galois_group(
    p: i64,
    e: usize,
    f: usize,
    different_exp: Option<i64>,
) -> LocalGaloisGroup {
    let pu = p as usize;
    // wild part = p^{v_p(e)}.
    let mut wild = 1usize;
    let mut ee = e;
    while ee % pu == 0 {
        wild *= pu;
        ee /= pu;
    }
    let tame = e / wild;
    let ramification = if e == 1 {
        Ramification::Unramified
    } else if e % pu != 0 {
        Ramification::Tame
    } else {
        Ramification::Wild
    };

    // p^f − 1, for the tame Galois criterion (e | p^f − 1).
    let pf_minus_1 = Integer::from(p).pow(f as u32) - Integer::one();
    let divides = |n: usize| (pf_minus_1.clone() % Integer::from(n as i64)).is_zero();

    let group = if e == 1 {
        LocalGroup::Cyclic(f) // unramified: Frobenius, C_f
    } else if e * f == 2 {
        LocalGroup::Cyclic(2) // any degree-2 extension is Galois
    } else if e % pu != 0 {
        // tame: Galois over ℚ_p iff e | p^f − 1.
        if divides(e) {
            if f == 1 {
                LocalGroup::Cyclic(e)
            } else if e == 1 {
                LocalGroup::Cyclic(f)
            } else {
                LocalGroup::Metacyclic { e, f }
            }
        } else {
            LocalGroup::NotGalois
        }
    } else {
        LocalGroup::Undetermined // wild, degree > 2
    };

    LocalGaloisGroup {
        e,
        f,
        ramification,
        tame_degree: tame,
        wild_degree: wild,
        different_exp,
        group,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn iz(v: &[i64]) -> Vec<Integer> {
        v.iter().map(|&x| Integer::from(x)).collect()
    }

    /// Σ fᵢ dᵢ = v_p(disc_K) whenever every dᵢ is determined.
    fn check_local_global(f: &[i64], p: i64) -> Vec<LocalFactor> {
        let fz = iz(f);
        let dec = local_decomposition(&fz, p).expect("resolved");
        if dec.iter().all(|lf| lf.different_exp.is_some()) {
            let s: i64 = dec.iter().map(|lf| lf.disc_exp().unwrap()).sum();
            assert_eq!(s, local_discriminant_exponent(&fz, p), "Σ f_i d_i = v_p(disc)");
        }
        assert_eq!(dec.iter().map(|lf| lf.local_degree()).sum::<usize>(), fz.len() - 1);
        dec
    }

    #[test]
    fn wild_quadratic_x2_plus_1_at_2() {
        let d = check_local_global(&[1, 0, 1], 2);
        assert_eq!(d.len(), 1);
        assert_eq!((d[0].e, d[0].f), (2, 1));
        assert_eq!(d[0].ramification, Ramification::Wild);
        assert_eq!(d[0].different_exp, Some(2));
        assert_eq!(d[0].residue_field.size(), Integer::from(2));
    }

    #[test]
    fn tame_quadratic_x2_minus_5_at_5() {
        let d = check_local_global(&[-5, 0, 1], 5);
        assert_eq!(d[0].ramification, Ramification::Tame);
        assert_eq!(d[0].different_exp, Some(1));
    }

    #[test]
    fn wild_cubic_x3_minus_2_at_3() {
        let d = check_local_global(&[-2, 0, 0, 1], 3);
        assert_eq!((d[0].e, d[0].f), (3, 1));
        assert_eq!(d[0].ramification, Ramification::Wild);
        assert_eq!(d[0].different_exp, Some(3));
    }

    #[test]
    fn wild_quartic_x4_minus_2_at_2() {
        let d = check_local_global(&[-2, 0, 0, 0, 1], 2);
        assert_eq!((d[0].e, d[0].f), (4, 1));
        assert_eq!(d[0].ramification, Ramification::Wild);
        assert_eq!(d[0].different_exp, Some(11));
    }

    #[test]
    fn unramified_split_x3_minus_2_at_5() {
        let d = check_local_global(&[-2, 0, 0, 1], 5);
        let mut ef: Vec<(usize, usize)> = d.iter().map(|lf| (lf.e, lf.f)).collect();
        ef.sort_unstable();
        assert_eq!(ef, vec![(1, 1), (1, 2)]);
        assert!(d.iter().all(|lf| lf.ramification == Ramification::Unramified));
        assert!(d.iter().all(|lf| lf.different_exp == Some(0)));
    }

    #[test]
    fn index_divisor_dedekind_cubic_at_2() {
        let d = check_local_global(&[-8, -2, -1, 1], 2);
        assert_eq!(d.len(), 3);
        assert!(d
            .iter()
            .all(|lf| lf.ramification == Ramification::Unramified && lf.different_exp == Some(0)));
    }

    // ---- unramified extension arithmetic ----

    #[test]
    fn unramified_modulus_is_irreducible() {
        // F_4 = F_2[x]/(x²+x+1).
        let m = unramified_modulus(2, 2).unwrap();
        assert_eq!(m, iz(&[1, 1, 1]));
        // F_9 = F_3[x]/(x²+1) (smallest irreducible tail).
        let m3 = unramified_modulus(3, 2).unwrap();
        assert!(is_irreducible_fp(&m3.iter().map(|c| c.to_i64()).collect::<Vec<_>>(), 3));
    }

    #[test]
    fn zq_ring_axioms_and_field_order() {
        // ℤ_q over F_4 at precision 2^5.
        let p = 2i64;
        let prec = 5u32;
        let m = unramified_modulus(p, 2).unwrap(); // x²+x+1
        let w = UnramifiedElement::generator(p, prec, m.clone());
        let one = UnramifiedElement::one(p, prec, m.clone());
        // ω² + ω + 1 = 0 in F_4 ⇒ residue of ω²+ω+1 is zero.
        let w2 = w.mul(&w);
        let sum = w2.add(&w).add(&one);
        assert_eq!(sum.residue(), vec![0, 0]);
        // distributivity: ω·(ω+1) = ω²+ω.
        let lhs = w.mul(&w.add(&one));
        let rhs = w2.add(&w);
        assert_eq!(lhs, rhs);
        // ω is a generator of F_4*: ω³ ≡ 1 (residue), ω ≠ 1.
        assert_eq!(w.pow(3).residue(), one.residue());
        assert_ne!(w.residue(), one.residue());
    }

    #[test]
    fn frobenius_is_a_genuine_automorphism_f2() {
        // F_4 = F_2[ω]/(ω²+ω+1), precision 2^6.
        let p = 2i64;
        let prec = 6u32;
        let m = unramified_modulus(p, 2).unwrap();
        let w = UnramifiedElement::generator(p, prec, m.clone());

        // φ(ω) = β is a genuine root of m in ℤ_q (m(β) = 0 to full precision).
        let beta = UnramifiedElement::frobenius_generator(p, prec, m.clone());
        assert!(beta.eval_int_poly(&m).is_zero(), "m(β) = 0 in ℤ_q");
        // β ≡ ω² ≡ ω+1 (mod 2), the residue Frobenius.
        assert_eq!(beta.residue(), vec![1, 1]);

        // φ fixes ℚ_p EXACTLY (not just mod p): φ(3) = 3.
        let c = UnramifiedElement::from_int(p, prec, m.clone(), Integer::from(3));
        assert_eq!(c.frobenius(), c);

        // φ is a ring hom: φ(ω)·φ(ω) and φ(ω·ω) agree.
        let fw = w.frobenius();
        assert_eq!(fw.mul(&fw), w.mul(&w).frobenius());

        // φ² = identity to FULL precision (order exactly f = 2).
        assert_eq!(fw.frobenius(), w);
        assert_ne!(fw, w);

        let rf = ResidueField { characteristic: p, degree: 2 };
        assert_eq!(rf.frobenius_order(), 2);
    }

    #[test]
    fn frobenius_order_exactly_f3() {
        // f = 3: φ has order exactly 3 as an automorphism (φ³ = id to full precision).
        let p = 2i64;
        let prec = 5u32;
        let m = unramified_modulus(p, 3).unwrap();
        let w = UnramifiedElement::generator(p, prec, m.clone());
        let f1 = w.frobenius();
        assert_eq!(f1.frobenius().frobenius(), w); // φ³ = id (full precision)
        assert_ne!(f1, w); // φ ≠ id
        assert_ne!(f1.frobenius(), w); // φ² ≠ id
        // An inverse times itself is one (sanity for ℤ_q inversion used by Frobenius).
        let u = w.add(&UnramifiedElement::one(p, prec, m.clone()));
        assert_eq!(u.mul(&u.inverse()), UnramifiedElement::one(p, prec, m));
    }

    // ---- ramified (Eisenstein) extensions ----

    #[test]
    fn eisenstein_recognition() {
        assert!(is_eisenstein(&iz(&[-2, 0, 1]), 2)); // x²−2
        assert!(is_eisenstein(&iz(&[2, -2, 1]), 2)); // x²−2x+2
        assert!(!is_eisenstein(&iz(&[1, 0, 1]), 2)); // x²+1, 2∤1
        assert!(!is_eisenstein(&iz(&[-4, 0, 1]), 2)); // x²−4, 2²∣4
        assert!(!is_eisenstein(&iz(&[-5, 0, 1]), 2)); // x²−5, 2∤5
        assert!(is_eisenstein(&iz(&[-5, 0, 1]), 5)); // x²−5 at 5
    }

    #[test]
    fn eisenstein_different_matches_pari_gp() {
        // Cross-checked against PARI/GP idealval(K.diff, P).
        assert_eq!(eisenstein_different_exponent(&iz(&[2, -2, 1]), 2), 2); // Q_2(i)
        assert_eq!(eisenstein_different_exponent(&iz(&[-2, 0, 1]), 2), 3); // Q_2(√2)
        assert_eq!(eisenstein_different_exponent(&iz(&[-5, 0, 1]), 5), 1); // tame
        assert_eq!(eisenstein_different_exponent(&iz(&[-3, 0, 0, 1]), 3), 5); // Q_3(3^⅓)
        assert_eq!(eisenstein_different_exponent(&iz(&[-2, 0, 0, 1]), 2), 2); // x³−2, tame
        assert_eq!(eisenstein_different_exponent(&iz(&[-2, 0, 0, 0, 1]), 2), 11); // x⁴−2
        assert_eq!(eisenstein_different_exponent(&iz(&[-3, 0, 1]), 3), 1); // tame
    }

    #[test]
    fn eisenstein_element_arithmetic_and_valuation() {
        // K = ℚ_2[π]/(π²−2): v(π)=1/2, v(2)=1 ⇒ v_π(π)=1, v_π(2)=2.
        let p = 2i64;
        let prec = 8u32;
        let g = iz(&[-2, 0, 1]);
        let pi = EisensteinElement::uniformizer(p, prec, g.clone());
        // π² = 2 (the modulus relation).
        let two = EisensteinElement::from_int(p, prec, g.clone(), Integer::from(2));
        assert_eq!(pi.mul(&pi), two);
        // v_π(π)=1, v_π(2)=2, v_π(π³)=3.
        assert_eq!(pi.valuation(), Some(1));
        assert_eq!(two.valuation(), Some(2));
        assert_eq!(pi.pow(3).valuation(), Some(3));
        // The intrinsic different via the element g'(π) equals the closed form: g'(x)=2x.
        let gprime = pi.mul(&two).valuation(); // 2π → v_π = 3
        assert_eq!(gprime, Some(3));
        assert_eq!(gprime.unwrap(), eisenstein_different_exponent(&g, 2));
    }

    #[test]
    fn eisenstein_div_by_uniformizer() {
        // K = ℚ_2[π]/(π²−2): π·(x/π) = x for any x with v_K(x) ≥ 1.
        let p = 2i64;
        let prec = 10u32;
        let g = iz(&[-2, 0, 1]);
        let pi = EisensteinElement::uniformizer(p, prec, g.clone());
        // x = π² (=2): x/π = π.
        let x = pi.mul(&pi);
        assert_eq!(x.div_by_uniformizer(), pi);
        // x = π³ + π (v_K=1): (x/π) = π² + 1, and π·(x/π) = x.
        let x2 = pi.pow(3).add(&pi);
        assert_eq!(pi.mul(&x2.div_by_uniformizer()), x2);
        // x = 2·π = π³ (v_K=3): /π = π² = 2.
        let two = EisensteinElement::from_int(p, prec, g.clone(), Integer::from(2));
        assert_eq!(two.mul(&pi).div_by_uniformizer(), two);
    }

    #[test]
    fn mixed_tower_e2_f2_arithmetic() {
        // K = ℚ_2(ω, √2): ℚ_4 = ℚ_2[ω]/(ω²+ω+1) (f=2, unramified), then π²−2 over ℚ_4
        // (e=2, Eisenstein). [K:ℚ_2] = 4, e=2, f=2, residue field F_4.
        let p = 2i64;
        let prec = 8u32;
        let um = unramified_modulus(p, 2).unwrap(); // ω²+ω+1
        let uq = |n: i64| UnramifiedElement::from_int(p, prec, um.clone(), Integer::from(n));
        // h = π² − 2 over ℚ_4: coeffs [−2, 0, 1] (as ℚ_4 constants).
        let h = vec![uq(-2), uq(0), uq(1)];
        let mk = |c: Vec<UnramifiedElement>| TowerElement::new(p, prec, um.clone(), h.clone(), c);

        let pi = TowerElement::uniformizer(p, prec, um.clone(), h.clone());
        let one = TowerElement::one(p, prec, um.clone(), h.clone());
        let omega = TowerElement::from_unram(
            p, prec, um.clone(), h.clone(),
            UnramifiedElement::generator(p, prec, um.clone()),
        );

        // π² = 2 (the Eisenstein relation).
        assert_eq!(pi.mul(&pi), mk(vec![uq(2), uq(0)]));
        // ω² + ω + 1 = 0 in ℚ_4 ⇒ (ω²+ω+1) = 0 as a tower constant.
        assert!(omega.mul(&omega).add(&omega).add(&one).is_zero());
        // Distributivity: (1+ω)·π = π + ω·π.
        let lhs = one.add(&omega).mul(&pi);
        let rhs = pi.add(&omega.mul(&pi));
        assert_eq!(lhs, rhs);

        // Valuations: v_π(π)=1, v_π(2)=e=2, v_π(ω)=0 (ω is a unit), v_π(ω·π)=1.
        assert_eq!(pi.valuation(), Some(1));
        assert_eq!(mk(vec![uq(2), uq(0)]).valuation(), Some(2));
        assert_eq!(omega.valuation(), Some(0));
        assert_eq!(omega.mul(&pi).valuation(), Some(1));
        // v_π(2ω·π³): 2ω has v_q=1 ⇒ v_π=2, times π³ ⇒ 5.
        let two_omega_pi3 = omega.mul(&mk(vec![uq(2), uq(0)])).mul(&pi.pow(3));
        assert_eq!(two_omega_pi3.valuation(), Some(5));
    }

    #[test]
    fn local_galois_group_clean_cases() {
        // Unramified degree f ⇒ C_f (Frobenius).
        let u = local_galois_group(5, 1, 3, Some(0));
        assert_eq!(u.group, LocalGroup::Cyclic(3));
        assert_eq!(u.ramification, Ramification::Unramified);

        // Any degree-2 extension is Galois (C_2), even wild Q_2(i).
        let q2i = local_galois_group(2, 2, 1, Some(2));
        assert_eq!(q2i.group, LocalGroup::Cyclic(2));
        assert_eq!(q2i.ramification, Ramification::Wild);
        assert_eq!((q2i.tame_degree, q2i.wild_degree), (1, 2));

        // Tame totally ramified: Galois iff e | p−1.
        // Q_5(5^{1/4}): e=4 | 5−1=4 ⇒ Galois C_4.
        assert_eq!(local_galois_group(5, 4, 1, Some(3)).group, LocalGroup::Cyclic(4));
        // Q_7(7^{1/3}): e=3 | 7−1=6 ⇒ Galois C_3.
        assert_eq!(local_galois_group(7, 3, 1, Some(2)).group, LocalGroup::Cyclic(3));
        // Q_5(5^{1/3}): e=3 ∤ 4 ⇒ NOT Galois over ℚ_5.
        assert_eq!(local_galois_group(5, 3, 1, Some(2)).group, LocalGroup::NotGalois);

        // Tame, e=2,f=2: e=2 | p^f−1=3²−1=8 ⇒ Galois metacyclic C_2⋊C_2.
        assert_eq!(
            local_galois_group(3, 2, 2, Some(1)).group,
            LocalGroup::Metacyclic { e: 2, f: 2 }
        );

        // Wild degree > 2: Galois-ness undetermined here.
        let wild = local_galois_group(2, 4, 1, Some(11));
        assert_eq!(wild.group, LocalGroup::Undetermined);
        assert_eq!((wild.tame_degree, wild.wild_degree), (1, 4));
    }
}
