//! Local field decomposition of a number field at a rational prime (Module 9).
//!
//! For `K = ℚ[x]/(f)` and a rational prime `p`, the completion splits as
//! `K ⊗_ℚ ℚ_p = ∏_{𝔭∣p} K_𝔭`, one local field per prime above `p`. Each `K_𝔭/ℚ_p`
//! carries:
//! - ramification index `e` and residue degree `f` (`Σ eᵢ fᵢ = [K:ℚ]`), from the
//!   prime decomposition ([`crate::ideals::prime_decomposition`], valid even at
//!   index-dividing primes via the Montes fallback);
//! - its **residue field** `F_{p^f}` (the actual arithmetic lives in
//!   `rustmath_finitefields::ExtensionField`; here we carry the `(p, f)` descriptor);
//! - a **ramification class**: *unramified* (`e=1`), *tame* (`e>1`, `p∤e`), or
//!   *wild* (`p∣e`);
//! - the **different exponent** `d = v_𝔭(𝔡_{K_𝔭/ℚ_p})`, with local-disc exponent
//!   `f·d`. The local–global formula is `Σ_𝔭 fᵢ dᵢ = v_p(disc_K)`.
//!
//! Different exponents: `d = 0` (unramified), `d = e−1` (tame). The wild exponent
//! is **not** determined by `(e,f)` alone (`x²+1` at 2 has `e=2, d=2`; `x⁴−2` at 2
//! has `e=4, d=11`); when a single wild prime lies above `p` it is recovered exactly
//! from `v_p(disc_K)`. With several wild primes above one `p` the split is left
//! `None` (it needs the higher-order Montes / ramification-filtration data).

use crate::ideals::prime_decomposition;
use crate::round2::field_discriminant;
use rustmath_integers::Integer;

/// Ramification class of a local field `K_𝔭/ℚ_p`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Ramification {
    /// `e = 1`.
    Unramified,
    /// `e > 1` and `p ∤ e`.
    Tame,
    /// `p ∣ e`.
    Wild,
}

/// Residue field `F_{p^f}` descriptor (the residue field of `K_𝔭`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ResidueField {
    pub characteristic: i64,
    /// Residue degree `f`, so the field is `F_{p^f}`.
    pub degree: usize,
}

impl ResidueField {
    /// `|F_{p^f}| = p^f`.
    pub fn size(&self) -> Integer {
        Integer::from(self.characteristic).pow(self.degree as u32)
    }
    /// Order of the Frobenius `x ↦ x^p`, i.e. `f` — equivalently the order of the
    /// cyclic Galois group `Gal(F_{p^f}/F_p) ≅ C_f` of the residue extension. For an
    /// **unramified** local field this is also `Gal(K_𝔭/ℚ_p)` (generated by the
    /// Frobenius), which is the per-prime local piece of the global Frobenius.
    pub fn frobenius_order(&self) -> usize {
        self.degree
    }
}

/// One local field `K_𝔭` above `p`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LocalFactor {
    pub e: usize,
    pub f: usize,
    pub ramification: Ramification,
    pub residue_field: ResidueField,
    /// Different exponent `d = v_𝔭(𝔡_{K_𝔭/ℚ_p})`. `None` for an undetermined wild
    /// prime (≥ 2 wild primes above `p`).
    pub different_exp: Option<i64>,
}

impl LocalFactor {
    /// Local discriminant exponent `f·d` (so `Σ disc_exp = v_p(disc_K)`).
    pub fn disc_exp(&self) -> Option<i64> {
        self.different_exp.map(|d| self.f as i64 * d)
    }
    /// Degree `[K_𝔭 : ℚ_p] = e·f`.
    pub fn local_degree(&self) -> usize {
        self.e * self.f
    }
}

/// `v_p(disc_K)` — the exponent of `p` in the field discriminant.
pub fn local_discriminant_exponent(f: &[Integer], p: i64) -> i64 {
    let d = field_discriminant(f);
    if d.is_zero() {
        return 0;
    }
    d.abs().valuation(&Integer::from(p)) as i64
}

/// The local fields `K_𝔭` above `p`, i.e. the factors of `K ⊗ ℚ_p`. Returns `None`
/// if the prime decomposition is unresolved (non-regular polygon needing
/// higher-order Montes — see [`prime_decomposition`]).
pub fn local_decomposition(f: &[Integer], p: i64) -> Option<Vec<LocalFactor>> {
    let dec = prime_decomposition(f, p);
    if !dec.montes_resolved {
        return None;
    }
    let vdisc = local_discriminant_exponent(f, p);
    let pu = p as usize;

    let mut factors: Vec<LocalFactor> = Vec::new();
    let mut known_sum: i64 = 0; // Σ f_i d_i over unramified+tame factors
    let mut wild_idx: Vec<usize> = Vec::new();

    for (e, fdeg) in dec.ef() {
        let ram = if e == 1 {
            Ramification::Unramified
        } else if e % pu != 0 {
            Ramification::Tame
        } else {
            Ramification::Wild
        };
        let d = match ram {
            Ramification::Unramified => Some(0),
            Ramification::Tame => Some((e - 1) as i64),
            Ramification::Wild => None,
        };
        if let Some(dv) = d {
            known_sum += fdeg as i64 * dv;
        } else {
            wild_idx.push(factors.len());
        }
        factors.push(LocalFactor {
            e,
            f: fdeg,
            ramification: ram,
            residue_field: ResidueField { characteristic: p, degree: fdeg },
            different_exp: d,
        });
    }

    // Recover a unique wild prime's different exponent from the global disc valuation.
    if wild_idx.len() == 1 {
        let i = wild_idx[0];
        let fi = factors[i].f as i64;
        let wild_total = vdisc - known_sum;
        if fi > 0 && wild_total % fi == 0 {
            factors[i].different_exp = Some(wild_total / fi);
        }
    }

    Some(factors)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn iz(v: &[i64]) -> Vec<Integer> {
        v.iter().map(|&x| Integer::from(x)).collect()
    }

    /// Σ fᵢ dᵢ = v_p(disc_K) whenever every dᵢ is determined.
    fn check_local_global(f: &[i64], p: i64) -> Vec<LocalFactor> {
        let fz = iz(f);
        let dec = local_decomposition(&fz, p).expect("resolved");
        if dec.iter().all(|lf| lf.different_exp.is_some()) {
            let s: i64 = dec.iter().map(|lf| lf.disc_exp().unwrap()).sum();
            assert_eq!(s, local_discriminant_exponent(&fz, p), "Σ f_i d_i = v_p(disc)");
        }
        // Σ e_i f_i = deg
        assert_eq!(dec.iter().map(|lf| lf.local_degree()).sum::<usize>(), fz.len() - 1);
        dec
    }

    #[test]
    fn wild_quadratic_x2_plus_1_at_2() {
        // K_𝔭 = ℚ_2(i): e=2, f=1, wild, different exp d=2 (recovered from v_2(disc)=2).
        let d = check_local_global(&[1, 0, 1], 2);
        assert_eq!(d.len(), 1);
        assert_eq!((d[0].e, d[0].f), (2, 1));
        assert_eq!(d[0].ramification, Ramification::Wild);
        assert_eq!(d[0].different_exp, Some(2));
        assert_eq!(d[0].residue_field.size(), Integer::from(2));
    }

    #[test]
    fn tame_quadratic_x2_minus_5_at_5() {
        let d = check_local_global(&[-5, 0, 1], 5);
        assert_eq!(d[0].ramification, Ramification::Tame);
        assert_eq!(d[0].different_exp, Some(1)); // d = e − 1 = 1
    }

    #[test]
    fn wild_cubic_x3_minus_2_at_3() {
        let d = check_local_global(&[-2, 0, 0, 1], 3);
        assert_eq!((d[0].e, d[0].f), (3, 1));
        assert_eq!(d[0].ramification, Ramification::Wild);
        assert_eq!(d[0].different_exp, Some(3)); // wild, d=3 (tame would be 2)
    }

    #[test]
    fn wild_quartic_x4_minus_2_at_2() {
        let d = check_local_global(&[-2, 0, 0, 0, 1], 2);
        assert_eq!((d[0].e, d[0].f), (4, 1));
        assert_eq!(d[0].ramification, Ramification::Wild);
        assert_eq!(d[0].different_exp, Some(11)); // recovered from v_2(disc)=11
    }

    #[test]
    fn unramified_split_x3_minus_2_at_5() {
        // 5 unramified in ℚ(2^{1/3}): factors (1,1) and (1,2).
        let d = check_local_global(&[-2, 0, 0, 1], 5);
        let mut ef: Vec<(usize, usize)> = d.iter().map(|lf| (lf.e, lf.f)).collect();
        ef.sort_unstable();
        assert_eq!(ef, vec![(1, 1), (1, 2)]);
        assert!(d.iter().all(|lf| lf.ramification == Ramification::Unramified));
        assert!(d.iter().all(|lf| lf.different_exp == Some(0)));
        assert_eq!(local_discriminant_exponent(&iz(&[-2, 0, 0, 1]), 5), 0);
    }

    #[test]
    fn index_divisor_dedekind_cubic_at_2() {
        // 2 | index, totally split into three unramified (1,1) primes.
        let d = check_local_global(&[-8, -2, -1, 1], 2);
        assert_eq!(d.len(), 3);
        assert!(d.iter().all(|lf| lf.ramification == Ramification::Unramified
            && lf.different_exp == Some(0)));
    }
}
