//! S-units and the S-class group of a number field (Module 8).
//!
//! For a finite set `S` of prime ideals, the **S-unit group**
//! `O_{K,S}^* = {x ∈ K^* : v_𝔭(x) = 0 for all 𝔭 ∉ S}` is, by Dirichlet's S-unit
//! theorem, `μ_K × ℤ^{r₁+r₂−1+|S|}` — so its free rank is the ordinary unit rank plus
//! `|S|`. The **S-class group** is `Cl_S = Cl_K / ⟨[𝔭] : 𝔭 ∈ S⟩`, with S-class number
//! `h_S = h_K / |⟨[𝔭] : 𝔭 ∈ S⟩|`. The subgroup generated by `S` is enumerated by a
//! BFS over ideal classes, using `𝔞 ~ 𝔟 ⟺ 𝔞·𝔟^{h−1}` principal (an integral test,
//! since `𝔟^h` is principal).

use crate::classgroup::{class_group, is_principal};
use crate::ideals::{ideal_mul, one_ideal, Ideal};
use crate::round2::{maximal_order_data, OrderData};
use crate::units::unit_rank;
use rustmath_integers::Integer;

/// Free rank of the S-unit group `O_{K,S}^*`: `unit_rank + |S|` (Dirichlet S-unit
/// theorem). `num_s_primes` is the number of prime ideals in `S`.
pub fn s_unit_rank(f: &[Integer], num_s_primes: usize) -> usize {
    unit_rank(f) + num_s_primes
}

fn ideal_pow(ord: &OrderData, a: &Ideal, e: usize) -> Ideal {
    let mut result = one_ideal(ord);
    let mut base = a.clone();
    let mut e = e;
    while e > 0 {
        if e & 1 == 1 {
            result = ideal_mul(ord, &result, &base);
        }
        e >>= 1;
        if e > 0 {
            base = ideal_mul(ord, &base, &base);
        }
    }
    result
}

/// Two integral ideals are in the same ideal class iff `𝔞·𝔟^{h−1}` is principal.
fn class_equal(f: &[Integer], ord: &OrderData, a: &Ideal, b: &Ideal, h: usize) -> bool {
    if h <= 1 {
        return true;
    }
    let prod = ideal_mul(ord, a, &ideal_pow(ord, b, h - 1));
    is_principal(f, ord, &prod).is_some()
}

/// The order of the subgroup `⟨[𝔭] : 𝔭 ∈ s_primes⟩` of the ideal class group, by BFS
/// over the reachable classes (bounded by `h_K`). `None` if the class group is
/// unavailable.
pub fn class_subgroup_order(f: &[Integer], s_primes: &[Ideal]) -> Option<usize> {
    let cg = class_group(f)?;
    let h: usize = cg.iter().product::<usize>().max(1);
    if h == 1 {
        return Some(1);
    }
    let ord = maximal_order_data(f);
    let mut classes: Vec<Ideal> = vec![one_ideal(&ord)];
    let mut frontier = vec![0usize];
    while let Some(idx) = frontier.pop() {
        let cur = classes[idx].clone();
        for g in s_primes {
            let prod = ideal_mul(&ord, &cur, g);
            if !classes.iter().any(|c| class_equal(f, &ord, &prod, c, h)) {
                classes.push(prod);
                frontier.push(classes.len() - 1);
            }
        }
    }
    Some(classes.len())
}

/// The S-class number `h_S = h_K / |⟨[𝔭] : 𝔭 ∈ S⟩|`.
pub fn s_class_number(f: &[Integer], s_primes: &[Ideal]) -> Option<usize> {
    let cg = class_group(f)?;
    let h: usize = cg.iter().product::<usize>().max(1);
    let sub = class_subgroup_order(f, s_primes)?;
    Some(h / sub)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ideals::prime_ideals;

    fn iz(v: &[i64]) -> Vec<Integer> {
        v.iter().map(|&x| Integer::from(x)).collect()
    }

    fn prime_above(f: &[Integer], p: i64) -> Ideal {
        prime_ideals(f, p).1.into_iter().next().unwrap().0
    }

    #[test]
    fn s_unit_rank_dirichlet() {
        // Q(√−5): imaginary quadratic, unit rank 0. With |S| prime ideals, rank = |S|.
        assert_eq!(s_unit_rank(&iz(&[5, 0, 1]), 0), 0);
        assert_eq!(s_unit_rank(&iz(&[5, 0, 1]), 2), 2);
        // Q(√2): real quadratic, unit rank 1. |S|=1 ⇒ rank 2.
        assert_eq!(s_unit_rank(&iz(&[-2, 0, 1]), 1), 2);
    }

    #[test]
    fn s_class_number_quadratic() {
        // Q(√−5): Cl = ℤ/2 (h=2).
        let f = iz(&[5, 0, 1]);
        // 𝔭_2 (ramified, non-principal, order 2) generates Cl ⇒ h_S = 1.
        let p2 = prime_above(&f, 2);
        assert_eq!(class_subgroup_order(&f, &[p2.clone()]), Some(2));
        assert_eq!(s_class_number(&f, &[p2]), Some(1));
        // 𝔭_29 = (3+2√−5) is principal (29 = 3²+5·2²) ⇒ subgroup trivial, h_S = 2.
        let p29 = prime_above(&f, 29);
        assert_eq!(class_subgroup_order(&f, &[p29.clone()]), Some(1));
        assert_eq!(s_class_number(&f, &[p29]), Some(2));
    }

    #[test]
    fn s_class_number_h3() {
        // Q(√−23): Cl = ℤ/3 (h=3). A prime above 2 (2 splits, −23 ≡ 1 mod 8) has
        // order 3 in Cl ⇒ generates it ⇒ h_S = 1.
        let f = iz(&[6, -1, 1]); // x²−x+6, polredabs of Q(√−23)
        let p2 = prime_above(&f, 2);
        assert_eq!(class_subgroup_order(&f, &[p2.clone()]), Some(3));
        assert_eq!(s_class_number(&f, &[p2]), Some(1));
    }

    #[test]
    fn trivial_class_group_s_class_is_one() {
        // Q(i): h = 1 ⇒ subgroup trivial, h_S = 1 for any S.
        let f = iz(&[1, 0, 1]);
        let p5 = prime_above(&f, 5);
        assert_eq!(s_class_number(&f, &[p5]), Some(1));
    }
}
