//! Hecke operators and Hecke modules
//!
//! Hecke operators are important endomorphisms of spaces of modular forms
//! that encode arithmetic information.

use rustmath_core::Ring;
use rustmath_integers::Integer;
use rustmath_rationals::Rational;
use std::collections::HashMap;

/// Greatest common divisor for u64 arguments.
fn gcd_u64(a: u64, b: u64) -> u64 {
    if b == 0 { a } else { gcd_u64(b, a % b) }
}

/// A Hecke operator T_n
#[derive(Debug, Clone)]
pub struct HeckeOperator {
    /// Index n
    n: u64,
    /// Level of the modular forms space
    level: u64,
    /// Matrix representation (if computed)
    matrix: Option<Vec<Vec<Rational>>>,
}

impl HeckeOperator {
    /// Create a new Hecke operator T_n
    pub fn new(n: u64, level: u64) -> Self {
        HeckeOperator {
            n,
            level,
            matrix: None,
        }
    }

    /// Get the index
    pub fn index(&self) -> u64 {
        self.n
    }

    /// Get the level
    pub fn level(&self) -> u64 {
        self.level
    }

    /// Apply T_n to q-expansion coefficients
    /// (T_n f)(q) = sum_{m>=0} b_m q^m where
    /// b_m = sum_{d | gcd(n,m)} d * a(nm/d^2)
    pub fn apply_to_coefficients(
        &self,
        input_coeffs: &HashMap<u64, Rational>,
        max_output: u64,
    ) -> HashMap<u64, Rational> {
        let mut result = HashMap::new();

        for m in 0..=max_output {
            let mut b_m = Rational::zero();

            // Sum over divisors of gcd(n, m)
            let g = gcd_u64(self.n, m);
            for d in 1..=g {
                if g % d == 0 {
                    let nm_over_d2 = (self.n * m) / (d * d);
                    if let Some(a_val) = input_coeffs.get(&nm_over_d2) {
                        b_m = b_m + Rational::from_integer(Integer::from(d)) * a_val.clone();
                    }
                }
            }

            if !b_m.is_zero() {
                result.insert(m, b_m);
            }
        }

        result
    }

    /// Check if this is a good Hecke operator (gcd(n, level) = 1)
    pub fn is_good(&self) -> bool {
        gcd_u64(self.n, self.level) == 1
    }

    /// Check if this is a bad Hecke operator (gcd(n, level) > 1)
    pub fn is_bad(&self) -> bool {
        !self.is_good()
    }
}

/// The full Hecke algebra T generated by all T_n
#[derive(Debug, Clone)]
pub struct HeckeAlgebra {
    /// Level
    level: u64,
    /// Weight
    weight: i32,
    /// Dimension of the ambient space
    dimension: usize,
}

impl HeckeAlgebra {
    /// Create a new Hecke algebra
    pub fn new(level: u64, weight: i32, dimension: usize) -> Self {
        HeckeAlgebra {
            level,
            weight,
            dimension,
        }
    }

    /// Get the level
    pub fn level(&self) -> u64 {
        self.level
    }

    /// Get the weight
    pub fn weight(&self) -> i32 {
        self.weight
    }

    /// Get the dimension
    pub fn dimension(&self) -> usize {
        self.dimension
    }

    /// Get Hecke operator T_n
    pub fn hecke_operator(&self, n: u64) -> HeckeOperator {
        HeckeOperator::new(n, self.level)
    }

    /// Compute Hecke eigenvalues for a newform.
    /// Returns a map from n to the eigenvalue of T_n, for n = 1..=max_n.
    ///
    /// Implemented case: weight 2, trivial character on Gamma0(level), when
    /// every T_n acts as a scalar on the cuspidal subspace of the modular
    /// symbols space (equivalently, there is a single system of rational
    /// Hecke eigenvalues, e.g. any genus-one level).  The eigenvalues are
    /// computed exactly over Q via Merel's Heilbronn-type matrices acting
    /// on Manin symbols (see [`crate::modsym::hecke`]); indices with
    /// gcd(n, level) > 1 use the U_p operators, so the full q-expansion of
    /// the newform is returned.
    ///
    /// Panics (honest `unimplemented!`) for other weights, for levels with
    /// no cusp forms, and when the cuspidal space carries more than one
    /// eigensystem (newform decomposition is not yet implemented).
    pub fn eigenvalues(&self, max_n: u64) -> HashMap<u64, Rational> {
        if self.weight != 2 {
            unimplemented!(
                "HeckeAlgebra::eigenvalues: only weight 2 with trivial character \
                 is implemented (via modular symbols); weight {} requires the \
                 polynomial part of Manin symbols",
                self.weight
            );
        }
        let m = crate::modsym::ModularSymbolsGamma0::new(self.level);
        let s = m.cuspidal_dimension();
        if s == 0 {
            unimplemented!(
                "HeckeAlgebra::eigenvalues: S_2(Gamma0({})) = 0; there is no \
                 newform whose eigenvalues could be returned",
                self.level
            );
        }
        let mut out = HashMap::new();
        for n in 1..=max_n {
            let t = m.hecke_matrix_cuspidal(n);
            let a = t.get(0, 0).expect("cuspidal dimension >= 1").clone();
            let scalar = (0..s).all(|i| {
                (0..s).all(|j| {
                    let e = t.get(i, j).expect("entry in range");
                    if i == j {
                        *e == a
                    } else {
                        e.is_zero()
                    }
                })
            });
            if !scalar {
                unimplemented!(
                    "HeckeAlgebra::eigenvalues: T_{} is not scalar on the \
                     cuspidal subspace at level {} (multiple Hecke \
                     eigensystems); newform decomposition is not yet \
                     implemented",
                    n,
                    self.level
                );
            }
            out.insert(n, a);
        }
        out
    }
}

/// A Hecke module (vector space with Hecke operator action)
pub trait HeckeModule {
    /// Get the dimension
    fn dimension(&self) -> usize;

    /// Apply Hecke operator T_n
    fn apply_hecke(&self, n: u64, element: &[Rational]) -> Vec<Rational>;

    /// Get the level
    fn level(&self) -> u64;

    /// Check if a vector is a Hecke eigenform
    fn is_eigenform(&self, element: &[Rational], max_n: u64) -> bool {
        // Check if T_n(f) = lambda_n * f for small n
        for n in 1..=max_n {
            let t_n_f = self.apply_hecke(n, element);

            // Check if t_n_f is a scalar multiple of element
            if element[0].is_zero() {
                continue;
            }

            let ratio = &t_n_f[0] / &element[0];
            for i in 0..self.dimension() {
                let expected = &element[i] * &ratio;
                if (t_n_f[i].clone() - expected).abs()
                    > Rational::new(Integer::one(), Integer::from(1000000))
                        .expect("nonzero denominator")
                {
                    return false;
                }
            }
        }
        true
    }
}

/// A newform (primitive eigenform for all Hecke operators)
#[derive(Debug, Clone)]
pub struct Newform {
    /// Weight
    weight: i32,
    /// Level
    level: u64,
    /// q-expansion coefficients
    coefficients: HashMap<u64, Rational>,
    /// Hecke eigenvalues
    eigenvalues: HashMap<u64, Rational>,
}

impl Newform {
    /// Create a new newform
    pub fn new(weight: i32, level: u64) -> Self {
        Newform {
            weight,
            level,
            coefficients: HashMap::new(),
            eigenvalues: HashMap::new(),
        }
    }

    /// Get weight
    pub fn weight(&self) -> i32 {
        self.weight
    }

    /// Get level
    pub fn level(&self) -> u64 {
        self.level
    }

    /// Get coefficient a(n)
    pub fn coefficient(&self, n: u64) -> Option<&Rational> {
        self.coefficients.get(&n)
    }

    /// Set coefficient
    pub fn set_coefficient(&mut self, n: u64, value: Rational) {
        self.coefficients.insert(n, value);
    }

    /// Get eigenvalue of T_n
    pub fn eigenvalue(&self, n: u64) -> Option<&Rational> {
        self.eigenvalues.get(&n)
    }

    /// Set eigenvalue of T_n
    pub fn set_eigenvalue(&mut self, n: u64, value: Rational) {
        self.eigenvalues.insert(n, value);
    }

    /// For a normalized newform (a(1) = 1), we have a(n) = eigenvalue(n)
    pub fn is_normalized(&self) -> bool {
        self.coefficients
            .get(&1)
            .map(|c| c == &Rational::one())
            .unwrap_or(false)
    }

    /// Normalize the newform so that a(1) = 1
    pub fn normalize(&mut self) {
        if let Some(a1) = self.coefficients.get(&1).cloned() {
            if !a1.is_zero() && a1 != Rational::one() {
                let inv_a1 = a1.reciprocal().expect("a1 nonzero (checked above)");
                for (_, coeff) in self.coefficients.iter_mut() {
                    *coeff = &*coeff * &inv_a1;
                }
            }
        }
    }
}

/// Diamond operator <d> (character twist)
#[derive(Debug, Clone)]
pub struct DiamondOperator {
    /// The integer d (coprime to level)
    d: u64,
    /// Level
    level: u64,
}

impl DiamondOperator {
    /// Create a new diamond operator <d>
    pub fn new(d: u64, level: u64) -> Option<Self> {
        if gcd_u64(d, level) == 1 {
            Some(DiamondOperator { d, level })
        } else {
            None
        }
    }

    /// Get the parameter d
    pub fn d(&self) -> u64 {
        self.d
    }

    /// Get the level
    pub fn level(&self) -> u64 {
        self.level
    }

    /// Apply to a modular form (modifies q-expansion)
    pub fn apply_to_coefficients(
        &self,
        input_coeffs: &HashMap<u64, Rational>,
    ) -> HashMap<u64, Rational> {
        // For Gamma1(N), <d> acts by character twist; the action on q-expansion
        // coefficients requires evaluating a Dirichlet character, which is not
        // yet implemented. Previously this was a no-op that just cloned the input.
        let _ = input_coeffs;
        unimplemented!(
            "DiamondOperator::apply_to_coefficients not yet implemented (facade): was a no-op"
        )
    }
}

/// Atkin-Lehner involution W_Q (for Q || N)
#[derive(Debug, Clone)]
pub struct AtkinLehnerInvolution {
    /// The integer Q (exact divisor of level)
    q: u64,
    /// Level
    level: u64,
}

impl AtkinLehnerInvolution {
    /// Create a new Atkin-Lehner involution W_Q
    pub fn new(q: u64, level: u64) -> Option<Self> {
        // Check that Q || N (Q divides N and gcd(Q, N/Q) = 1)
        if level % q != 0 {
            return None;
        }
        let quotient = level / q;
        if gcd_u64(q, quotient) != 1 {
            return None;
        }
        Some(AtkinLehnerInvolution { q, level })
    }

    /// Get Q
    pub fn q(&self) -> u64 {
        self.q
    }

    /// Get the level
    pub fn level(&self) -> u64 {
        self.level
    }

    /// Apply to modular form coefficients
    /// W_Q typically has eigenvalues ±1
    pub fn apply_to_coefficients(
        &self,
        input_coeffs: &HashMap<u64, Rational>,
    ) -> HashMap<u64, Rational> {
        // Full implementation requires a matrix representation of W_Q on the
        // modular symbols / modular forms space. Previously this was a no-op
        // that just cloned the input.
        let _ = input_coeffs;
        unimplemented!(
            "AtkinLehnerInvolution::apply_to_coefficients not yet implemented (facade): was a no-op"
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hecke_operator() {
        let t2 = HeckeOperator::new(2, 1);
        assert_eq!(t2.index(), 2);
        assert_eq!(t2.level(), 1);
        assert!(t2.is_good());
    }

    #[test]
    fn test_hecke_operator_good_bad() {
        let t2_level1 = HeckeOperator::new(2, 1);
        assert!(t2_level1.is_good());

        let t2_level2 = HeckeOperator::new(2, 2);
        assert!(t2_level2.is_bad());

        let t3_level2 = HeckeOperator::new(3, 2);
        assert!(t3_level2.is_good());
    }

    #[test]
    fn test_hecke_algebra() {
        let hecke = HeckeAlgebra::new(11, 2, 2);
        assert_eq!(hecke.level(), 11);
        assert_eq!(hecke.weight(), 2);
        assert_eq!(hecke.dimension(), 2);

        let t2 = hecke.hecke_operator(2);
        assert_eq!(t2.index(), 2);
    }

    /// a_n tables verified independently in python: prime indices by direct
    /// point counting on the curve (nonsingular counts at multiplicative
    /// primes), composite indices from the classical eta products whose
    /// prime coefficients were matched against the point counts, and which
    /// satisfy the weight-2 Hecke recursions.
    fn check_eigenvalues(level: u64, expected: &[i64]) {
        let h = HeckeAlgebra::new(level, 2, 2);
        let ev = h.eigenvalues(expected.len() as u64);
        assert_eq!(ev.len(), expected.len());
        for (i, a) in expected.iter().enumerate() {
            let n = (i + 1) as u64;
            assert_eq!(
                ev[&n],
                Rational::from_integer(Integer::from(*a)),
                "a_{n} at level {level}"
            );
        }
    }

    #[test]
    fn test_hecke_algebra_eigenvalues_level_11() {
        // 11a: y^2 + y = x^3 - x^2 - 10x - 20 (conductor 11 = -Delta support,
        // c4 = 496 coprime to 11).
        check_eigenvalues(
            11,
            &[1, -2, -1, 2, 1, 2, -2, 0, -2, -2, 1, -2, 4, 4],
        );
    }

    #[test]
    fn test_hecke_algebra_eigenvalues_level_14() {
        // 14a: y^2 + xy + y = x^3 + 4x - 6 (Delta = -2^6 7^3, c4 = -215).
        check_eigenvalues(
            14,
            &[1, -1, -2, 1, 0, 2, 1, -1, 1, 0, 0, -2, -4, -1],
        );
    }

    #[test]
    fn test_hecke_algebra_eigenvalues_level_15() {
        // 15a: y^2 + xy + y = x^3 + x^2 - 10x - 10 (Delta = 3^4 5^4, c4 = 481).
        check_eigenvalues(
            15,
            &[1, -1, -1, -1, 1, 1, 0, 3, 1, -1, -4, 1, -2, 0],
        );
    }

    #[test]
    #[should_panic(expected = "not scalar")]
    fn test_hecke_algebra_eigenvalues_level_37_honestly_unimplemented() {
        // Level 37 has two distinct eigensystems (a_2 = -2 and 0), so T_2 is
        // not scalar on the cuspidal space and the newform decomposition is
        // honestly refused.
        let h = HeckeAlgebra::new(37, 2, 4);
        let _ = h.eigenvalues(2);
    }

    #[test]
    #[should_panic(expected = "no newform")]
    fn test_hecke_algebra_eigenvalues_genus_zero_honestly_unimplemented() {
        let h = HeckeAlgebra::new(3, 2, 0);
        let _ = h.eigenvalues(2);
    }

    #[test]
    #[should_panic(expected = "weight 2")]
    fn test_hecke_algebra_eigenvalues_higher_weight_honestly_unimplemented() {
        let h = HeckeAlgebra::new(1, 12, 1);
        let _ = h.eigenvalues(2);
    }

    #[test]
    fn test_newform() {
        let mut f = Newform::new(2, 11);
        f.set_coefficient(1, Rational::one());
        assert_eq!(f.coefficient(1), Some(&Rational::one()));
        assert!(f.is_normalized());
    }

    #[test]
    fn test_newform_normalization() {
        let mut f = Newform::new(2, 11);
        f.set_coefficient(1, Rational::from_integer(Integer::from(2)));
        f.set_coefficient(2, Rational::from_integer(Integer::from(4)));

        f.normalize();
        assert_eq!(f.coefficient(1), Some(&Rational::one()));
        assert_eq!(
            f.coefficient(2),
            Some(&Rational::from_integer(Integer::from(2)))
        );
    }

    #[test]
    fn test_diamond_operator() {
        let diamond = DiamondOperator::new(3, 11);
        assert!(diamond.is_some());
        let d = diamond.unwrap();
        assert_eq!(d.d(), 3);
        assert_eq!(d.level(), 11);

        // Should fail for non-coprime d
        let bad_diamond = DiamondOperator::new(2, 4);
        assert!(bad_diamond.is_none());
    }

    #[test]
    fn test_atkin_lehner() {
        // W_11 for level 11
        let w = AtkinLehnerInvolution::new(11, 11);
        assert!(w.is_some());

        // W_4 for level 12 (4 || 12: 4 | 12 and gcd(4, 12/4) = gcd(4, 3) = 1)
        let w2 = AtkinLehnerInvolution::new(4, 12);
        assert!(w2.is_some());

        // Q = 2 does NOT exactly divide N = 4: gcd(2, 4/2) = gcd(2, 2) = 2 != 1
        let not_exact = AtkinLehnerInvolution::new(2, 4);
        assert!(not_exact.is_none());

        // Should fail if Q doesn't even divide N
        let bad_w = AtkinLehnerInvolution::new(3, 11);
        assert!(bad_w.is_none()); // 3 doesn't divide 11
    }
}
