//! Explicit embedding of a hyperbolic triangle group Δ(a,b,c) into PSL₂(ℝ), the
//! foundation of the Klug–Musty–Schiavone–Voight (KMSV) numerical method for
//! computing three-point branched covers (Belyi maps) of cocompact triangle groups.
//! Reference: Klug–Musty–Schiavone–Voight, "Numerical calculation of three-point
//! branched covers of the projective line", LMS J. Comput. Math. 17 (2014), §2.
//!
//! Our target is Δ(2,12,5) — the triangle group for the [2,12,5] M₂₄ passport
//! (2⁸1⁸ over 0, 12² over 1, 5⁴1⁴ over ∞), which is cocompact (all orders finite,
//! χ(2,12,5)=1−1/2−1/12−1/5 = 0.2833… > 0), so it acts on the hyperbolic plane ℍ.
//!
//! §2 construction: a hyperbolic triangle T(a,b,c) with angles π/a, π/b, π/c, with
//! z_a = i, z_b = μi on the imaginary axis, z_c in the right half. The
//! orientation-preserving subgroup is generated by δ_a, δ_b, δ_c (CCW rotations by
//! 2π/a, 2π/b, 2π/c around z_a, z_b, z_c) with relations
//!     δ_a^a = δ_b^b = δ_c^c = δ_c δ_b δ_a = 1.

use num_complex::Complex64;

/// An element of PSL₂(ℝ): a real Möbius transformation `z ↦ (az+b)/(cz+d)`,
/// represented up to sign (so `M` and `−M` are equal).
#[derive(Clone, Copy, Debug)]
pub struct Mobius {
    pub a: f64,
    pub b: f64,
    pub c: f64,
    pub d: f64,
}

impl Mobius {
    pub fn new(a: f64, b: f64, c: f64, d: f64) -> Self {
        Mobius { a, b, c, d }
    }

    pub fn identity() -> Self {
        Mobius::new(1.0, 0.0, 0.0, 1.0)
    }

    /// Matrix product `self · other` (apply `other` first when acting on points).
    pub fn mul(&self, o: &Mobius) -> Mobius {
        Mobius::new(
            self.a * o.a + self.b * o.c,
            self.a * o.b + self.b * o.d,
            self.c * o.a + self.d * o.c,
            self.c * o.b + self.d * o.d,
        )
    }

    pub fn det(&self) -> f64 {
        self.a * self.d - self.b * self.c
    }

    /// Inverse in PSL₂ (normalized by determinant).
    pub fn inverse(&self) -> Mobius {
        let det = self.det();
        Mobius::new(self.d / det, -self.b / det, -self.c / det, self.a / det)
    }

    /// Action on a point of the upper half-plane (or ℂ ∪ ∞).
    pub fn apply(&self, z: Complex64) -> Complex64 {
        (Complex64::new(self.a, 0.0) * z + Complex64::new(self.b, 0.0))
            / (Complex64::new(self.c, 0.0) * z + Complex64::new(self.d, 0.0))
    }

    pub fn pow(&self, n: u32) -> Mobius {
        let mut acc = Mobius::identity();
        for _ in 0..n {
            acc = acc.mul(self);
        }
        acc
    }

    /// Is this a scalar matrix (i.e. `±I` in PSL₂), to tolerance? Normalizes by the
    /// largest entry so the test is scale-free.
    pub fn is_scalar(&self, tol: f64) -> bool {
        let scale = self.a.abs().max(self.d.abs()).max(1e-300);
        (self.b.abs() / scale) < tol
            && (self.c.abs() / scale) < tol
            && ((self.a - self.d).abs() / scale) < tol
    }

    /// Frobenius distance to `±I` after normalizing to unit determinant — a smooth
    /// proxy for "is a scalar".
    pub fn scalar_defect(&self) -> f64 {
        let s = self.det().abs().sqrt().max(1e-300);
        let (a, b, c, d) = (self.a / s, self.b / s, self.c / s, self.d / s);
        // distance to ±I: min over the two signs of ((a∓1)²+b²+c²+(d∓1)²)
        let plus = (a - 1.0).powi(2) + b * b + c * c + (d - 1.0).powi(2);
        let minus = (a + 1.0).powi(2) + b * b + c * c + (d + 1.0).powi(2);
        plus.min(minus).sqrt()
    }
}

/// The explicit embedding data of Δ(a,b,c) ↪ PSL₂(ℝ).
#[derive(Clone, Debug)]
pub struct TriangleGroup {
    pub a: u32,
    pub b: u32,
    pub c: u32,
    /// μ with z_b = μ·i.
    pub mu: f64,
    /// The three triangle vertices z_a = i, z_b = μi, z_c (in the right half-plane).
    pub z_a: Complex64,
    pub z_b: Complex64,
    pub z_c: Complex64,
    /// CCW rotations by 2π/a, 2π/b, 2π/c around z_a, z_b, z_c.
    pub delta_a: Mobius,
    pub delta_b: Mobius,
    pub delta_c: Mobius,
}

impl TriangleGroup {
    /// Build the embedding for the hyperbolic triple `(a,b,c)` (KMSV §2).
    pub fn new(a: u32, b: u32, c: u32) -> Self {
        let (pa, pb, pc) = (
            std::f64::consts::PI / a as f64,
            std::f64::consts::PI / b as f64,
            std::f64::consts::PI / c as f64,
        );
        // cosh d(i,μi) = 1 + (μ−1)²/(2μ) = Λ := (cos π/a cos π/b + cos π/c)/(sin π/a sin π/b)
        // (the hyperbolic law of cosines). This gives μ² − 2Λμ + 1 = 0, so μ = Λ + √(Λ²−1).
        // NB: the KMSV text writes λ with a spurious factor 1/2; the consistent Λ has none.
        let big_lambda = (pa.cos() * pb.cos() + pc.cos()) / (pa.sin() * pb.sin());
        let mu = big_lambda + (big_lambda * big_lambda - 1.0).sqrt();

        let z_a = Complex64::new(0.0, 1.0);
        let z_b = Complex64::new(0.0, mu);
        // z_c from (2.4): the intersection of the two bounding geodesics in ℍ.
        let denom = 2.0 * (pa.cos() / pa.sin() + mu * (pb.cos() / pb.sin()));
        let re = (mu * mu - 1.0) / denom;
        let inside = 1.0 / (pa.sin() * pa.sin()) - (re - pa.cos() / pa.sin()).powi(2);
        let z_c = Complex64::new(re, inside.sqrt());

        // δ_a: CCW rotation by 2π/a around i = [[cos(π/a), sin(π/a)],[−sin(π/a), cos(π/a)]].
        let delta_a = Mobius::new(pa.cos(), pa.sin(), -pa.sin(), pa.cos());
        // δ_b: same rotation by 2π/b conjugated by z ↦ μz (which sends i ↦ μi = z_b).
        //   M = diag(√μ, 1/√μ);  δ_b = M · R(π/b) · M⁻¹.
        let sq = mu.sqrt();
        let m = Mobius::new(sq, 0.0, 0.0, 1.0 / sq);
        let r_b = Mobius::new(pb.cos(), pb.sin(), -pb.sin(), pb.cos());
        let delta_b = m.mul(&r_b).mul(&m.inverse());
        // δ_c from the product relation δ_c δ_b δ_a = 1 ⇒ δ_c = (δ_b δ_a)⁻¹.
        let delta_c = delta_b.mul(&delta_a).inverse();

        TriangleGroup { a, b, c, mu, z_a, z_b, z_c, delta_a, delta_b, delta_c }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn check_orders(tg: &TriangleGroup) {
        // δ_a^a, δ_b^b, δ_c^c, and δ_c δ_b δ_a must all be ±I.
        assert!(tg.delta_a.pow(tg.a).is_scalar(1e-9), "δ_a^a not ±I");
        assert!(tg.delta_b.pow(tg.b).is_scalar(1e-9), "δ_b^b not ±I");
        assert!(tg.delta_c.pow(tg.c).is_scalar(1e-9), "δ_c^c not ±I");
        let prod = tg.delta_c.mul(&tg.delta_b).mul(&tg.delta_a);
        assert!(prod.is_scalar(1e-9), "δ_c δ_b δ_a not ±I");
        // lower powers must NOT be scalar (genuine order, not a divisor).
        assert!(!tg.delta_b.pow(tg.b / 2).is_scalar(1e-6), "δ_b has smaller order");
    }

    fn check_fixed_points(tg: &TriangleGroup) {
        // δ_s fixes z_s.
        let da = tg.delta_a.apply(tg.z_a);
        let db = tg.delta_b.apply(tg.z_b);
        let dc = tg.delta_c.apply(tg.z_c);
        assert!((da - tg.z_a).norm() < 1e-9, "δ_a moves z_a: {da}");
        assert!((db - tg.z_b).norm() < 1e-9, "δ_b moves z_b: {db}");
        assert!((dc - tg.z_c).norm() < 1e-8, "δ_c moves z_c: {dc}");
    }

    #[test]
    fn triangle_2_12_5() {
        let tg = TriangleGroup::new(2, 12, 5);
        // sanity on μ (≈ 6.088 by hand: Λ = cos(π/5)/sin(π/12) ≈ 3.126, μ = Λ+√(Λ²−1)).
        assert!((tg.mu - 6.088).abs() < 1e-2, "μ = {}", tg.mu);
        // z_c is genuinely in ℍ (positive imaginary part).
        assert!(tg.z_c.im > 0.0, "z_c not in upper half plane");
        check_orders(&tg);
        check_fixed_points(&tg);
    }

    #[test]
    fn triangle_2_3_7_hurwitz() {
        // The (2,3,7) Hurwitz triangle group — a standard sanity check.
        let tg = TriangleGroup::new(2, 3, 7);
        check_orders(&tg);
        check_fixed_points(&tg);
    }

    #[test]
    fn triangle_2_3_8() {
        let tg = TriangleGroup::new(2, 3, 8);
        check_orders(&tg);
        check_fixed_points(&tg);
    }
}
