//! Matrix algebras `Mₙ(F)` and finitely generated subalgebras (MAGMA ch. 83).
//!
//! MAGMA source: Handbook chapter 83 (Matrix Algebras), §83.2
//! (`MatrixAlgebra(S, n)`, `MatrixAlgebra<S, n | L>`), §83.3
//! (`Generators`, `Ngens`) and §83.9 (`Dimension`, `Basis`, `BasisElement`).
//!
//! This module is **purely additive** and supplies two things:
//!
//! * [`MatN<F, N>`] — a *fixed size* `N×N` matrix element that implements the
//!   `rustmath-core` [`Algebra<F>`](rustmath_core::Algebra) tower
//!   (`Ring` + `Module<F>` + `VectorSpace<F>` + `Algebra<F>`). The const generic
//!   makes the static `Ring::zero()`/`one()` and `VectorSpace::dimension()`
//!   well-defined and every operator total — the contract those traits require.
//! * [`MatrixAlgebra<F>`] — a runtime [`Parent`] modelling either the full
//!   algebra `Mₙ(F)` or the unital `F`-subalgebra generated by a list of `n×n`
//!   matrices. It exposes `Dimension`, `Basis`, `BasisElement`, `Generators` and
//!   `Ngens`; the generated case computes its dimension/basis by closing the
//!   generators under multiplication (the standard "spinning" over `F`).

use crate::Matrix;
use rustmath_core::parent::{Parent, ParentWithBasis, ParentWithGenerators};
use rustmath_core::{
    Algebra, CommutativeRing, Field, MathError, Module, Result, Ring, VectorSpace as CoreVectorSpace,
};
use std::fmt;
use std::ops::{Add, Mul, Neg, Sub};

/// An `N × N` matrix over a field `F`, as an element of the matrix algebra
/// `Mₙ(F)`. All arithmetic is total (the shape is fixed by the const generic),
/// so this type implements the full core [`Algebra<F>`] tower.
#[derive(Clone, Debug, PartialEq)]
pub struct MatN<F: Field, const N: usize> {
    data: Vec<F>, // invariant: length N*N, row-major
}

impl<F: Field, const N: usize> MatN<F, N> {
    /// Build from a row-major length-`N²` array.
    pub fn from_flat(data: Vec<F>) -> Result<Self> {
        if data.len() != N * N {
            return Err(MathError::InvalidArgument(format!(
                "MatN<_, {N}> needs {} entries, got {}",
                N * N,
                data.len()
            )));
        }
        Ok(MatN { data })
    }

    /// Convert from a dynamic [`Matrix`] (must be `N × N`).
    pub fn from_matrix(m: &Matrix<F>) -> Result<Self> {
        if m.rows() != N || m.cols() != N {
            return Err(MathError::InvalidArgument(format!(
                "matrix is {}x{}, expected {N}x{N}",
                m.rows(),
                m.cols()
            )));
        }
        Ok(MatN {
            data: m.data().to_vec(),
        })
    }

    /// Convert to a dynamic [`Matrix`].
    pub fn to_matrix(&self) -> Matrix<F> {
        Matrix::from_vec(N, N, self.data.clone()).expect("shape is consistent")
    }

    /// Entry access.
    pub fn get(&self, i: usize, j: usize) -> &F {
        &self.data[i * N + j]
    }

    /// The trace (sum of the diagonal).
    pub fn trace(&self) -> F {
        let mut s = F::zero();
        for i in 0..N {
            s = s + self.data[i * N + i].clone();
        }
        s
    }
}

impl<F: Field, const N: usize> fmt::Display for MatN<F, N> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "MatN{N}[")?;
        for i in 0..N {
            if i > 0 {
                write!(f, "; ")?;
            }
            for j in 0..N {
                if j > 0 {
                    write!(f, ", ")?;
                }
                write!(f, "{}", self.data[i * N + j])?;
            }
        }
        write!(f, "]")
    }
}

impl<F: Field, const N: usize> Add for MatN<F, N> {
    type Output = Self;
    fn add(self, rhs: Self) -> Self {
        MatN {
            data: self
                .data
                .into_iter()
                .zip(rhs.data)
                .map(|(a, b)| a + b)
                .collect(),
        }
    }
}

impl<F: Field, const N: usize> Sub for MatN<F, N> {
    type Output = Self;
    fn sub(self, rhs: Self) -> Self {
        MatN {
            data: self
                .data
                .into_iter()
                .zip(rhs.data)
                .map(|(a, b)| a - b)
                .collect(),
        }
    }
}

impl<F: Field, const N: usize> Neg for MatN<F, N> {
    type Output = Self;
    fn neg(self) -> Self {
        MatN {
            data: self.data.into_iter().map(|a| -a).collect(),
        }
    }
}

impl<F: Field, const N: usize> Mul for MatN<F, N> {
    type Output = Self;
    fn mul(self, rhs: Self) -> Self {
        let mut data = vec![F::zero(); N * N];
        for i in 0..N {
            for j in 0..N {
                let mut acc = F::zero();
                for k in 0..N {
                    acc = acc + self.data[i * N + k].clone() * rhs.data[k * N + j].clone();
                }
                data[i * N + j] = acc;
            }
        }
        MatN { data }
    }
}

impl<F: Field, const N: usize> Ring for MatN<F, N> {
    fn zero() -> Self {
        MatN {
            data: vec![F::zero(); N * N],
        }
    }
    fn one() -> Self {
        let mut data = vec![F::zero(); N * N];
        for i in 0..N {
            data[i * N + i] = F::one();
        }
        MatN { data }
    }
    fn is_zero(&self) -> bool {
        self.data.iter().all(|x| x.is_zero())
    }
    fn is_one(&self) -> bool {
        for i in 0..N {
            for j in 0..N {
                let want = if i == j { F::one() } else { F::zero() };
                if self.data[i * N + j] != want {
                    return false;
                }
            }
        }
        true
    }
}

impl<F: Field, const N: usize> Module<F> for MatN<F, N> {
    fn scalar_mul(&self, scalar: &F) -> Self {
        MatN {
            data: self.data.iter().map(|a| a.clone() * scalar.clone()).collect(),
        }
    }
    fn zero() -> Self {
        <Self as Ring>::zero()
    }
    fn is_zero(&self) -> bool {
        <Self as Ring>::is_zero(self)
    }
}

impl<F: Field, const N: usize> CoreVectorSpace<F> for MatN<F, N> {
    fn dimension() -> Option<usize> {
        Some(N * N)
    }
}

// `rustmath_core::Algebra<F>` — a matrix algebra is the archetypal
// finite-dimensional associative algebra.
impl<F: Field, const N: usize> Algebra<F> for MatN<F, N> {
    fn scalar_mul(&self, scalar: &F) -> Self {
        Module::scalar_mul(self, scalar)
    }

    fn dimension(&self) -> Option<usize> {
        Some(N * N)
    }
}

// A matrix algebra is a (non-commutative) ring; we do NOT claim CommutativeRing
// in general. The marker below is available only when the caller knows N ≤ 1.
impl<F: Field> CommutativeRing for MatN<F, 1> {}

// ------------------------------------------------------------------------- //
// Runtime matrix-algebra parent                                             //
// ------------------------------------------------------------------------- //

/// A matrix algebra `A ⊆ Mₙ(F)`: either the full algebra or the unital
/// subalgebra generated by a list of matrices.
#[derive(Clone, Debug)]
pub struct MatrixAlgebra<F: Field> {
    n: usize,
    /// The defining generators (empty for the full algebra).
    generators: Vec<Matrix<F>>,
    /// An `F`-basis of `A`, as flattened `n²`-vectors (row-major).
    basis: Vec<Vec<F>>,
}

impl<F: Field> MatrixAlgebra<F> {
    /// The complete matrix algebra `Mₙ(F)` (MAGMA `MatrixAlgebra(S, n)`).
    pub fn full(n: usize) -> Self {
        // Basis = the n² matrix units E_ij.
        let mut basis = Vec::with_capacity(n * n);
        for i in 0..n {
            for j in 0..n {
                let mut e = vec![F::zero(); n * n];
                e[i * n + j] = F::one();
                basis.push(e);
            }
        }
        MatrixAlgebra {
            n,
            generators: Vec::new(),
            basis,
        }
    }

    /// The unital `F`-subalgebra of `Mₙ(F)` generated by `gens` (MAGMA
    /// `MatrixAlgebra<S, n | L>`). The dimension and basis are computed by
    /// closing `{I} ∪ gens` under (right) multiplication by the generators.
    pub fn generated(n: usize, gens: Vec<Matrix<F>>) -> Result<Self> {
        for g in &gens {
            if g.rows() != n || g.cols() != n {
                return Err(MathError::InvalidArgument(format!(
                    "generator is {}x{}, expected {n}x{n}",
                    g.rows(),
                    g.cols()
                )));
            }
        }
        let gen_flat: Vec<Vec<F>> = gens.iter().map(|g| g.data().to_vec()).collect();

        // Reduced-echelon basis (for independence tests) and the discovered
        // independent words (the returned basis), plus a work queue.
        let mut echelon: Vec<Vec<F>> = Vec::new();
        let mut basis: Vec<Vec<F>> = Vec::new();
        let mut queue: Vec<Vec<F>> = Vec::new();

        // Seed with the identity (unital algebra).
        let mut id = vec![F::zero(); n * n];
        for i in 0..n {
            id[i * n + i] = F::one();
        }
        for seed in std::iter::once(id).chain(gen_flat.iter().cloned()) {
            if reduce_into_basis(&mut echelon, seed.clone(), n) {
                basis.push(seed.clone());
                queue.push(seed);
            }
        }

        // Close under right multiplication by generators. Products of words are
        // words, so the span discovered is exactly the generated algebra.
        let cap = (n * n) + 1;
        while let Some(x) = queue.pop() {
            for g in &gen_flat {
                let prod = matmul_flat(&x, g, n);
                if reduce_into_basis(&mut echelon, prod.clone(), n) {
                    basis.push(prod.clone());
                    queue.push(prod);
                    if basis.len() > cap {
                        break;
                    }
                }
            }
        }

        Ok(MatrixAlgebra {
            n,
            generators: gens,
            basis,
        })
    }

    /// The degree `n` (matrices are `n × n`).
    pub fn degree(&self) -> usize {
        self.n
    }

    /// The `F`-dimension of the algebra (MAGMA `Dimension`).
    pub fn dimension(&self) -> usize {
        self.basis.len()
    }

    /// An `F`-basis of the algebra, as matrices (MAGMA `Basis`).
    pub fn basis(&self) -> Vec<Matrix<F>> {
        self.basis
            .iter()
            .map(|v| Matrix::from_vec(self.n, self.n, v.clone()).expect("shape ok"))
            .collect()
    }

    /// The `i`-th basis element (MAGMA `BasisElement`).
    pub fn basis_element_matrix(&self, i: usize) -> Option<Matrix<F>> {
        self.basis
            .get(i)
            .map(|v| Matrix::from_vec(self.n, self.n, v.clone()).expect("shape ok"))
    }

    /// The identity element `Iₙ`.
    pub fn identity(&self) -> Matrix<F> {
        Matrix::identity(self.n)
    }

    /// The defining generators (MAGMA `Generators`). For the full algebra this
    /// is the matrix-unit basis.
    pub fn generator_matrices(&self) -> Vec<Matrix<F>> {
        if self.generators.is_empty() {
            self.basis()
        } else {
            self.generators.clone()
        }
    }
}

impl<F: Field> Parent for MatrixAlgebra<F> {
    type Element = Matrix<F>;

    fn contains(&self, element: &Self::Element) -> bool {
        element.rows() == self.n && element.cols() == self.n
    }

    fn zero(&self) -> Option<Self::Element> {
        Some(Matrix::zeros(self.n, self.n))
    }

    fn one(&self) -> Option<Self::Element> {
        Some(Matrix::identity(self.n))
    }

    fn cardinality(&self) -> Option<usize> {
        None // infinite when F is infinite
    }

    fn name(&self) -> String {
        if self.generators.is_empty() {
            format!("Full matrix algebra M_{}(F)", self.n)
        } else {
            format!(
                "Matrix algebra of degree {} and dimension {}",
                self.n,
                self.dimension()
            )
        }
    }
}

impl<F: Field> ParentWithBasis for MatrixAlgebra<F> {
    type BasisIndex = usize;

    fn dimension(&self) -> Option<usize> {
        Some(MatrixAlgebra::dimension(self))
    }

    fn basis_element(&self, index: &usize) -> Option<Self::Element> {
        self.basis_element_matrix(*index)
    }

    fn basis_indices(&self) -> Vec<usize> {
        (0..self.basis.len()).collect()
    }
}

impl<F: Field> ParentWithGenerators for MatrixAlgebra<F> {
    fn generators(&self) -> Vec<Self::Element> {
        self.generator_matrices()
    }
}

// ------------------------------- helpers ---------------------------------- //

fn matmul_flat<F: Field>(a: &[F], b: &[F], n: usize) -> Vec<F> {
    let mut out = vec![F::zero(); n * n];
    for i in 0..n {
        for j in 0..n {
            let mut acc = F::zero();
            for k in 0..n {
                acc = acc + a[i * n + k].clone() * b[k * n + j].clone();
            }
            out[i * n + j] = acc;
        }
    }
    out
}

/// Row-reduce `v` (a flattened `n²`-vector) against the reduced-echelon `basis`.
/// If `v` is independent, its reduced form is inserted (keeping `basis` in
/// echelon form) and `true` is returned; otherwise `false`.
fn reduce_into_basis<F: Field>(basis: &mut Vec<Vec<F>>, mut v: Vec<F>, n: usize) -> bool {
    let len = n * n;
    for b in basis.iter() {
        // pivot column of b = first nonzero index
        if let Some(p) = (0..len).find(|&c| !b[c].is_zero()) {
            if !v[p].is_zero() {
                let factor = v[p].clone(); // b[p] == 1 (echelon rows are normalised)
                for c in p..len {
                    v[c] = v[c].clone() - factor.clone() * b[c].clone();
                }
            }
        }
    }
    // find pivot of the reduced v
    let pivot = (0..len).find(|&c| !v[c].is_zero());
    match pivot {
        None => false, // dependent
        Some(p) => {
            // normalise so v[p] == 1
            let inv = v[p].inverse().expect("nonzero pivot invertible");
            for c in p..len {
                v[c] = v[c].clone() * inv.clone();
            }
            // reduce existing basis rows above this new pivot (keep echelon)
            for b in basis.iter_mut() {
                if !b[p].is_zero() {
                    let factor = b[p].clone();
                    for c in p..len {
                        b[c] = b[c].clone() - factor.clone() * v[c].clone();
                    }
                }
            }
            basis.push(v);
            true
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rustmath_rationals::Rational;

    fn q(n: i64) -> Rational {
        Rational::from_integer(n)
    }

    #[test]
    fn matn_is_an_algebra() {
        // Exercise Ring + Module + VectorSpace + Algebra on M_2(Q).
        let a = MatN::<Rational, 2>::from_flat(vec![q(1), q(2), q(3), q(4)]).unwrap();
        let b = MatN::<Rational, 2>::from_flat(vec![q(0), q(1), q(1), q(0)]).unwrap();

        // Ring one/zero.
        let one = <MatN<Rational, 2> as Ring>::one();
        assert!(one.is_one());
        assert_eq!(a.clone() * one, a.clone());

        // multiplication (non-commutative in general): A*B != B*A here.
        let ab = a.clone() * b.clone();
        let ba = b.clone() * a.clone();
        assert_ne!(ab, ba);

        // A*B = [[2,1],[4,3]]
        assert_eq!(ab, MatN::from_flat(vec![q(2), q(1), q(4), q(3)]).unwrap());

        // Module: scalar_mul and additive structure.
        let scaled = Module::scalar_mul(&a, &q(2));
        assert_eq!(scaled, MatN::from_flat(vec![q(2), q(4), q(6), q(8)]).unwrap());
        assert_eq!(a.clone() - a.clone(), <MatN<Rational, 2> as Module<Rational>>::zero());

        // VectorSpace dimension = n² = 4.
        assert_eq!(
            <MatN<Rational, 2> as CoreVectorSpace<Rational>>::dimension(),
            Some(4)
        );

        // trace
        assert_eq!(a.trace(), q(5));
    }

    #[test]
    fn matn_roundtrips_with_dynamic_matrix() {
        let m = Matrix::from_vec(2, 2, vec![q(1), q(0), q(0), q(1)]).unwrap();
        let e = MatN::<Rational, 2>::from_matrix(&m).unwrap();
        assert!(e.is_one());
        assert_eq!(e.to_matrix(), m);
    }

    #[test]
    fn full_matrix_algebra_dimension_and_basis() {
        let a = MatrixAlgebra::<Rational>::full(3);
        assert_eq!(a.degree(), 3);
        assert_eq!(a.dimension(), 9);
        assert_eq!(a.basis().len(), 9);
        assert_eq!(ParentWithBasis::dimension(&a), Some(9));
        assert_eq!(a.basis_indices().len(), 9);
        assert!(a.contains(&Matrix::<Rational>::identity(3)));
        assert!(!a.contains(&Matrix::<Rational>::identity(2)));
        assert_eq!(a.one().unwrap(), Matrix::identity(3));
    }

    #[test]
    fn generated_diagonal_subalgebra_has_expected_dimension() {
        // Algebra generated by diag(1,0) inside M_2: {a·I + b·diag(1,0)} has
        // dimension 2 (spanned by I and diag(1,0)).
        let d = Matrix::from_vec(2, 2, vec![q(1), q(0), q(0), q(0)]).unwrap();
        let a = MatrixAlgebra::generated(2, vec![d]).unwrap();
        assert_eq!(a.dimension(), 2);
        assert_eq!(a.generators().len(), 1);
        assert_eq!(a.num_generators(), 1);
    }

    #[test]
    fn generated_algebra_of_full_generators_is_everything() {
        // E_12 and E_21 generate all of M_2 (since E12*E21=E11, E21*E12=E22).
        let e12 = Matrix::from_vec(2, 2, vec![q(0), q(1), q(0), q(0)]).unwrap();
        let e21 = Matrix::from_vec(2, 2, vec![q(0), q(0), q(1), q(0)]).unwrap();
        let a = MatrixAlgebra::generated(2, vec![e12, e21]).unwrap();
        assert_eq!(a.dimension(), 4);
    }
}
