//! Blow-ups of affine space, in charts.
//!
//! # The blow-up at the origin
//!
//! `Bl₀(𝔸ⁿ) ⊆ 𝔸ⁿ × ℙⁿ⁻¹` is the closure of the graph of `x ↦ (x₀ : … : x_{n−1})`; it is cut
//! out by the *incidence relations* `xᵢ yⱼ = xⱼ yᵢ`. It is covered by the `n` charts
//! `U_j = {yⱼ ≠ 0}`. Setting `yⱼ = 1` and writing `uᵢ = yᵢ/yⱼ` for `i ≠ j`, `uⱼ = xⱼ`, the
//! chart `U_j` becomes a copy of `𝔸ⁿ` with coordinates `u₀,…,u_{n−1}` and the projection
//! `π_j : U_j → 𝔸ⁿ` is
//!
//! ```text
//! xⱼ ↦ uⱼ ,      xᵢ ↦ uⱼ · uᵢ   (i ≠ j).
//! ```
//!
//! [`OriginChart::verify_incidence_relations`] checks that this really does parametrise the
//! incidence variety, so the charts are not asserted to be charts — they are *shown* to be.
//!
//! # Total and strict transforms
//!
//! The **total transform** of `V(I)` is `π_j*(I)`: just pull back the generators. It always
//! contains the whole exceptional divisor as a component whenever `V(I)` passes through the
//! centre, which is exactly the junk we want gone.
//!
//! The **strict (proper) transform** is the closure of `π_j⁻¹(V(I) ∖ {0})`, obtained by
//! removing every component supported on the exceptional divisor `E = V(uⱼ)`:
//!
//! ```text
//! I_strict = π_j*(I) : uⱼ^∞        (saturation)
//! ```
//!
//! For a **hypersurface** there is a second, completely independent route: `π_j*(f)` is
//! divisible by exactly `u_j^m` where `m = mult₀(f)` is the multiplicity of the singularity,
//! and the strict transform is the cofactor. Both routes are implemented
//! ([`OriginChart::strict_transform`] and [`OriginChart::strict_transform_hypersurface`])
//! and the tests cross-assert them against each other.
//!
//! ## Why the exponent is exactly the multiplicity
//!
//! Write `f = f_m + f_{m+1} + …` in homogeneous parts, `f_m ≠ 0`, so `m = mult₀(f)`. Then
//! `π_j*(f) = Σ_d u_j^d · f_d(u′)` where `u′` is `u` with a `1` in slot `j` — the
//! dehomogenisation of `f_d` at `y_j`. Hence `π_j*(f) = u_j^m · (f_m(u′) + u_j·(…))`, and
//! `f_m(u′) ≠ 0` because dehomogenising a non-zero *homogeneous* polynomial cannot kill it
//! (distinct degree-`m` monomials stay distinct: the exponent of `y_j` is determined by the
//! others). So `u_j^m ∥ π_j*(f)` exactly — in *every* chart.
//!
//! # Blowing up along an arbitrary ideal
//!
//! [`IdealBlowupChart`] handles `Bl_I(𝔸ⁿ)` for any `I = (g₀,…,g_{r−1})`, via the Rees
//! algebra `k[x][It] = k[x][g₀t,…,g_{r−1}t]`. Its presentation ideal is
//!
//! ```text
//! J = ker( k[x, y₀,…,y_{r−1}] → k[x, t],  yᵢ ↦ gᵢ t )  =  (yᵢ − gᵢ t : i) ∩ k[x, y],
//! ```
//! an elimination of `t` — so this is *computed*, not tabulated. The chart `U_k = {y_k ≠ 0}`
//! is `Spec` of `J + (y_k − 1)`, on which `I·𝒪` is generated by `g_k`, so `g_k` is the
//! exceptional divisor and the strict transform is again a saturation, this time by `g_k`.
//!
//! The tests check that blowing up `𝔸²` along `(x₀, x₁)` by this general route reproduces
//! the explicit origin chart above.

use rustmath_core::Field;
use rustmath_polynomials::elimination::{eliminate_with_budget, saturate_with_budget};
use rustmath_polynomials::groebner::{reduced_groebner_basis_field, GroebnerBudget, MonomialOrdering};
use rustmath_polynomials::multivariate::{Monomial, MultivariatePolynomial};
use std::collections::BTreeMap;

/// Divide out the largest power of the variable `v` that divides `f`.
///
/// Returns `(m, f / x_v^m)` where `m` is exact: `x_v^m | f` but `x_v^{m+1} ∤ f`. Exact by
/// construction — `m` is the least exponent of `x_v` over the terms of `f`, and every term
/// is then shifted down by `m`, so nothing is rounded away.
///
/// The zero polynomial is divisible by every power, so it is refused rather than answered.
pub fn divide_out_variable<R: Field>(
    f: &MultivariatePolynomial<R>,
    v: usize,
) -> Result<(u32, MultivariatePolynomial<R>), String> {
    if f.is_zero() {
        return Err("divide_out_variable: every power of x divides 0".to_string());
    }

    let m = f
        .terms()
        .map(|(mono, _)| mono.exponent(v))
        .min()
        .expect("non-zero polynomial has a term");

    let mut cofactor = MultivariatePolynomial::zero();
    for (mono, coeff) in f.terms() {
        let mut exps: BTreeMap<usize, u32> = mono
            .iter_exponents()
            .map(|(var, e)| (*var, *e))
            .collect();
        match exps.get(&v).copied() {
            Some(e) if e > m => {
                exps.insert(v, e - m);
            }
            _ => {
                exps.remove(&v);
            }
        }
        cofactor.add_term(Monomial::from_exponents(exps), coeff.clone());
    }

    Ok((m, cofactor))
}

/// The chart `U_j` of the blow-up of `𝔸ⁿ` at the origin.
///
/// The chart is itself a copy of `𝔸ⁿ`, with coordinates `u₀,…,u_{n−1}` carried on the same
/// variable indices `0..n` as the ambient `x₀,…,x_{n−1}`. That is deliberate: it makes the
/// chart projection an endomorphism of `k[x₀,…,x_{n−1}]`, so blow-ups compose without any
/// re-indexing — which is what the two-blow-up resolution tests need.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OriginChart {
    n: usize,
    j: usize,
}

impl OriginChart {
    /// The chart `U_j` of `Bl₀(𝔸ⁿ)`.
    pub fn new(n: usize, j: usize) -> Result<Self, String> {
        if n == 0 {
            return Err("OriginChart: 𝔸⁰ is a point; there is nothing to blow up".to_string());
        }
        if j >= n {
            return Err(format!("OriginChart: chart index {} must be < n = {}", j, n));
        }
        Ok(OriginChart { n, j })
    }

    /// The ambient dimension `n`.
    pub fn ambient_dimension(&self) -> usize {
        self.n
    }

    /// The chart index `j` (the chart is `{yⱼ ≠ 0}`).
    pub fn index(&self) -> usize {
        self.j
    }

    /// `π_j*(xᵢ)`: the pullback of the `i`-th ambient coordinate.
    ///
    /// `xⱼ ↦ uⱼ`, and `xᵢ ↦ uⱼ·uᵢ` for `i ≠ j`.
    pub fn coordinate_pullback<R: Field>(
        &self,
        i: usize,
    ) -> Result<MultivariatePolynomial<R>, String> {
        if i >= self.n {
            return Err(format!(
                "coordinate_pullback: coordinate {} out of range for 𝔸^{}",
                i, self.n
            ));
        }
        let uj: MultivariatePolynomial<R> = MultivariatePolynomial::variable(self.j);
        if i == self.j {
            Ok(uj)
        } else {
            Ok(uj * MultivariatePolynomial::variable(i))
        }
    }

    /// The substitution `x ↦ π_j*(x)` as a map on variable indices.
    fn substitution<R: Field>(&self) -> BTreeMap<usize, MultivariatePolynomial<R>> {
        (0..self.n)
            .map(|i| {
                (
                    i,
                    self.coordinate_pullback(i)
                        .expect("i < n by construction"),
                )
            })
            .collect()
    }

    /// `π_j*(f)`: pull a polynomial on `𝔸ⁿ` back to the chart.
    pub fn pullback<R: Field>(
        &self,
        f: &MultivariatePolynomial<R>,
    ) -> Result<MultivariatePolynomial<R>, String> {
        if let Some(v) = f.max_variable() {
            if v >= self.n {
                return Err(format!(
                    "pullback: {} uses variable x{} but the ambient is 𝔸^{}",
                    f, v, self.n
                ));
            }
        }
        Ok(f.substitute(&self.substitution()))
    }

    /// The exceptional divisor `E ∩ U_j = V(uⱼ)`, as the polynomial `uⱼ`.
    pub fn exceptional_divisor<R: Field>(&self) -> MultivariatePolynomial<R> {
        MultivariatePolynomial::variable(self.j)
    }

    /// The **total transform** `π_j*(I)`: the pullbacks of the generators.
    pub fn total_transform<R: Field>(
        &self,
        gens: &[MultivariatePolynomial<R>],
    ) -> Result<Vec<MultivariatePolynomial<R>>, String> {
        gens.iter().map(|g| self.pullback(g)).collect()
    }

    /// The **strict (proper) transform** of `V(I)` in this chart.
    ///
    /// `π_j*(I) : uⱼ^∞` — the total transform with every component supported on the
    /// exceptional divisor saturated away. Returned as a reduced Gröbner basis, so the
    /// answer is canonical and directly comparable.
    pub fn strict_transform<R: Field>(
        &self,
        gens: &[MultivariatePolynomial<R>],
        budget: &GroebnerBudget,
    ) -> Result<Vec<MultivariatePolynomial<R>>, String> {
        let total = self.total_transform(gens)?;
        let e: MultivariatePolynomial<R> = self.exceptional_divisor();
        let sat = saturate_with_budget(total, &e, budget)?;
        if sat.is_empty() {
            return Ok(vec![]);
        }
        reduced_groebner_basis_field(sat, MonomialOrdering::Grevlex, budget)
    }

    /// The strict transform of the **hypersurface** `V(f)`, together with the multiplicity.
    ///
    /// Returns `(m, f_strict)` where `π_j*(f) = uⱼ^m · f_strict` and `uⱼ ∤ f_strict`. By the
    /// argument in the module docs, `m = mult₀(f)` — the multiplicity of the singularity —
    /// and this holds in every chart.
    ///
    /// This is a *different computation* from [`Self::strict_transform`]: it factors, where
    /// the other saturates. The tests assert they agree.
    pub fn strict_transform_hypersurface<R: Field>(
        &self,
        f: &MultivariatePolynomial<R>,
    ) -> Result<(u32, MultivariatePolynomial<R>), String> {
        if f.is_zero() {
            return Err("strict_transform_hypersurface: V(0) = 𝔸ⁿ is not a hypersurface"
                .to_string());
        }
        let total = self.pullback(f)?;
        divide_out_variable(&total, self.j)
    }

    /// The incidence relations `xᵢ yⱼ − xⱼ yᵢ` cutting out `Bl₀(𝔸ⁿ) ⊆ 𝔸ⁿ × ℙⁿ⁻¹`.
    ///
    /// The `x` coordinates sit at indices `0..n` and the `y` coordinates at `n..2n`.
    pub fn incidence_relations<R: Field>(n: usize) -> Vec<MultivariatePolynomial<R>> {
        let mut rels = Vec::new();
        for a in 0..n {
            for b in a + 1..n {
                let xa: MultivariatePolynomial<R> = MultivariatePolynomial::variable(a);
                let xb: MultivariatePolynomial<R> = MultivariatePolynomial::variable(b);
                let ya: MultivariatePolynomial<R> = MultivariatePolynomial::variable(n + a);
                let yb: MultivariatePolynomial<R> = MultivariatePolynomial::variable(n + b);
                rels.push(xa * yb - xb * ya);
            }
        }
        rels
    }

    /// Check that this chart really parametrises the incidence variety.
    ///
    /// Substitutes `xᵢ ↦ π_j*(xᵢ)`, `yᵢ ↦ uᵢ` (`i ≠ j`), `yⱼ ↦ 1` into every incidence
    /// relation and returns `true` iff all of them become identically zero. This is what
    /// makes `U_j` a chart *of the blow-up* rather than an arbitrary map `𝔸ⁿ → 𝔸ⁿ`.
    pub fn verify_incidence_relations<R: Field>(&self) -> bool {
        let mut images: BTreeMap<usize, MultivariatePolynomial<R>> = self.substitution();
        for i in 0..self.n {
            let image = if i == self.j {
                MultivariatePolynomial::constant(R::one())
            } else {
                MultivariatePolynomial::variable(i)
            };
            images.insert(self.n + i, image);
        }

        Self::incidence_relations::<R>(self.n)
            .iter()
            .all(|rel| rel.substitute(&images).is_zero())
    }
}

/// A chart `U_k = {y_k ≠ 0}` of the blow-up `Bl_I(𝔸ⁿ)` along an arbitrary ideal
/// `I = (g₀,…,g_{r−1})`.
///
/// Unlike [`OriginChart`], this chart is *not* an affine space: it is the closed subscheme
/// of `𝔸ⁿ × 𝔸^{r−1}` cut out by [`Self::chart_ideal`]. The `x` coordinates keep indices
/// `0..n`; the Rees variable `yᵢ` lives at index `n + i` (and `y_k` is gone — it has been
/// set to 1).
#[derive(Debug, Clone)]
pub struct IdealBlowupChart<R: Field> {
    n: usize,
    k: usize,
    center: Vec<MultivariatePolynomial<R>>,
    relations: Vec<MultivariatePolynomial<R>>,
}

impl<R: Field> IdealBlowupChart<R> {
    /// Build the chart `U_k` of `Bl_I(𝔸ⁿ)`, computing the Rees relations by elimination.
    pub fn new(
        n: usize,
        center: Vec<MultivariatePolynomial<R>>,
        k: usize,
        budget: &GroebnerBudget,
    ) -> Result<Self, String> {
        let center: Vec<_> = center.into_iter().filter(|g| !g.is_zero()).collect();
        let r = center.len();
        if r == 0 {
            return Err("IdealBlowupChart: cannot blow up along the zero ideal".to_string());
        }
        if k >= r {
            return Err(format!(
                "IdealBlowupChart: chart index {} must be < r = {} generators",
                k, r
            ));
        }
        for g in &center {
            if let Some(v) = g.max_variable() {
                if v >= n {
                    return Err(format!(
                        "IdealBlowupChart: generator {} uses x{} but the ambient is 𝔸^{}",
                        g, v, n
                    ));
                }
            }
        }

        // Rees presentation: eliminate t from (y_i − g_i·t). Variables: x at 0..n,
        // y_i at n+i, t at n+r.
        let t_index = n + r;
        let t: MultivariatePolynomial<R> = MultivariatePolynomial::variable(t_index);
        let graph: Vec<MultivariatePolynomial<R>> = center
            .iter()
            .enumerate()
            .map(|(i, g)| {
                MultivariatePolynomial::variable(n + i) - g.clone() * t.clone()
            })
            .collect();

        let rees = eliminate_with_budget(graph, &[t_index], budget)?;

        // Dehomogenise: y_k ↦ 1.
        let mut images: BTreeMap<usize, MultivariatePolynomial<R>> = BTreeMap::new();
        images.insert(n + k, MultivariatePolynomial::constant(R::one()));

        let relations: Vec<MultivariatePolynomial<R>> = rees
            .iter()
            .map(|g| g.substitute(&images))
            .filter(|g| !g.is_zero())
            .collect();

        Ok(IdealBlowupChart {
            n,
            k,
            center,
            relations,
        })
    }

    /// The ambient dimension `n` of the space being blown up.
    pub fn ambient_dimension(&self) -> usize {
        self.n
    }

    /// The chart index `k`.
    pub fn index(&self) -> usize {
        self.k
    }

    /// The generators of the centre `I`.
    pub fn center(&self) -> &[MultivariatePolynomial<R>] {
        &self.center
    }

    /// The ideal cutting the chart out of `𝔸ⁿ × 𝔸^{r−1}`: the Rees relations with `y_k = 1`.
    pub fn chart_ideal(&self) -> &[MultivariatePolynomial<R>] {
        &self.relations
    }

    /// The exceptional divisor in this chart: `V(g_k)`.
    ///
    /// On `U_k` the pulled-back ideal `I·𝒪` is generated by `g_k`, because `gᵢ = g_k·(yᵢ/y_k)`
    /// there — the inverse image of the centre is a *principal* (Cartier) divisor, which is
    /// the defining property of the blow-up.
    pub fn exceptional_divisor(&self) -> &MultivariatePolynomial<R> {
        &self.center[self.k]
    }

    /// The total transform of `V(I′)` in this chart: the chart relations plus the generators.
    ///
    /// The `x` coordinates are still coordinates on the chart, so a polynomial on `𝔸ⁿ` pulls
    /// back to itself; the content is in the chart relations.
    pub fn total_transform(
        &self,
        gens: &[MultivariatePolynomial<R>],
    ) -> Vec<MultivariatePolynomial<R>> {
        let mut out = self.relations.clone();
        out.extend(gens.iter().cloned());
        out
    }

    /// The strict transform of `V(I′)` in this chart: the total transform saturated by `g_k`.
    pub fn strict_transform(
        &self,
        gens: &[MultivariatePolynomial<R>],
        budget: &GroebnerBudget,
    ) -> Result<Vec<MultivariatePolynomial<R>>, String> {
        let total = self.total_transform(gens);
        let e = self.exceptional_divisor().clone();
        let sat = saturate_with_budget(total, &e, budget)?;
        if sat.is_empty() {
            return Ok(vec![]);
        }
        reduced_groebner_basis_field(sat, MonomialOrdering::Grevlex, budget)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::singularity::{is_smooth_hypersurface, is_unit_ideal};
    use rustmath_core::Ring;
    use rustmath_integers::Integer;
    use rustmath_polynomials::elimination::{
        eliminate_with_budget, ideal_intersection_with_budget, krull_dimension,
    };
    use rustmath_polynomials::groebner::ideal_membership_field;
    use rustmath_rationals::Rational;

    type P = MultivariatePolynomial<Rational>;

    fn q(n: i64) -> Rational {
        Rational::from_integer(Integer::from(n))
    }

    fn term(c: i64, powers: &[(usize, u32)]) -> P {
        let mut m = Monomial::new();
        for (v, e) in powers {
            m = m.mul(&Monomial::variable(*v, *e));
        }
        let mut p = P::zero();
        p.add_term(m, q(c));
        p
    }

    fn var(v: usize) -> P {
        term(1, &[(v, 1)])
    }

    fn con(c: i64) -> P {
        term(c, &[])
    }

    fn b() -> GroebnerBudget {
        GroebnerBudget::generous()
    }

    fn show(ps: &[P]) -> Vec<String> {
        ps.iter().map(|p| p.to_string()).collect()
    }

    /// Ideal equality by mutual membership.
    fn same_ideal(a: &[P], c: &[P]) -> bool {
        let a_in_c = a
            .iter()
            .all(|p| ideal_membership_field(p, c, MonomialOrdering::Grevlex, &b()).unwrap_or(false));
        let c_in_a = c
            .iter()
            .all(|p| ideal_membership_field(p, a, MonomialOrdering::Grevlex, &b()).unwrap_or(false));
        a_in_c && c_in_a
    }

    // x = variable 0, y = variable 1.
    fn node() -> P {
        // y^2 - x^2 - x^3
        term(1, &[(1, 2)]) - term(1, &[(0, 2)]) - term(1, &[(0, 3)])
    }
    fn cusp() -> P {
        // y^2 - x^3
        term(1, &[(1, 2)]) - term(1, &[(0, 3)])
    }
    fn tacnode() -> P {
        // y^2 - x^4
        term(1, &[(1, 2)]) - term(1, &[(0, 4)])
    }
    fn a4() -> P {
        // y^2 - x^5
        term(1, &[(1, 2)]) - term(1, &[(0, 5)])
    }

    // -----------------------------------------------------------------------
    // The chart machinery itself
    // -----------------------------------------------------------------------

    #[test]
    fn chart_parametrises_the_incidence_variety() {
        // This is the check that U_j is a chart *of the blow-up*: the incidence relations
        // x_i y_j - x_j y_i must pull back to zero identically.
        for n in 1..=4 {
            for j in 0..n {
                let chart = OriginChart::new(n, j).unwrap();
                assert!(
                    chart.verify_incidence_relations::<Rational>(),
                    "chart U_{} of Bl_0(A^{}) does not satisfy the incidence relations",
                    j,
                    n
                );
            }
        }

        // And the relations are not vacuous: there are C(n,2) of them, and for n = 2 the
        // single relation x0*y1 - x1*y0 is genuinely non-zero before substitution.
        let rels: Vec<P> = OriginChart::incidence_relations(2);
        assert_eq!(rels.len(), 1);
        assert!(!rels[0].is_zero());
        assert_eq!(OriginChart::incidence_relations::<Rational>(3).len(), 3);
    }

    #[test]
    fn chart_pullback_is_the_textbook_substitution() {
        // n = 2, chart j = 0 ("x-chart"): x = u0, y = u0*u1.
        let c0 = OriginChart::new(2, 0).unwrap();
        assert_eq!(c0.coordinate_pullback::<Rational>(0).unwrap(), var(0));
        assert_eq!(
            c0.coordinate_pullback::<Rational>(1).unwrap(),
            var(0) * var(1)
        );

        // chart j = 1 ("y-chart"): y = u1, x = u1*u0.
        let c1 = OriginChart::new(2, 1).unwrap();
        assert_eq!(
            c1.coordinate_pullback::<Rational>(0).unwrap(),
            var(1) * var(0)
        );
        assert_eq!(c1.coordinate_pullback::<Rational>(1).unwrap(), var(1));

        assert!(OriginChart::new(2, 2).is_err());
        assert!(OriginChart::new(0, 0).is_err());
    }

    #[test]
    fn exceptional_divisor_is_the_inverse_image_of_the_centre() {
        // THE defining property of the blow-up: the inverse image ideal of the centre is
        // principal, generated by the exceptional divisor.  π*(x_0, ..., x_{n-1}) = (u_j).
        for n in 1..=4 {
            for j in 0..n {
                let chart = OriginChart::new(n, j).unwrap();
                let origin: Vec<P> = (0..n).map(var).collect();
                let total = chart.total_transform(&origin).unwrap();
                let e: P = chart.exceptional_divisor();

                assert!(
                    same_ideal(&total, &[e.clone()]),
                    "π*(m_0) should be (u_{}) in chart {} of A^{}, got {:?}",
                    j,
                    j,
                    n,
                    show(&total)
                );
            }
        }

        // E is a hyperplane in the chart: dim V(u_j) = n - 1. Over all charts these glue to
        // the P^{n-1} sitting over the origin (that gluing is exactly the incidence check
        // above, which pins the y-coordinates to the homogeneous coordinates of P^{n-1}).
        for n in 1..=4 {
            for j in 0..n {
                let chart = OriginChart::new(n, j).unwrap();
                let e: P = chart.exceptional_divisor();
                assert_eq!(
                    krull_dimension(vec![e], n, &b()).unwrap(),
                    n as isize - 1,
                    "E ∩ U_{} must be a hyperplane in A^{}",
                    j,
                    n
                );
            }
        }
    }

    #[test]
    fn divide_out_variable_is_exact() {
        // (u0^2)*(u1^2 - 1 - u0) — the node's total transform.
        let f = term(1, &[(0, 2), (1, 2)]) - term(1, &[(0, 2)]) - term(1, &[(0, 3)]);
        let (m, cof) = divide_out_variable(&f, 0).unwrap();
        assert_eq!(m, 2);
        assert_eq!(cof, term(1, &[(1, 2)]) - con(1) - var(0));
        // The cofactor is genuinely not divisible again.
        assert_eq!(divide_out_variable(&cof, 0).unwrap().0, 0);
        // Multiplying back reproduces f.
        assert_eq!(cof * term(1, &[(0, 2)]), f);

        assert!(divide_out_variable(&P::zero(), 0).is_err());
    }

    // -----------------------------------------------------------------------
    // The multiplicity cross-check: saturation vs factoring
    // -----------------------------------------------------------------------

    #[test]
    fn multiplicity_matches_in_every_chart_and_both_routes_agree() {
        // For each curve: the exponent of u_j dividing the total transform must equal the
        // order of vanishing at the origin (min total degree) — in EVERY chart — and the
        // cofactor must generate the same ideal as the saturation route.
        for (name, f, expected_mult) in [
            ("node", node(), 2u32),
            ("cusp", cusp(), 2),
            ("tacnode", tacnode(), 2),
            ("a4", a4(), 2),
            // A triple point, to make sure mult 2 is not hard-wired anywhere.
            ("ordinary triple point", term(1, &[(1, 3)]) - term(1, &[(0, 3)]), 3),
        ] {
            assert_eq!(
                f.order_at_origin().unwrap(),
                expected_mult,
                "{}: multiplicity at origin",
                name
            );

            for j in 0..2 {
                let chart = OriginChart::new(2, j).unwrap();

                // Route 1: factor out the highest power of u_j.
                let (m, strict_fac) = chart.strict_transform_hypersurface(&f).unwrap();
                assert_eq!(
                    m, expected_mult,
                    "{}: chart {} factoring route gave multiplicity {}",
                    name, j, m
                );

                // Route 2: saturate the total transform by u_j.
                let strict_sat = chart.strict_transform(&[f.clone()], &b()).unwrap();

                assert!(
                    same_ideal(&[strict_fac.clone()], &strict_sat),
                    "{}: chart {}: factoring route {} != saturation route {:?}",
                    name,
                    j,
                    strict_fac,
                    show(&strict_sat)
                );
            }
        }
    }

    // -----------------------------------------------------------------------
    // Gate 1: the node
    // -----------------------------------------------------------------------

    #[test]
    fn node_resolves_in_one_blowup_with_two_points_over_the_origin() {
        let f = node();
        let chart = OriginChart::new(2, 0).unwrap();

        // Total transform = u0^2 * (u1^2 - 1 - u0).   [sympy: -u0**2*(u0 - u1**2 + 1)]
        let total = chart.total_transform(&[f.clone()]).unwrap();
        let expected_total = term(1, &[(0, 2), (1, 2)]) - term(1, &[(0, 2)]) - term(1, &[(0, 3)]);
        assert_eq!(total, vec![expected_total]);

        // Strict transform = u1^2 - 1 - u0, and multiplicity 2.
        let (m, strict) = chart.strict_transform_hypersurface(&f).unwrap();
        assert_eq!(m, 2);
        let expected_strict = term(1, &[(1, 2)]) - con(1) - var(0);
        assert_eq!(strict, expected_strict, "strict transform of the node");

        // ---- THE RESOLUTION ----
        assert!(
            !is_smooth_hypersurface(&f, 2, &b()).unwrap(),
            "the node must be SINGULAR"
        );
        assert!(
            is_smooth_hypersurface(&strict, 2, &b()).unwrap(),
            "the strict transform of the node must be SMOOTH"
        );

        // ---- TWO points over the origin, i.e. the two branches are separated ----
        // The fibre is strict ∩ E = (u1^2 - 1 - u0, u0) = (u0, u1^2 - 1).
        let fibre = vec![strict.clone(), chart.exceptional_divisor()];
        let expected_fibre = vec![var(0), term(1, &[(1, 2)]) - con(1)];
        assert!(same_ideal(&fibre, &expected_fibre));

        // It is zero-dimensional...
        assert_eq!(krull_dimension(fibre.clone(), 2, &b()).unwrap(), 0);

        // ...and it splits as the intersection of TWO distinct reduced points, u1 = ±1.
        // (sympy: (u0, u1-1) ∩ (u0, u1+1) = [u0, u1**2 - 1].)
        let p_plus = vec![var(0), var(1) - con(1)];
        let p_minus = vec![var(0), var(1) + con(1)];
        let two_points = ideal_intersection_with_budget(p_plus.clone(), p_minus.clone(), &b())
            .unwrap();
        assert!(
            same_ideal(&fibre, &two_points),
            "the node's fibre must be exactly two distinct reduced points, got {:?}",
            show(&fibre)
        );

        // Both points really are on the strict transform, and they are distinct.
        for p in [&p_plus, &p_minus] {
            assert!(
                ideal_membership_field(&strict, p, MonomialOrdering::Grevlex, &b()).unwrap(),
                "the strict transform passes through {:?}",
                show(p)
            );
        }
        assert!(!same_ideal(&p_plus, &p_minus));
    }

    #[test]
    fn node_resolves_in_the_other_chart_too() {
        // y-chart (j = 1): x = u1*u0, y = u1. Total = u1^2 * (1 - u0^2 - u0^3*u1).
        // [sympy: y-chart strict = -u0**3*u1 - u0**2 + 1]
        let f = node();
        let chart = OriginChart::new(2, 1).unwrap();
        let (m, strict) = chart.strict_transform_hypersurface(&f).unwrap();
        assert_eq!(m, 2);
        let expected = con(1) - term(1, &[(0, 2)]) - term(1, &[(0, 3), (1, 1)]);
        assert_eq!(strict, expected);
        assert!(is_smooth_hypersurface(&strict, 2, &b()).unwrap());
    }

    // -----------------------------------------------------------------------
    // Gate 2: the cusp
    // -----------------------------------------------------------------------

    #[test]
    fn cusp_resolves_in_one_blowup_with_one_point_over_the_origin() {
        let f = cusp();
        let chart = OriginChart::new(2, 0).unwrap();

        let (m, strict) = chart.strict_transform_hypersurface(&f).unwrap();
        assert_eq!(m, 2, "the cusp has multiplicity 2");
        // Strict transform = u1^2 - u0.   [sympy: u0 - u1**2, same ideal]
        let expected_strict = term(1, &[(1, 2)]) - var(0);
        assert_eq!(strict, expected_strict);

        assert!(
            !is_smooth_hypersurface(&f, 2, &b()).unwrap(),
            "the cusp must be SINGULAR"
        );
        assert!(
            is_smooth_hypersurface(&strict, 2, &b()).unwrap(),
            "the strict transform of the cusp must be SMOOTH"
        );

        // ---- ONE point over the origin (contrast with the node's two) ----
        // The fibre is (u0, u1^2): supported at the single point (0,0), but NON-REDUCED.
        let fibre = vec![strict.clone(), chart.exceptional_divisor()];
        let expected_fibre = vec![var(0), term(1, &[(1, 2)])];
        assert!(same_ideal(&fibre, &expected_fibre));
        assert_eq!(krull_dimension(fibre.clone(), 2, &b()).unwrap(), 0);

        // Its support is the single point (u0, u1) — the strict transform is tangent to E.
        let origin_of_chart = vec![var(0), var(1)];
        assert!(
            ideal_membership_field(
                &term(1, &[(1, 2)]),
                &fibre,
                MonomialOrdering::Grevlex,
                &b()
            )
            .unwrap()
        );
        // u1 itself is NOT in the fibre ideal: the fibre is a fat point, not a reduced one.
        assert!(
            !ideal_membership_field(&var(1), &fibre, MonomialOrdering::Grevlex, &b()).unwrap(),
            "the cusp's fibre must be the non-reduced point (u0, u1^2)"
        );
        // ...but its radical is that single point.
        assert!(same_ideal(
            &vec![var(0), term(1, &[(1, 2)])],
            &fibre
        ));
        assert!(
            !same_ideal(&fibre, &origin_of_chart),
            "the fibre is (u0, u1^2), strictly smaller than the reduced point (u0, u1)"
        );

        // And it is NOT two distinct points, unlike the node — this is what distinguishes
        // a cusp from a node after one blow-up.
        let two_points = ideal_intersection_with_budget(
            vec![var(0), var(1) - con(1)],
            vec![var(0), var(1) + con(1)],
            &b(),
        )
        .unwrap();
        assert!(!same_ideal(&fibre, &two_points));
    }

    // -----------------------------------------------------------------------
    // Gate 3: singularities that need TWO blow-ups
    // -----------------------------------------------------------------------

    #[test]
    fn tacnode_needs_two_blowups() {
        // y^2 - x^4 = (y - x^2)(y + x^2): two smooth branches, tangent at the origin.
        let f = tacnode();
        let chart = OriginChart::new(2, 0).unwrap();

        assert!(!is_smooth_hypersurface(&f, 2, &b()).unwrap(), "tacnode is singular");

        // First blow-up: strict transform is u1^2 - u0^2 — a NODE, still singular.
        let (m1, strict1) = chart.strict_transform_hypersurface(&f).unwrap();
        assert_eq!(m1, 2);
        let expected1 = term(1, &[(1, 2)]) - term(1, &[(0, 2)]);
        assert_eq!(strict1, expected1);

        assert!(
            !is_smooth_hypersurface(&strict1, 2, &b()).unwrap(),
            "ONE blow-up must NOT resolve the tacnode — the strict transform u1^2 - u0^2 \
             is still singular (it is a node)"
        );
        // Still singular at the chart origin, with multiplicity 2 again.
        assert_eq!(strict1.order_at_origin().unwrap(), 2);

        // Second blow-up, of the same chart's origin. Because the chart coordinates reuse
        // the ambient indices, we can simply blow up again.
        let (m2, strict2) = chart.strict_transform_hypersurface(&strict1).unwrap();
        assert_eq!(m2, 2);
        // v1^2 - 1: two disjoint parallel lines. [sympy: v1**2 - 1]
        let expected2 = term(1, &[(1, 2)]) - con(1);
        assert_eq!(strict2, expected2);

        assert!(
            is_smooth_hypersurface(&strict2, 2, &b()).unwrap(),
            "TWO blow-ups must resolve the tacnode"
        );

        // Cross-check the second step against the saturation route as well.
        let strict2_sat = chart.strict_transform(&[strict1.clone()], &b()).unwrap();
        assert!(same_ideal(&[strict2.clone()], &strict2_sat));

        // The two branches are now genuinely separated: v1 = +1 and v1 = -1 are disjoint.
        assert!(is_unit_ideal(
            vec![var(1) - con(1), var(1) + con(1)],
            &b()
        )
        .unwrap());
    }

    #[test]
    fn a4_singularity_needs_two_blowups_and_passes_through_a_cusp() {
        // y^2 - x^5: the first blow-up turns it into a CUSP (y^2 - x^3), the second resolves.
        let f = a4();
        let chart = OriginChart::new(2, 0).unwrap();

        assert!(!is_smooth_hypersurface(&f, 2, &b()).unwrap());

        let (m1, strict1) = chart.strict_transform_hypersurface(&f).unwrap();
        assert_eq!(m1, 2);
        // u1^2 - u0^3 — literally the cusp again.
        let expected1 = term(1, &[(1, 2)]) - term(1, &[(0, 3)]);
        assert_eq!(strict1, expected1);
        assert_eq!(
            strict1, cusp(),
            "the first blow-up of y^2 - x^5 is exactly the cusp y^2 - x^3"
        );
        assert!(
            !is_smooth_hypersurface(&strict1, 2, &b()).unwrap(),
            "ONE blow-up must NOT resolve y^2 - x^5"
        );

        let (m2, strict2) = chart.strict_transform_hypersurface(&strict1).unwrap();
        assert_eq!(m2, 2);
        // v1^2 - v0.  [sympy: -v0 + v1**2]
        let expected2 = term(1, &[(1, 2)]) - var(0);
        assert_eq!(strict2, expected2);
        assert!(
            is_smooth_hypersurface(&strict2, 2, &b()).unwrap(),
            "TWO blow-ups must resolve y^2 - x^5"
        );
    }

    // -----------------------------------------------------------------------
    // Gate 4: THE self-certifying resolution gate
    // -----------------------------------------------------------------------

    /// The headline test: a machine-checked resolution of singularities.
    ///
    /// For each plane curve below we assert, with **no eyeballing**:
    ///
    /// 1. `1 ∉ (f, ∂f/∂x, ∂f/∂y)` — so there is a point of ℚ̄² where `f` and both partials
    ///    vanish: the curve is **not smooth over ℚ̄**. We also exhibit the witness: the
    ///    origin is a rational point of that singular subscheme.
    /// 2. after `k` blow-ups at the origin, `1 ∈ (f_k, ∂f_k/∂u, ∂f_k/∂v)` — so **no** point
    ///    of ℚ̄² kills the strict transform and its partials: it is **smooth over ℚ̄**.
    ///
    /// Both are decided by Buchberger over ℚ, and both statements are about ℚ̄, not ℚ: a
    /// Gröbner basis over ℚ stays a Gröbner basis over any extension, so `1 ∈ I` is a
    /// base-change-stable certificate (see `singularity`'s module docs). Nothing here says
    /// "no rational singular points" and calls it smoothness.
    #[test]
    fn resolution_of_singularities_is_machine_checked() {
        let chart = OriginChart::new(2, 0).unwrap();

        let cases: Vec<(&str, P, usize)> = vec![
            ("node    y^2 - x^2 - x^3", node(), 1),
            ("cusp    y^2 - x^3", cusp(), 1),
            ("tacnode y^2 - x^4", tacnode(), 2),
            ("A4      y^2 - x^5", a4(), 2),
        ];

        for (name, f, blowups_needed) in cases {
            // ---- 1. the original curve is SINGULAR, and the origin witnesses it ----
            let sing = crate::singularity::hypersurface_singular_locus(&f, 2);
            assert!(
                !is_unit_ideal(sing.clone(), &b()).unwrap(),
                "{}: the singular subscheme must NOT be the unit ideal",
                name
            );
            let origin = [q(0), q(0)];
            for g in &sing {
                assert!(
                    g.evaluate(&origin).is_zero(),
                    "{}: the origin must lie on the singular subscheme (generator {})",
                    name,
                    g
                );
            }

            // ---- 2. blow up until smooth, and check it takes exactly the expected number ----
            let mut current = f.clone();
            for step in 1..=blowups_needed {
                assert!(
                    !is_smooth_hypersurface(&current, 2, &b()).unwrap(),
                    "{}: still expected to be singular before blow-up {}",
                    name,
                    step
                );
                let (m, next) = chart.strict_transform_hypersurface(&current).unwrap();
                assert!(m >= 2, "{}: a singular point has multiplicity >= 2", name);

                // The saturation route must agree with the factoring route at every step.
                let via_saturation = chart.strict_transform(&[current.clone()], &b()).unwrap();
                assert!(
                    same_ideal(&[next.clone()], &via_saturation),
                    "{}: step {}: saturation and factoring disagree",
                    name,
                    step
                );

                current = next;
            }

            // ---- 3. RESOLVED: the unit ideal certificate ----
            let sing_after = crate::singularity::hypersurface_singular_locus(&current, 2);
            assert!(
                is_unit_ideal(sing_after, &b()).unwrap(),
                "{}: after {} blow-up(s) the strict transform {} must be SMOOTH \
                 (its singular subscheme must be the unit ideal)",
                name,
                blowups_needed,
                current
            );
        }
    }

    // -----------------------------------------------------------------------
    // Blowing up along a general ideal (the Rees-algebra route)
    // -----------------------------------------------------------------------

    #[test]
    fn general_blowup_along_the_origin_reproduces_the_explicit_chart() {
        // Bl_(x0,x1)(A^2), chart k = 0. The Rees relation is x0*y1 - x1*y0; setting y0 = 1
        // gives x0*y1 - x1.  [sympy: chart y0 = 1 ideal = [x*y1 - y]]
        // y_0 lives at index 2, y_1 at index 3.
        let center = vec![var(0), var(1)];
        let chart = IdealBlowupChart::new(2, center, 0, &b()).unwrap();

        let expected_relation = var(0) * var(3) - var(1);
        assert!(
            same_ideal(chart.chart_ideal(), &[expected_relation]),
            "chart ideal was {:?}",
            show(chart.chart_ideal())
        );

        // The exceptional divisor is g_0 = x0.
        assert_eq!(chart.exceptional_divisor(), &var(0));

        // Strict transform of the node.
        // [sympy: (x - y1**2 + 1, y - y1**3 + y1); eliminating y gives (x - y1**2 + 1)]
        let strict = chart.strict_transform(&[node()], &b()).unwrap();
        let expected = vec![
            var(0) - term(1, &[(3, 2)]) + con(1),
            var(1) - term(1, &[(3, 3)]) + var(3),
        ];
        assert!(
            same_ideal(&strict, &expected),
            "general strict transform was {:?}",
            show(&strict)
        );

        // Now eliminate the redundant coordinate x1 (it is determined by x1 = x0*y1). What
        // is left must be exactly the explicit chart's answer, with u0 = x0 and u1 = y1.
        let reduced = eliminate_with_budget(strict, &[1], &b()).unwrap();

        let explicit = OriginChart::new(2, 0).unwrap();
        let (_, explicit_strict) = explicit.strict_transform_hypersurface(&node()).unwrap();
        // relabel u1 (index 1) -> y1 (index 3); u0 (index 0) stays.
        let explicit_relabelled = explicit_strict
            .relabel(|v| if v == 1 { 3 } else { v })
            .unwrap();

        assert!(
            same_ideal(&reduced, &[explicit_relabelled.clone()]),
            "the general (Rees) blow-up and the explicit origin chart must agree: \
             got {:?}, explicit gives {}",
            show(&reduced),
            explicit_relabelled
        );
    }

    #[test]
    fn general_blowup_rejects_bad_input() {
        assert!(IdealBlowupChart::<Rational>::new(2, vec![], 0, &b()).is_err());
        assert!(IdealBlowupChart::new(2, vec![var(0), var(1)], 2, &b()).is_err());
        // A generator outside the ambient A^2.
        assert!(IdealBlowupChart::new(2, vec![var(0), var(5)], 0, &b()).is_err());
    }
}
