//! Elimination theory: elimination ideals, saturation, ideal intersection and quotient.
//!
//! Everything here is built on a Gröbner basis with respect to a *block elimination
//! order* ([`MonomialOrdering::Elimination`]) and on the Elimination Theorem:
//!
//! > **Elimination Theorem** (Cox–Little–O'Shea, *Ideals, Varieties, and Algorithms*,
//! > Ch. 3 §1, Thm. 2). Let `I ⊆ k[x_0,…,x_{n-1}]` be an ideal and let `G` be a Gröbner
//! > basis of `I` with respect to a monomial order having the elimination property for
//! > the block `x_0,…,x_{k-1}` (any monomial involving a block variable outranks every
//! > monomial involving none of them). Then
//! >
//! > `G ∩ k[x_k,…,x_{n-1}]` is a Gröbner basis of the elimination ideal
//! > `I ∩ k[x_k,…,x_{n-1}]`.
//!
//! So "run a Gröbner basis in the block order, then keep exactly the elements that do
//! not mention the eliminated variables" is not a heuristic — it is the theorem.
//!
//! All routines require `R: Field`. Buchberger's algorithm needs to divide by leading
//! coefficients; over a general ring the theory is different (strong Gröbner bases) and
//! we do not implement it, so we refuse rather than pretend.

use crate::groebner::{
    groebner_basis_field, reduced_groebner_basis_field, GroebnerBudget, MonomialOrdering,
};
use crate::multivariate::{Monomial, MultivariatePolynomial};
use rustmath_core::Field;
use std::collections::BTreeSet;

/// The smallest variable index not used by any of `polys`.
///
/// This is `max(all variable indices) + 1`, or `0` when no variable occurs at all.
/// Variables are unbounded `usize` indices with no ambient count, so a fresh variable
/// costs nothing — which is what makes the Rabinowitsch trick below free.
pub fn fresh_variable<R: Field>(polys: &[MultivariatePolynomial<R>]) -> usize {
    polys
        .iter()
        .filter_map(|p| p.max_variable())
        .max()
        .map(|m| m + 1)
        .unwrap_or(0)
}

/// Relabel so that `eliminate_vars` become `0..k` and everything else follows in order.
///
/// The elimination order is defined on a *prefix* block of variable indices, so to
/// eliminate an arbitrary set of variables we move them to the front, compute, and move
/// them back. Returns `(forward, backward, k)`, both maps indexed by variable index.
fn build_relabeling<R: Field>(
    gens: &[MultivariatePolynomial<R>],
    eliminate_vars: &[usize],
) -> (Vec<usize>, Vec<usize>, usize) {
    let elim: BTreeSet<usize> = eliminate_vars.iter().copied().collect();

    let mut occurring: BTreeSet<usize> = BTreeSet::new();
    for p in gens {
        for v in p.variables() {
            occurring.insert(v);
        }
    }
    for v in &elim {
        occurring.insert(*v);
    }

    let block: Vec<usize> = occurring.iter().copied().filter(|v| elim.contains(v)).collect();
    let rest: Vec<usize> = occurring.iter().copied().filter(|v| !elim.contains(v)).collect();
    let k = block.len();

    let width = occurring.iter().copied().max().map(|m| m + 1).unwrap_or(0);
    let mut forward = vec![usize::MAX; width];
    let mut backward = vec![usize::MAX; block.len() + rest.len()];

    for (new, old) in block.iter().chain(rest.iter()).enumerate() {
        forward[*old] = new;
        backward[new] = *old;
    }

    (forward, backward, k)
}

/// Compute a generating set of the elimination ideal `I ∩ k[remaining variables]`.
///
/// `I` is the ideal generated by `gens`; the variables listed in `eliminate_vars` are
/// eliminated. The returned polynomials generate `I ∩ k[x : x ∉ eliminate_vars]` — in
/// fact they are a Gröbner basis of it, by the Elimination Theorem quoted at the top of
/// this module.
///
/// Uses [`GroebnerBudget::default`]; see [`eliminate_with_budget`] to control it.
pub fn eliminate<R: Field>(
    gens: Vec<MultivariatePolynomial<R>>,
    eliminate_vars: &[usize],
) -> Result<Vec<MultivariatePolynomial<R>>, String> {
    eliminate_with_budget(gens, eliminate_vars, &GroebnerBudget::default())
}

/// [`eliminate`] with an explicit resource budget.
pub fn eliminate_with_budget<R: Field>(
    gens: Vec<MultivariatePolynomial<R>>,
    eliminate_vars: &[usize],
    budget: &GroebnerBudget,
) -> Result<Vec<MultivariatePolynomial<R>>, String> {
    let gens: Vec<_> = gens.into_iter().filter(|p| !p.is_zero()).collect();
    if gens.is_empty() {
        return Ok(vec![]);
    }

    let (forward, backward, k) = build_relabeling(&gens, eliminate_vars);

    let shifted: Vec<MultivariatePolynomial<R>> = gens
        .iter()
        .map(|p| p.relabel(|v| forward[v]))
        .collect::<Result<_, _>>()?;

    let gb = groebner_basis_field(shifted, MonomialOrdering::Elimination { block: k }, budget)?;

    // Elimination Theorem: keep exactly the elements free of the block variables.
    let kept: Vec<MultivariatePolynomial<R>> = gb
        .into_iter()
        .filter(|p| p.variables().iter().all(|v| *v >= k))
        .collect();

    let back: Vec<MultivariatePolynomial<R>> = kept
        .iter()
        .map(|p| p.relabel(|v| backward[v]))
        .collect::<Result<_, _>>()?;

    // Return the canonical (reduced) basis of the elimination ideal in the remaining
    // variables, so callers can compare results directly.
    if back.is_empty() {
        return Ok(vec![]);
    }
    reduced_groebner_basis_field(back, MonomialOrdering::Grevlex, budget)
}

/// The saturation `I : f^∞ = { g : f^m · g ∈ I for some m ≥ 0 }`.
///
/// Computed by the Rabinowitsch trick: introduce a **fresh** variable `t`, form the
/// ideal `I + (t·f − 1)` in one more variable, and eliminate `t`. Geometrically this
/// inverts `f`, so the components of `V(I)` contained in `V(f)` are thrown away, which
/// is exactly what saturation does.
///
/// The fresh index is `max(variable indices occurring in gens and f) + 1`, so it cannot
/// collide with anything the caller is using.
///
/// Uses [`GroebnerBudget::default`]; see [`saturate_with_budget`].
pub fn saturate<R: Field>(
    gens: Vec<MultivariatePolynomial<R>>,
    f: &MultivariatePolynomial<R>,
) -> Result<Vec<MultivariatePolynomial<R>>, String> {
    saturate_with_budget(gens, f, &GroebnerBudget::default())
}

/// [`saturate`] with an explicit resource budget.
pub fn saturate_with_budget<R: Field>(
    gens: Vec<MultivariatePolynomial<R>>,
    f: &MultivariatePolynomial<R>,
    budget: &GroebnerBudget,
) -> Result<Vec<MultivariatePolynomial<R>>, String> {
    let gens: Vec<_> = gens.into_iter().filter(|p| !p.is_zero()).collect();
    if gens.is_empty() {
        // (0) : f^∞ = (0) whenever f ≠ 0, since k[x] is a domain; and (0) : 0^∞ = (1).
        if f.is_zero() {
            return Ok(vec![MultivariatePolynomial::constant(R::one())]);
        }
        return Ok(vec![]);
    }

    let mut all = gens.clone();
    all.push(f.clone());
    let t = fresh_variable(&all);

    // t·f − 1
    let t_poly: MultivariatePolynomial<R> = MultivariatePolynomial::variable(t);
    let rabinowitsch = t_poly * f.clone() - MultivariatePolynomial::constant(R::one());

    let mut augmented = gens;
    augmented.push(rabinowitsch);

    eliminate_with_budget(augmented, &[t], budget)
}

/// The intersection `I ∩ J`.
///
/// `I ∩ J = ( t·I + (1−t)·J ) ∩ k[x]` for a fresh variable `t`: an element of the
/// left-hand ideal that is free of `t` must lie in `I` (set `t = 1`) and in `J`
/// (set `t = 0`), and conversely every element of `I ∩ J` is `t·h + (1−t)·h`.
///
/// This is genuinely different from the product `I·J`: for `I = J = (x)` the
/// intersection is `(x)` while the product is `(x²)`.
///
/// Uses [`GroebnerBudget::default`]; see [`ideal_intersection_with_budget`].
pub fn ideal_intersection<R: Field>(
    i: Vec<MultivariatePolynomial<R>>,
    j: Vec<MultivariatePolynomial<R>>,
) -> Result<Vec<MultivariatePolynomial<R>>, String> {
    ideal_intersection_with_budget(i, j, &GroebnerBudget::default())
}

/// [`ideal_intersection`] with an explicit resource budget.
pub fn ideal_intersection_with_budget<R: Field>(
    i: Vec<MultivariatePolynomial<R>>,
    j: Vec<MultivariatePolynomial<R>>,
    budget: &GroebnerBudget,
) -> Result<Vec<MultivariatePolynomial<R>>, String> {
    let i: Vec<_> = i.into_iter().filter(|p| !p.is_zero()).collect();
    let j: Vec<_> = j.into_iter().filter(|p| !p.is_zero()).collect();

    // (0) ∩ J = (0)
    if i.is_empty() || j.is_empty() {
        return Ok(vec![]);
    }

    let mut all = i.clone();
    all.extend(j.clone());
    let t = fresh_variable(&all);

    let t_poly: MultivariatePolynomial<R> = MultivariatePolynomial::variable(t);
    let one_minus_t: MultivariatePolynomial<R> =
        MultivariatePolynomial::constant(R::one()) - t_poly.clone();

    let mut augmented: Vec<MultivariatePolynomial<R>> = Vec::new();
    for g in &i {
        augmented.push(t_poly.clone() * g.clone());
    }
    for h in &j {
        augmented.push(one_minus_t.clone() * h.clone());
    }

    eliminate_with_budget(augmented, &[t], budget)
}

/// Exact division `p / g`, erroring if the division leaves a remainder.
///
/// Used by [`ideal_quotient`], where a non-exact division would mean the intersection
/// step produced something that is not a multiple of `g` — an internal bug, never
/// something to round away.
pub fn exact_divide<R: Field>(
    p: &MultivariatePolynomial<R>,
    g: &MultivariatePolynomial<R>,
) -> Result<MultivariatePolynomial<R>, String> {
    let cmp = crate::groebner::comparison_fn(MonomialOrdering::Grevlex);

    let Some((g_lm, g_lc)) = g.leading_term(cmp) else {
        return Err("exact_divide: division by the zero polynomial".to_string());
    };
    let g_lc_inv = g_lc
        .inverse()
        .map_err(|e| format!("exact_divide: {} is not invertible: {:?}", g_lc, e))?;

    let mut rem = p.clone();
    let mut quot = MultivariatePolynomial::zero();

    while !rem.is_zero() {
        let (r_lm, r_lc) = rem
            .leading_term(cmp)
            .expect("non-zero polynomial has a leading term");

        let Some(q) = r_lm.div(&g_lm) else {
            return Err(format!(
                "exact_divide: {} does not divide {} exactly (leftover leading monomial {})",
                g, p, r_lm
            ));
        };

        let c = r_lc * g_lc_inv.clone();
        quot.add_term(q.clone(), c.clone());
        rem = rem - g.monomial_mul(&q, &c);
    }

    Ok(quot)
}

/// The ideal quotient (colon ideal) `I : J = { f : f·J ⊆ I }`.
///
/// Computed from two standard identities:
/// - `I : J = ⋂_k (I : g_k)` over generators `g_k` of `J`;
/// - `I : g = (1/g) · (I ∩ (g))` — intersect with the principal ideal `(g)`, then divide
///   every generator by `g`. Each such division is exact; if one ever leaves a remainder
///   that is a bug and we return `Err` instead of rounding.
///
/// Uses [`GroebnerBudget::default`]; see [`ideal_quotient_with_budget`].
pub fn ideal_quotient<R: Field>(
    i: Vec<MultivariatePolynomial<R>>,
    j: Vec<MultivariatePolynomial<R>>,
) -> Result<Vec<MultivariatePolynomial<R>>, String> {
    ideal_quotient_with_budget(i, j, &GroebnerBudget::default())
}

/// [`ideal_quotient`] with an explicit resource budget.
pub fn ideal_quotient_with_budget<R: Field>(
    i: Vec<MultivariatePolynomial<R>>,
    j: Vec<MultivariatePolynomial<R>>,
    budget: &GroebnerBudget,
) -> Result<Vec<MultivariatePolynomial<R>>, String> {
    let i: Vec<_> = i.into_iter().filter(|p| !p.is_zero()).collect();
    let j: Vec<_> = j.into_iter().filter(|p| !p.is_zero()).collect();

    // I : (0) = the whole ring, since f·0 = 0 ∈ I for every f.
    if j.is_empty() {
        return Ok(vec![MultivariatePolynomial::constant(R::one())]);
    }
    // (0) : J = the annihilator of J, which is (0) in a domain (J ≠ 0 here).
    if i.is_empty() {
        return Ok(vec![]);
    }

    let mut accumulated: Option<Vec<MultivariatePolynomial<R>>> = None;

    for g in &j {
        let inter = ideal_intersection_with_budget(i.clone(), vec![g.clone()], budget)?;

        let mut colon = Vec::with_capacity(inter.len());
        for p in &inter {
            colon.push(exact_divide(p, g)?);
        }

        accumulated = Some(match accumulated {
            None => colon,
            Some(prev) => ideal_intersection_with_budget(prev, colon, budget)?,
        });
    }

    let result = accumulated.expect("j is non-empty");
    if result.is_empty() {
        return Ok(vec![]);
    }
    reduced_groebner_basis_field(result, MonomialOrdering::Grevlex, budget)
}

/// The Krull dimension of `k[x_0,…,x_{num_vars-1}] / I`.
///
/// # Algorithm
///
/// `dim k[x]/I = dim k[x]/LT(I)` (the leading-term ideal has the same Hilbert function),
/// and for a *monomial* ideal `M` the dimension is the size of a largest subset `U` of
/// the variables with `M ∩ k[U] = (0)` — equivalently, no leading monomial of a Gröbner
/// basis has all of its variables inside `U`. So this is a finite combinatorial search
/// over the leading monomials: find a maximal *independent set* of variables.
///
/// # Convention
///
/// - the zero ideal in `n` variables has dimension `n`;
/// - a point has dimension `0`;
/// - the **unit ideal** has dimension `-1` (the empty variety). This falls out of the
///   algorithm rather than being special-cased: `1` is a leading monomial with empty
///   support, and the empty support is contained in every `U` — including `U = ∅` — so
///   no set of variables is independent and the maximum is taken over nothing.
pub fn krull_dimension<R: Field>(
    gens: Vec<MultivariatePolynomial<R>>,
    num_vars: usize,
    budget: &GroebnerBudget,
) -> Result<isize, String> {
    if num_vars > 16 {
        return Err(format!(
            "krull_dimension: the maximal-independent-set search is exponential; \
             refusing {} variables (limit 16)",
            num_vars
        ));
    }

    for p in &gens {
        if let Some(m) = p.max_variable() {
            if m >= num_vars {
                return Err(format!(
                    "krull_dimension: generator uses variable x{} but num_vars = {}",
                    m, num_vars
                ));
            }
        }
    }

    let cmp = crate::groebner::comparison_fn(MonomialOrdering::Grevlex);
    let gb = groebner_basis_field(gens, MonomialOrdering::Grevlex, budget)?;

    // The zero ideal: every subset of the variables is independent.
    if gb.is_empty() {
        return Ok(num_vars as isize);
    }

    // Support bitmask of each leading monomial.
    let supports: Vec<u32> = gb
        .iter()
        .filter_map(|g| g.leading_monomial(cmp))
        .map(|m| {
            let mut mask = 0u32;
            for v in m.variables() {
                mask |= 1u32 << v;
            }
            mask
        })
        .collect();

    let mut best: isize = -1;
    for u in 0u32..(1u32 << num_vars) {
        // U is independent iff no leading monomial has support ⊆ U.
        let independent = supports.iter().all(|s| (s & !u) != 0);
        if independent {
            best = best.max(u.count_ones() as isize);
        }
    }

    Ok(best)
}

/// The univariate squarefree part of a polynomial that involves a single variable.
///
/// `f / gcd(f, f')`, computed by the Euclidean algorithm on the dense coefficient
/// vector. Over a field of characteristic zero this is exactly the radical generator of
/// the principal ideal `(f)`.
///
/// Errors when `f` involves more than one variable: multivariate squarefree parts need a
/// multivariate GCD, which this crate does not have.
pub fn univariate_squarefree_part<R: Field>(
    f: &MultivariatePolynomial<R>,
) -> Result<MultivariatePolynomial<R>, String> {
    let vars = f.variables();
    if vars.len() > 1 {
        return Err(format!(
            "univariate_squarefree_part: {} involves {} variables; a multivariate \
             squarefree part needs multivariate GCD, which is not implemented",
            f,
            vars.len()
        ));
    }
    if f.is_zero() {
        return Ok(MultivariatePolynomial::zero());
    }
    if vars.is_empty() {
        // A non-zero constant generates the unit ideal.
        return Ok(MultivariatePolynomial::constant(R::one()));
    }

    let var = vars[0];
    let deg = f.degree_in(var).unwrap_or(0) as usize;

    let mut coeffs: Vec<R> = vec![R::zero(); deg + 1];
    for (m, c) in f.terms() {
        coeffs[m.exponent(var) as usize] = c.clone();
    }

    let derivative = poly_derivative(&coeffs);
    let g = poly_gcd(&coeffs, &derivative)?;
    let (quot, rem) = poly_div_rem(&coeffs, &g)?;
    if !rem.iter().all(|c| c.is_zero()) {
        return Err("univariate_squarefree_part: f / gcd(f, f') was not exact".to_string());
    }

    let mut result = MultivariatePolynomial::zero();
    for (i, c) in quot.iter().enumerate() {
        if !c.is_zero() {
            result.add_term(Monomial::variable(var, i as u32), c.clone());
        }
    }
    Ok(result)
}

fn poly_trim<R: Field>(c: &[R]) -> Vec<R> {
    let mut v = c.to_vec();
    while v.last().map(|x| x.is_zero()).unwrap_or(false) {
        v.pop();
    }
    v
}

fn poly_derivative<R: Field>(c: &[R]) -> Vec<R> {
    let mut d = Vec::new();
    for (i, coeff) in c.iter().enumerate().skip(1) {
        let mut n = R::zero();
        for _ in 0..i {
            n = n + R::one();
        }
        d.push(coeff.clone() * n);
    }
    poly_trim(&d)
}

fn poly_div_rem<R: Field>(a: &[R], b: &[R]) -> Result<(Vec<R>, Vec<R>), String> {
    let b = poly_trim(b);
    if b.is_empty() {
        return Err("poly_div_rem: division by zero polynomial".to_string());
    }
    let mut rem = poly_trim(a);
    let bl = b.len() - 1;
    let b_lead_inv = b[bl]
        .inverse()
        .map_err(|e| format!("poly_div_rem: leading coefficient not invertible: {:?}", e))?;

    if rem.len() < b.len() {
        return Ok((vec![], rem));
    }

    let mut quot = vec![R::zero(); rem.len() - bl];
    while rem.len() >= b.len() && !rem.is_empty() {
        let rl = rem.len() - 1;
        let factor = rem[rl].clone() * b_lead_inv.clone();
        let shift = rl - bl;
        quot[shift] = factor.clone();
        for (i, bi) in b.iter().enumerate() {
            rem[shift + i] = rem[shift + i].clone() - factor.clone() * bi.clone();
        }
        rem = poly_trim(&rem);
    }

    Ok((quot, rem))
}

fn poly_gcd<R: Field>(a: &[R], b: &[R]) -> Result<Vec<R>, String> {
    let mut x = poly_trim(a);
    let mut y = poly_trim(b);
    while !y.is_empty() {
        let (_, r) = poly_div_rem(&x, &y)?;
        x = y;
        y = poly_trim(&r);
    }
    if x.is_empty() {
        return Ok(vec![]);
    }
    // Normalize to monic.
    let lead_inv = x[x.len() - 1]
        .inverse()
        .map_err(|e| format!("poly_gcd: leading coefficient not invertible: {:?}", e))?;
    Ok(x.iter().map(|c| c.clone() * lead_inv.clone()).collect())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::groebner::{ideal_membership_field, MonomialOrdering};
    use crate::multivariate::{Monomial, MultivariatePolynomial};
    use rustmath_integers::Integer;
    use rustmath_rationals::Rational;

    type P = MultivariatePolynomial<Rational>;

    fn q(n: i64) -> Rational {
        Rational::from_integer(Integer::from(n))
    }

    /// c · x_v^e
    fn term(c: i64, powers: &[(usize, u32)]) -> P {
        let mut m = Monomial::new();
        for (v, e) in powers {
            m = m.mul(&Monomial::variable(*v, *e));
        }
        let mut p = P::zero();
        p.add_term(m, q(c));
        p
    }

    fn var(v: usize) -> P {
        term(1, &[(v, 1)])
    }

    fn con(c: i64) -> P {
        term(c, &[])
    }

    /// Ideal equality by mutual membership — the only honest way to compare ideals,
    /// since a Gröbner basis is canonical only after reduction.
    fn same_ideal(a: &[P], b: &[P]) -> bool {
        let budget = GroebnerBudget::generous();
        let a_in_b = a.iter().all(|p| {
            ideal_membership_field(p, b, MonomialOrdering::Grevlex, &budget).unwrap_or(false)
        });
        let b_in_a = b.iter().all(|p| {
            ideal_membership_field(p, a, MonomialOrdering::Grevlex, &budget).unwrap_or(false)
        });
        a_in_b && b_in_a
    }

    // ---------------------------------------------------------------------
    // Part A: pin down what the monomial orders actually do, before relying on them.
    // ---------------------------------------------------------------------

    #[test]
    fn cmp_lex_makes_variable_zero_the_largest() {
        // x0 vs x1: lex walks indices ascending and returns on the first difference,
        // so x0 (exponent 1 at index 0) beats x1 (exponent 0 at index 0).
        let x0 = Monomial::variable(0, 1);
        let x1 = Monomial::variable(1, 1);
        assert_eq!(x0.cmp_lex(&x1), std::cmp::Ordering::Greater);

        // And it is a *lexicographic* order, not a graded one: x0 beats x1^5.
        let x1_5 = Monomial::variable(1, 5);
        assert_eq!(x0.cmp_lex(&x1_5), std::cmp::Ordering::Greater);

        // Textbook example: x^2 y > x y^2 under lex with x = x0, y = x1.
        let x2y = Monomial::variable(0, 2).mul(&Monomial::variable(1, 1));
        let xy2 = Monomial::variable(0, 1).mul(&Monomial::variable(1, 2));
        assert_eq!(x2y.cmp_lex(&xy2), std::cmp::Ordering::Greater);
    }

    #[test]
    fn elimination_order_has_the_elimination_property() {
        // block = 1, so x0 is the variable being eliminated.
        let block = 1;

        // Any monomial touching x0 outranks any monomial that does not, regardless of degree.
        let x0 = Monomial::variable(0, 1);
        let x1_big = Monomial::variable(1, 9).mul(&Monomial::variable(2, 9));
        assert_eq!(x0.cmp_elimination(&x1_big, block), std::cmp::Ordering::Greater);

        // More block degree still wins.
        let x0_sq = Monomial::variable(0, 2);
        assert_eq!(x0_sq.cmp_elimination(&x0, block), std::cmp::Ordering::Greater);

        // Equal block degree falls back to grevlex.
        let a = Monomial::variable(0, 1).mul(&Monomial::variable(1, 2));
        let b = Monomial::variable(0, 1).mul(&Monomial::variable(2, 2));
        assert_eq!(
            a.cmp_elimination(&b, block),
            a.cmp_grevlex(&b),
            "ties within a block should be broken by grevlex"
        );

        // 1 is minimal.
        let one = Monomial::new();
        assert_eq!(one.cmp_elimination(&x0, block), std::cmp::Ordering::Less);
        assert_eq!(one.cmp_elimination(&x1_big, block), std::cmp::Ordering::Less);
    }

    #[test]
    fn relabel_is_injective_and_invertible() {
        // x0^2 * x3
        let p = term(1, &[(0, 2), (3, 1)]);
        let fwd = p.relabel(|v| v + 10).unwrap();
        assert_eq!(fwd.variables(), vec![10, 13]);
        let back = fwd.relabel(|v| v - 10).unwrap();
        assert_eq!(back, p);

        // A non-injective map must be reported, not silently merge exponents.
        assert!(p.relabel(|_| 0).is_err());
    }

    // ---------------------------------------------------------------------
    // Part B: elimination
    // ---------------------------------------------------------------------

    #[test]
    fn eliminate_recovers_the_twisted_cubic() {
        // Variables: t = 0, x = 1, y = 2, z = 3.
        // I = (x - t, y - t^2, z - t^3); eliminate t.
        // sympy (lex t > x > y > z) gives the t-free elements
        //   x^2 - y, x*y - z, x*z - y^2, y^3 - z^2
        // which generate the twisted cubic ideal (y - x^2, z - x^3).
        let gens = vec![
            var(1) - var(0),
            var(2) - term(1, &[(0, 2)]),
            var(3) - term(1, &[(0, 3)]),
        ];

        let elim = eliminate(gens, &[0]).unwrap();

        assert!(!elim.is_empty(), "elimination ideal must not be empty");
        for p in &elim {
            assert!(
                !p.variables().contains(&0),
                "eliminated variable t leaked into {}",
                p
            );
        }

        // Independently-derived expected ideal (from sympy): (x^2 - y, x*y - z).
        let expected = vec![
            term(1, &[(1, 2)]) - var(2), // x^2 - y
            var(1) * var(2) - var(3),    // x*y - z
        ];
        assert!(
            same_ideal(&elim, &expected),
            "elimination ideal {:?} != twisted cubic ideal",
            elim.iter().map(|p| p.to_string()).collect::<Vec<_>>()
        );

        // And the extra sympy generators really are in it.
        let budget = GroebnerBudget::generous();
        let xz_minus_y2 = var(1) * var(3) - term(1, &[(2, 2)]);
        let y3_minus_z2 = term(1, &[(2, 3)]) - term(1, &[(3, 2)]);
        assert!(
            ideal_membership_field(&xz_minus_y2, &elim, MonomialOrdering::Grevlex, &budget).unwrap()
        );
        assert!(
            ideal_membership_field(&y3_minus_z2, &elim, MonomialOrdering::Grevlex, &budget).unwrap()
        );
    }

    #[test]
    fn eliminate_leaves_a_non_monic_system_alone() {
        // The old R: Ring Buchberger drops leading coefficients; make sure the field
        // engine handles a system whose leading coefficients are not 1.
        // I = (2x - 2t, 3y - 3t^2) with t = 0, x = 1, y = 2  ->  eliminate t  ->  (x^2 - y)
        let gens = vec![
            var(1).scalar_mul(&q(2)) - var(0).scalar_mul(&q(2)),
            var(2).scalar_mul(&q(3)) - term(3, &[(0, 2)]),
        ];
        let elim = eliminate(gens, &[0]).unwrap();
        let expected = vec![term(1, &[(1, 2)]) - var(2)];
        assert!(same_ideal(&elim, &expected), "got {:?}", elim.iter().map(|p| p.to_string()).collect::<Vec<_>>());
    }

    // ---------------------------------------------------------------------
    // Part B: saturation
    // ---------------------------------------------------------------------

    #[test]
    fn saturation_uses_a_genuinely_fresh_variable() {
        // x = 0, y = 1, z = 2 all occur, so the fresh index must be 3.
        let gens = vec![var(0) * var(1), var(0) * var(2)];
        let f = var(0);
        let mut all = gens.clone();
        all.push(f.clone());
        assert_eq!(fresh_variable(&all), 3);
        for p in &all {
            assert!(!p.variables().contains(&3), "index 3 was not fresh");
        }

        // Sparse indices: only x5 is used, so fresh must be 6 (not 1).
        let sparse = vec![var(5)];
        assert_eq!(fresh_variable(&sparse), 6);

        // No variables at all: fresh is 0.
        let constant_only: Vec<P> = vec![con(7)];
        assert_eq!(fresh_variable(&constant_only), 0);
    }

    #[test]
    fn saturate_removes_the_component_inside_v_of_f() {
        // sympy: groebner([x*y, x*z, t*x - 1], t, x, y, z, order='lex')
        //        = [t*x - 1, y, z]  ->  t-free part is (y, z).
        // (x*y, x*z) : x^inf = (y, z)
        let gens = vec![var(0) * var(1), var(0) * var(2)];
        let sat = saturate(gens, &var(0)).unwrap();

        for p in &sat {
            assert!(!p.variables().contains(&3), "fresh t leaked into {}", p);
        }

        let expected = vec![var(1), var(2)];
        assert!(
            same_ideal(&sat, &expected),
            "got {:?}, expected (y, z)",
            sat.iter().map(|p| p.to_string()).collect::<Vec<_>>()
        );
    }

    #[test]
    fn saturate_can_return_the_unit_ideal() {
        // sympy: groebner([x**2, x*y, t*x - 1], t, x, y, order='lex') = [1]
        // V(x^2, xy) = V(x) sits entirely inside V(x), so saturating by x kills it all.
        let gens = vec![term(1, &[(0, 2)]), var(0) * var(1)];
        let sat = saturate(gens, &var(0)).unwrap();

        let one = vec![con(1)];
        assert!(
            same_ideal(&sat, &one),
            "expected the unit ideal, got {:?}",
            sat.iter().map(|p| p.to_string()).collect::<Vec<_>>()
        );
    }

    // ---------------------------------------------------------------------
    // Part B: intersection — must distinguish I ∩ J from I · J
    // ---------------------------------------------------------------------

    #[test]
    fn intersection_of_x_with_itself_is_x_not_x_squared() {
        // This is the test that separates a real intersection from `product`.
        // I = J = (x):  I ∩ J = (x),  but  I · J = (x^2).
        let i = vec![var(0)];
        let j = vec![var(0)];

        let inter = ideal_intersection(i, j).unwrap();

        let x = vec![var(0)];
        let x_squared = vec![term(1, &[(0, 2)])];

        assert!(
            same_ideal(&inter, &x),
            "I ∩ I should be (x), got {:?}",
            inter.iter().map(|p| p.to_string()).collect::<Vec<_>>()
        );
        assert!(
            !same_ideal(&inter, &x_squared),
            "I ∩ I must NOT be the product (x^2) — that would still be the facade"
        );

        // And x itself is in the intersection, while it is not in the product.
        let budget = GroebnerBudget::generous();
        assert!(ideal_membership_field(&var(0), &inter, MonomialOrdering::Grevlex, &budget).unwrap());
        assert!(
            !ideal_membership_field(&var(0), &x_squared, MonomialOrdering::Grevlex, &budget).unwrap()
        );
    }

    #[test]
    fn intersection_of_coprime_principal_ideals_is_the_product() {
        // (x) ∩ (y) = (x*y) — sympy confirms the t-free part is [x*y].
        let inter = ideal_intersection(vec![var(0)], vec![var(1)]).unwrap();
        let expected = vec![var(0) * var(1)];
        assert!(same_ideal(&inter, &expected));
    }

    #[test]
    fn intersection_of_two_maximal_ideals() {
        // sympy: (x, y) ∩ (x, z) = (x, y*z)
        // x = 0, y = 1, z = 2
        let i = vec![var(0), var(1)];
        let j = vec![var(0), var(2)];
        let inter = ideal_intersection(i.clone(), j.clone()).unwrap();

        let expected = vec![var(0), var(1) * var(2)];
        assert!(
            same_ideal(&inter, &expected),
            "expected (x, y*z), got {:?}",
            inter.iter().map(|p| p.to_string()).collect::<Vec<_>>()
        );

        // Sanity: the product (x^2, xz, xy, yz) is strictly smaller — x is not in it.
        let mut product = Vec::new();
        for a in &i {
            for b in &j {
                product.push(a.clone() * b.clone());
            }
        }
        let budget = GroebnerBudget::generous();
        assert!(
            !ideal_membership_field(&var(0), &product, MonomialOrdering::Grevlex, &budget).unwrap(),
            "x should not be in I·J"
        );
        assert!(
            ideal_membership_field(&var(0), &inter, MonomialOrdering::Grevlex, &budget).unwrap(),
            "x must be in I ∩ J"
        );
    }

    // ---------------------------------------------------------------------
    // Part B: ideal quotient
    // ---------------------------------------------------------------------

    #[test]
    fn quotient_of_x_squared_xy_by_x() {
        // sympy: (x^2, x*y) ∩ (x) = (x^2, x*y), and dividing by x gives (x, y).
        let i = vec![term(1, &[(0, 2)]), var(0) * var(1)];
        let j = vec![var(0)];

        let quot = ideal_quotient(i, j).unwrap();
        let expected = vec![var(0), var(1)];

        assert!(
            same_ideal(&quot, &expected),
            "expected (x, y), got {:?}",
            quot.iter().map(|p| p.to_string()).collect::<Vec<_>>()
        );
    }

    #[test]
    fn quotient_by_a_non_divisor_is_the_ideal_itself() {
        // (x) : (y) = (x), since y is a non-zerodivisor mod (x).
        let quot = ideal_quotient(vec![var(0)], vec![var(1)]).unwrap();
        assert!(same_ideal(&quot, &vec![var(0)]));
    }

    #[test]
    fn exact_divide_refuses_an_inexact_division() {
        // x^2 + 1 is not divisible by x.
        let p = term(1, &[(0, 2)]) + con(1);
        let err = exact_divide(&p, &var(0)).unwrap_err();
        assert!(err.contains("does not divide"), "unexpected error: {}", err);

        // But x^2 is.
        let ok = exact_divide(&term(1, &[(0, 2)]), &var(0)).unwrap();
        assert_eq!(ok, var(0));
    }

    // ---------------------------------------------------------------------
    // Krull dimension gates
    // ---------------------------------------------------------------------

    #[test]
    fn krull_dimension_gates() {
        let b = GroebnerBudget::generous();

        // dim k[x,y]/(x) = 1
        assert_eq!(krull_dimension(vec![var(0)], 2, &b).unwrap(), 1);

        // a point (x, y) in the plane has dimension 0
        assert_eq!(krull_dimension(vec![var(0), var(1)], 2, &b).unwrap(), 0);

        // the whole ring k[x,y,z], i.e. the zero ideal, has dimension 3
        assert_eq!(krull_dimension(Vec::<P>::new(), 3, &b).unwrap(), 3);

        // the unit ideal is the empty variety: dimension -1 by our convention
        assert_eq!(krull_dimension(vec![con(1)], 3, &b).unwrap(), -1);

        // the twisted cubic (y - x^2, z - x^3) is a curve: dimension 1
        // x = 0, y = 1, z = 2
        let tc = vec![
            var(1) - term(1, &[(0, 2)]),
            var(2) - term(1, &[(0, 3)]),
        ];
        assert_eq!(krull_dimension(tc, 3, &b).unwrap(), 1);

        // a plane conic in k[x,y]: dimension 1
        let circle = vec![term(1, &[(0, 2)]) + term(1, &[(1, 2)]) - con(1)];
        assert_eq!(krull_dimension(circle, 2, &b).unwrap(), 1);

        // a hypersurface in 3-space has dimension 2
        let surface = vec![term(1, &[(0, 2)]) + term(1, &[(1, 2)]) + term(1, &[(2, 2)]) - con(1)];
        assert_eq!(krull_dimension(surface, 3, &b).unwrap(), 2);

        // zero-dimensional: (x^2 - 1, y^2 - 1) is 4 points
        let four_points = vec![
            term(1, &[(0, 2)]) - con(1),
            term(1, &[(1, 2)]) - con(1),
        ];
        assert_eq!(krull_dimension(four_points, 2, &b).unwrap(), 0);
    }

    #[test]
    fn krull_dimension_refuses_too_many_variables() {
        let b = GroebnerBudget::generous();
        let err = krull_dimension(vec![var(0)], 17, &b).unwrap_err();
        assert!(err.contains("limit 16"), "unexpected error: {}", err);
    }

    // ---------------------------------------------------------------------
    // Squarefree part (used by the radical)
    // ---------------------------------------------------------------------

    #[test]
    fn univariate_squarefree_part_works() {
        // (x - 1)^2 * (x + 1) = x^3 - x^2 - x + 1  ->  squarefree part (x-1)(x+1) = x^2 - 1
        let f = term(1, &[(0, 3)]) - term(1, &[(0, 2)]) - var(0) + con(1);
        let sf = univariate_squarefree_part(&f).unwrap();
        let expected = term(1, &[(0, 2)]) - con(1);
        assert_eq!(sf, expected, "got {}", sf);

        // Already squarefree: x^2 - 1 stays x^2 - 1.
        let g = term(1, &[(0, 2)]) - con(1);
        assert_eq!(univariate_squarefree_part(&g).unwrap(), g);

        // x^3 -> x
        let h = term(1, &[(0, 3)]);
        assert_eq!(univariate_squarefree_part(&h).unwrap(), var(0));

        // Multivariate is an honest refusal, not a wrong answer.
        let multi = var(0) * var(1);
        assert!(univariate_squarefree_part(&multi).is_err());
    }

    // ---------------------------------------------------------------------
    // Part D: the budget must actually fire
    // ---------------------------------------------------------------------

    #[test]
    fn budget_trips_on_cyclic_6_instead_of_hanging() {
        // Cyclic-6 in an elimination order is a classic Buchberger blow-up: the pair
        // count, the degrees and the term counts all stay modest while the *rational
        // coefficients* explode, so the combinatorial limits never fire and the thing
        // just grinds. This is exactly why the budget carries a wall-clock ceiling.
        //
        // Verified by construction: with no time limit this test hung the whole suite
        // (the 900 s harness cap killed the run). It must now come back as an honest Err.
        let gens = cyclic_system(6);
        let budget = GroebnerBudget {
            max_millis: 4_000,
            ..GroebnerBudget::default()
        };

        let start = std::time::Instant::now();
        let result = eliminate_with_budget(gens, &[0], &budget);
        let elapsed = start.elapsed();

        match result {
            Err(e) => {
                assert!(
                    e.contains("budget exceeded"),
                    "expected a budget error, got: {}",
                    e
                );
                // It must give up promptly, not merely eventually.
                assert!(
                    elapsed.as_secs() < 60,
                    "budget fired but took {:?} to do so",
                    elapsed
                );
            }
            Ok(basis) => panic!(
                "cyclic-6 elimination unexpectedly completed within the budget \
                 ({} elements) — the budget test needs a nastier system",
                basis.len()
            ),
        }
    }

    #[test]
    fn tiny_budget_trips_on_an_easy_system() {
        // The same system that succeeds with a generous budget must fail with a tiny one,
        // proving the budget is what stopped it (and not some other error).
        let tc = vec![
            var(1) - term(1, &[(0, 2)]),
            var(2) - term(1, &[(0, 3)]),
        ];

        let ok = eliminate_with_budget(tc.clone(), &[0], &GroebnerBudget::generous());
        assert!(ok.is_ok(), "twisted cubic should succeed with a generous budget");

        let tiny = GroebnerBudget {
            max_pairs: 1,
            ..GroebnerBudget::generous()
        };
        let err = eliminate_with_budget(tc, &[0], &tiny).unwrap_err();
        assert!(
            err.contains("max_pairs"),
            "expected the pair budget to fire, got: {}",
            err
        );
    }

    /// The degree cap must actually fire — on the *input* and on *produced* elements.
    ///
    /// This test used to be `if let Err(e) = err { assert!(...) }`, which passes
    /// unconditionally whenever the computation succeeds. It asserted nothing. A test that
    /// cannot fail is worse than no test.
    #[test]
    fn degree_budget_trips() {
        // ---- (a) the cap applies to the INPUT generators ----------------------------
        // x^8 - 1 has degree 8. Under max_degree = 3 the budget must refuse it *before*
        // running Buchberger; the old code only ever checked polynomials it produced
        // itself, so a caller could hand in a generator that violated the cap and the
        // limit was silently a lie.
        let gens = vec![term(1, &[(0, 8)]) - con(1), var(1) - var(0)];
        let budget = GroebnerBudget {
            max_degree: 3,
            ..GroebnerBudget::generous()
        };
        let result = eliminate_with_budget(gens.clone(), &[0], &budget);
        assert!(
            matches!(result, Err(_)),
            "a degree-8 input generator must trip max_degree = 3, got Ok"
        );
        let e = result.unwrap_err();
        assert!(
            e.contains("max_degree") && e.contains("input generator"),
            "expected the input-generator degree cap to fire, got: {}",
            e
        );

        // The very same system succeeds once the cap admits the input, which proves the
        // Err above came from the budget and not from some unrelated failure.
        let ok = eliminate_with_budget(gens, &[0], &GroebnerBudget::generous());
        assert!(ok.is_ok(), "x^8 - 1, y - x should eliminate fine: {:?}", ok);

        // ---- (b) the cap applies to elements Buchberger PRODUCES ---------------------
        // (x^3 - y, y^3 - x): both inputs have degree 3, so they pass a max_degree = 3
        // check. Eliminating x forces y^9 - y (sympy: groebner([x**3-y, y**3-x], x, y,
        // order='lex') = [x - y**3, y**9 - y]), which is degree 9 and must trip the cap.
        let deep = vec![
            term(1, &[(0, 3)]) - var(1), // x^3 - y
            term(1, &[(1, 3)]) - var(0), // y^3 - x
        ];
        for g in &deep {
            assert_eq!(g.degree(), Some(3), "the inputs must sit exactly at the cap");
        }

        let result = eliminate_with_budget(deep.clone(), &[0], &budget);
        assert!(
            matches!(result, Err(_)),
            "eliminating x from (x^3 - y, y^3 - x) needs degree 9; max_degree = 3 must trip"
        );
        let e = result.unwrap_err();
        assert!(
            e.contains("max_degree") && e.contains("new basis element"),
            "expected the degree cap to fire on a element Buchberger produced, got: {}",
            e
        );

        // And with a generous budget the same elimination succeeds and really does produce
        // the degree-9 generator, so the cap above fired on a genuine need for degree 9.
        let elim = eliminate_with_budget(deep, &[0], &GroebnerBudget::generous()).unwrap();
        let expected = term(1, &[(1, 9)]) - var(1); // y^9 - y
        assert!(
            same_ideal(&elim, &[expected]),
            "expected the elimination ideal (y^9 - y), got {:?}",
            elim.iter().map(|p| p.to_string()).collect::<Vec<_>>()
        );
    }

    /// The cyclic-n benchmark system: the standard Gröbner basis stress test.
    fn cyclic_system(n: usize) -> Vec<P> {
        let mut gens = Vec::new();
        for d in 1..n {
            let mut sum = P::zero();
            for i in 0..n {
                let mut prod = P::zero();
                prod.add_term(Monomial::new(), q(1));
                for k in 0..d {
                    prod = prod * var((i + k) % n);
                }
                sum = sum + prod;
            }
            gens.push(sum);
        }
        let mut prod = P::zero();
        prod.add_term(Monomial::new(), q(1));
        for i in 0..n {
            prod = prod * var(i);
        }
        gens.push(prod - con(1));
        gens
    }
}
