//! Polynomial Ideals
//!
//! This module implements ideals in polynomial rings, which are fundamental
//! objects in commutative algebra and algebraic geometry.
//!
//! An ideal I in a ring R is a subset closed under addition and multiplication
//! by ring elements: if a,b ∈ I and r ∈ R, then a+b ∈ I and ra ∈ I.
//!
//! This module provides:
//! - Generic ideals with arbitrary generators
//! - Principal ideals (generated by a single element)
//! - Benchmark ideal generators (Cyclic, Katsura)
//! - Ideal arithmetic (sum, product, intersection, quotient)
//! - Membership testing using Gröbner bases
//! - Radical and primality checking (basic)
//!
//! # Two Gröbner engines, two caches
//!
//! An [`Ideal`] can be asked for a Gröbner basis by two different engines, and they do not
//! compute the same object:
//!
//! - [`Ideal::get_groebner_basis`] runs the `R: Ring` Buchberger
//!   ([`crate::groebner::groebner_basis`]). It cannot divide coefficients, so its output
//!   is **not reduced** and — for non-monic input over a non-field — not even certified to
//!   be a Gröbner basis. It exists because [`Ideal::reduce`] must work over `Z`.
//! - [`Ideal::reduced_basis`] runs the `R: Field` Buchberger
//!   ([`crate::groebner::reduced_groebner_basis_field`]) and returns the **canonical**
//!   reduced Gröbner basis.
//!
//! These are cached in **separate fields**. They used to share one cache, so whichever
//! engine ran first won it: for `I = (x, x²)` over `Q`, a fresh `reduced_basis()` returned
//! `[x]`, but calling `reduce()` first made `reduced_basis()` return `[x, x²]` — a
//! non-reduced answer from a method whose documented contract is that its output is
//! canonical. `contains`, `is_radical` and `radical` all route through `reduced_basis`, so
//! they could be answered against a basis that was not a reduced Gröbner basis.
//! `ideal_cache_split_reduced_basis_stays_reduced` is the regression test.
//!
//! # Accepted API changes (do not "fix" these back)
//!
//! ## Six methods were narrowed from `R: EuclideanDomain` to `R: Field`
//!
//! [`Ideal::contains`], [`Ideal::intersection`], [`Ideal::quotient_ideal`],
//! [`Ideal::radical`], [`Ideal::is_radical`], [`Ideal::is_prime`] (and
//! [`Ideal::dimension`]) now require `R: Field`. That removes them for `Ideal<Integer>`.
//!
//! This is deliberate. Buchberger's algorithm needs to divide by leading coefficients; the
//! correct theory over `Z` is *strong* Gröbner bases, which this crate does not implement.
//! The old `EuclideanDomain` versions did not implement it either — they were facades that
//! returned a plausible-looking wrong answer:
//!
//! - `Ideal<Integer>::intersection` returned `self.product(other)`. But `I·J ⊆ I∩J` is
//!   strict in general: for `I = J = (x)` the intersection is `(x)` and the product is
//!   `(x²)`.
//! - `Ideal<Integer>::radical` returned `self.clone()`, i.e. it claimed every ideal is
//!   radical. `√(x²) = (x) ≠ (x²)`.
//! - `Ideal<Integer>::quotient_ideal` returned `self.clone()`. `(x²,xy) : (x) = (x,y)`,
//!   which is strictly bigger.
//!
//! Deleting a lying API is not a regression. Nothing in the workspace outside this crate's
//! own tests consumed those methods over a non-field. If you need them over `Z`, the
//! honest path is to implement strong Gröbner bases, not to widen the bound back.
//!
//! ## `MonomialOrdering` gained an `Elimination { block }` variant
//!
//! Additive: a block order with the elimination property, required by
//! [`crate::elimination`]. Any `match` on `MonomialOrdering` that was exhaustive before
//! must now handle it.

use crate::elimination::{
    eliminate_with_budget, ideal_intersection_with_budget, ideal_quotient_with_budget,
    krull_dimension, univariate_squarefree_part,
};
use crate::groebner::{
    comparison_fn, groebner_basis, normal_form, reduced_groebner_basis_field, GroebnerBudget,
    MonomialOrdering,
};
use crate::multivariate::MultivariatePolynomial;
use rustmath_core::{EuclideanDomain, Field, Ring};
use std::fmt;

/// An ideal in a multivariate polynomial ring
///
/// Represented by a set of generators. The ideal consists of all
/// polynomial combinations of these generators.
#[derive(Clone, Debug)]
pub struct Ideal<R: Ring> {
    /// Generators of the ideal
    generators: Vec<MultivariatePolynomial<R>>,
    /// Cache for the `R: Ring` Buchberger engine ([`Ideal::get_groebner_basis`]).
    ///
    /// **Not reduced**, and not canonical. Kept apart from `field_reduced_basis` on
    /// purpose: the two engines compute different objects, and sharing one cache let
    /// whichever ran first answer for the other. See the module documentation.
    ring_basis: Option<Vec<MultivariatePolynomial<R>>>,
    /// Cache for the `R: Field` engine ([`Ideal::reduced_basis`]): the canonical reduced
    /// Gröbner basis.
    field_reduced_basis: Option<Vec<MultivariatePolynomial<R>>>,
    /// Monomial ordering used for Gröbner basis
    ordering: MonomialOrdering,
}

impl<R: Ring> Ideal<R> {
    /// Create a new ideal from generators
    ///
    /// # Examples
    /// ```
    /// use rustmath_polynomials::ideal::Ideal;
    /// use rustmath_polynomials::multivariate::MultivariatePolynomial;
    /// use rustmath_polynomials::groebner::MonomialOrdering;
    /// use rustmath_integers::Integer;
    ///
    /// let p1: MultivariatePolynomial<Integer> = MultivariatePolynomial::zero();
    /// let p2: MultivariatePolynomial<Integer> = MultivariatePolynomial::zero();
    /// let ideal = Ideal::new(vec![p1, p2], MonomialOrdering::Lex);
    /// ```
    pub fn new(generators: Vec<MultivariatePolynomial<R>>, ordering: MonomialOrdering) -> Self {
        Ideal {
            generators: generators.into_iter().filter(|p| !p.is_zero()).collect(),
            ring_basis: None,
            field_reduced_basis: None,
            ordering,
        }
    }

    /// Create the zero ideal {0}
    pub fn zero(ordering: MonomialOrdering) -> Self {
        Ideal::new(vec![], ordering)
    }

    /// Create the unit ideal (entire ring)
    pub fn unit(ordering: MonomialOrdering) -> Self {
        Ideal::new(vec![MultivariatePolynomial::constant(R::one())], ordering)
    }

    /// Create a principal ideal from a single generator
    ///
    /// A principal ideal is generated by a single element: ⟨g⟩ = {fg : f ∈ R[x]}
    ///
    /// # Examples
    /// ```
    /// use rustmath_polynomials::ideal::Ideal;
    /// use rustmath_polynomials::multivariate::MultivariatePolynomial;
    /// use rustmath_polynomials::groebner::MonomialOrdering;
    /// use rustmath_integers::Integer;
    ///
    /// let gen: MultivariatePolynomial<Integer> = MultivariatePolynomial::zero();
    /// let ideal = Ideal::principal(gen, MonomialOrdering::Lex);
    /// assert!(ideal.is_principal());
    /// ```
    pub fn principal(generator: MultivariatePolynomial<R>, ordering: MonomialOrdering) -> Self {
        if generator.is_zero() {
            Ideal::zero(ordering)
        } else {
            Ideal::new(vec![generator], ordering)
        }
    }

    /// Check if this is a principal ideal (single generator)
    pub fn is_principal(&self) -> bool {
        self.generators.len() <= 1
    }

    /// Get the generators of this ideal
    pub fn generators(&self) -> &[MultivariatePolynomial<R>] {
        &self.generators
    }

    /// Get the number of generators
    pub fn num_generators(&self) -> usize {
        self.generators.len()
    }

    /// Check if this is the zero ideal
    pub fn is_zero(&self) -> bool {
        self.generators.is_empty()
    }

    /// Check if this is the unit ideal (entire ring)
    ///
    /// An ideal is the unit ideal if it contains 1 as a generator.
    /// In polynomial rings, ⟨1⟩ is the entire ring.
    pub fn is_unit(&self) -> bool {
        use crate::multivariate::Monomial;
        self.generators.iter().any(|p| {
            p.is_constant() && p.coefficient(&Monomial::new()) == R::one()
        })
    }

    /// Compute or retrieve the `R: Ring` Gröbner basis for this ideal (cached).
    ///
    /// # ⚠ This is NOT the reduced basis
    ///
    /// This runs [`crate::groebner::groebner_basis`], the engine that has no coefficient
    /// division. Its output is not reduced, not canonical, and — for non-monic generators
    /// over a non-field — not certified to be a Gröbner basis at all. It is what
    /// [`Ideal::reduce`] uses, because `QuotientRing` needs to reduce over `Z`.
    ///
    /// For anything that must be canonical (equality of ideals, membership, radical) use
    /// [`Ideal::reduced_basis`], which requires `R: Field` and returns the reduced Gröbner
    /// basis. The two results are cached **separately**; neither can be served from the
    /// other's cache.
    ///
    /// # Panics
    ///
    /// Inherits the panic contract of [`crate::groebner::groebner_basis`]: it panics with
    /// a precise message if the default Gröbner budget trips (which can happen for
    /// non-monic generators over a non-field). It does not hang.
    pub fn get_groebner_basis(&mut self) -> Vec<MultivariatePolynomial<R>>
    where
        R: rustmath_core::EuclideanDomain + Clone,
    {
        if self.ring_basis.is_none() {
            let gb = groebner_basis(self.generators.clone(), self.ordering);
            self.ring_basis = Some(gb);
        }
        self.ring_basis.as_ref().unwrap().clone()
    }

    /// Exact membership test over a field: `p ∈ I` iff `p` has normal form 0.
    ///
    /// Uses the field Gröbner engine, so this is exact — not the degree-comparison
    /// stub that used to live here.
    pub fn contains(&mut self, p: &MultivariatePolynomial<R>) -> Result<bool, String>
    where
        R: Field,
    {
        self.contains_with_budget(p, &GroebnerBudget::default())
    }

    /// [`Ideal::contains`] with an explicit budget.
    pub fn contains_with_budget(
        &mut self,
        p: &MultivariatePolynomial<R>,
        budget: &GroebnerBudget,
    ) -> Result<bool, String>
    where
        R: Field,
    {
        if self.is_zero() {
            return Ok(p.is_zero());
        }
        let gb = self.reduced_basis(budget)?;
        Ok(normal_form(p, &gb, self.ordering)?.is_zero())
    }

    /// Reduce a polynomial modulo this ideal.
    ///
    /// # Honesty note
    ///
    /// The bound here is `EuclideanDomain`, not `Field`, because `QuotientRing` builds
    /// quotients over rings such as `Z` (and `i32`). Over a **field** this is the true
    /// normal form: the leading coefficient of a reducer is always invertible, so every
    /// reducible leading term is cancelled exactly, and the remainder is canonical.
    ///
    /// Over a non-field Euclidean domain a leading term is only reduced when the
    /// reducer's leading coefficient *divides* it exactly; the result is then a valid
    /// remainder (`p − result ∈ I`) but is canonical only when the basis is a *strong*
    /// Gröbner basis, which this crate does not compute. Use [`Ideal::contains`] (field
    /// only) when you need an exact membership decision.
    pub fn reduce(&mut self, p: &MultivariatePolynomial<R>) -> MultivariatePolynomial<R>
    where
        R: EuclideanDomain + Clone,
    {
        if self.is_zero() {
            return p.clone();
        }

        let gb = self.get_groebner_basis();
        Self::reduce_by_basis_static(p, &gb, self.ordering)
    }

    /// Reduce `p` by `basis` over a Euclidean domain.
    ///
    /// Terminates: every iteration either cancels the leading term (strictly lowering the
    /// leading monomial in a well-order) or retires it to the remainder. The previous
    /// version of this function never modified its accumulator and therefore looped
    /// forever whenever `deg(p) >= deg(g)` for some `g`.
    fn reduce_by_basis_static(
        p: &MultivariatePolynomial<R>,
        basis: &[MultivariatePolynomial<R>],
        ordering: MonomialOrdering,
    ) -> MultivariatePolynomial<R>
    where
        R: EuclideanDomain + Clone,
    {
        let cmp = comparison_fn(ordering);

        let reducers: Vec<(&MultivariatePolynomial<R>, crate::multivariate::Monomial, R)> = basis
            .iter()
            .filter_map(|g| g.leading_term(cmp).map(|(lm, lc)| (g, lm, lc)))
            .collect();

        let mut work = p.clone();
        let mut remainder = MultivariatePolynomial::zero();

        while !work.is_zero() {
            let Some((w_lm, w_lc)) = work.leading_term(cmp) else {
                break;
            };

            let mut step = None;
            for (g, g_lm, g_lc) in &reducers {
                if w_lm.div(g_lm).is_none() {
                    continue;
                }
                // Only reduce when the leading coefficient divides exactly.
                let Ok((quot, rem)) = w_lc.div_rem(g_lc) else {
                    continue;
                };
                if !rem.is_zero() {
                    continue;
                }
                let q_mono = w_lm.div(g_lm).expect("divisibility just checked");
                step = Some((*g, q_mono, quot));
                break;
            }

            match step {
                Some((g, q_mono, factor)) => {
                    work = work - g.monomial_mul(&q_mono, &factor);
                }
                None => {
                    remainder.add_term(w_lm.clone(), w_lc.clone());
                    work.add_term(w_lm, -w_lc);
                }
            }
        }

        remainder
    }

    /// Compute the sum of two ideals: I + J = {a + b : a ∈ I, b ∈ J}
    ///
    /// The sum is generated by the union of the generators
    pub fn sum(&self, other: &Ideal<R>) -> Ideal<R> {
        let mut gens = self.generators.clone();
        gens.extend(other.generators.clone());
        Ideal::new(gens, self.ordering)
    }

    /// Compute the product of two ideals: I * J = {Σ aᵢbⱼ : aᵢ ∈ I, bⱼ ∈ J}
    ///
    /// The product is generated by all products of generators
    pub fn product(&self, other: &Ideal<R>) -> Ideal<R>
    where
        R: Clone,
    {
        if self.is_zero() || other.is_zero() {
            return Ideal::zero(self.ordering);
        }

        let mut gens = Vec::new();
        for g1 in &self.generators {
            for g2 in &other.generators {
                gens.push(g1.clone() * g2.clone());
            }
        }
        Ideal::new(gens, self.ordering)
    }

    /// The reduced Gröbner basis of this ideal (cached), over a field.
    ///
    /// This is the canonical generating set: two ideals are equal iff these agree.
    ///
    /// Cached in its own field, disjoint from the `R: Ring` cache used by
    /// [`Ideal::get_groebner_basis`]. Calling [`Ideal::reduce`] first (which populates the
    /// ring cache) therefore cannot make this method hand back a non-reduced basis — which
    /// is exactly what the old shared cache did.
    pub fn reduced_basis(
        &mut self,
        budget: &GroebnerBudget,
    ) -> Result<Vec<MultivariatePolynomial<R>>, String>
    where
        R: Field,
    {
        if self.field_reduced_basis.is_none() {
            let gb = reduced_groebner_basis_field(self.generators.clone(), self.ordering, budget)?;
            self.field_reduced_basis = Some(gb);
        }
        Ok(self.field_reduced_basis.as_ref().unwrap().clone())
    }

    /// The ambient number of variables implied by the generators (largest index + 1).
    pub fn ambient_variables(&self) -> usize {
        self.generators
            .iter()
            .filter_map(|p| p.max_variable())
            .max()
            .map(|m| m + 1)
            .unwrap_or(0)
    }

    /// The intersection of two ideals: `I ∩ J`.
    ///
    /// Computed by elimination: `I ∩ J = ( t·I + (1−t)·J ) ∩ k[x]` for a fresh variable
    /// `t`. This used to return `self.product(other)`, which is wrong — `I·J ⊆ I∩J` with
    /// equality only in special cases. For `I = J = (x)` the intersection is `(x)` while
    /// the product is `(x²)`.
    pub fn intersection(&self, other: &Ideal<R>) -> Result<Ideal<R>, String>
    where
        R: Field,
    {
        self.intersection_with_budget(other, &GroebnerBudget::default())
    }

    /// [`Ideal::intersection`] with an explicit budget.
    pub fn intersection_with_budget(
        &self,
        other: &Ideal<R>,
        budget: &GroebnerBudget,
    ) -> Result<Ideal<R>, String>
    where
        R: Field,
    {
        if self.is_zero() || other.is_zero() {
            return Ok(Ideal::zero(self.ordering));
        }

        let gens = ideal_intersection_with_budget(
            self.generators.clone(),
            other.generators.clone(),
            budget,
        )?;
        Ok(Ideal::new(gens, self.ordering))
    }

    /// The ideal quotient (colon ideal) `I : J = { f : f·J ⊆ I }`.
    ///
    /// Computed as `⋂_k (I : g_k)` with `I : g = (1/g)·(I ∩ (g))`. This used to return
    /// `self.clone()`.
    pub fn quotient_ideal(&self, other: &Ideal<R>) -> Result<Ideal<R>, String>
    where
        R: Field,
    {
        self.quotient_ideal_with_budget(other, &GroebnerBudget::default())
    }

    /// [`Ideal::quotient_ideal`] with an explicit budget.
    pub fn quotient_ideal_with_budget(
        &self,
        other: &Ideal<R>,
        budget: &GroebnerBudget,
    ) -> Result<Ideal<R>, String>
    where
        R: Field,
    {
        let gens =
            ideal_quotient_with_budget(self.generators.clone(), other.generators.clone(), budget)?;
        Ok(Ideal::new(gens, self.ordering))
    }

    /// Is this ideal prime?
    ///
    /// # Honest refusal
    ///
    /// Deciding primality in general needs primary decomposition
    /// (Gianni–Trager–Zacharias), which this crate does not implement. Rather than
    /// return `false` for every ideal — which is the claim "no ideal is prime", a lie —
    /// this decides only the two cases that are decidable without it and returns `Err`
    /// otherwise, naming what is missing.
    pub fn is_prime(&mut self) -> Result<bool, String>
    where
        R: Field,
    {
        if self.is_zero() {
            // k[x_1..x_n] is an integral domain, so (0) is prime.
            return Ok(true);
        }
        if self.is_unit() {
            // The unit ideal is prime by no convention: primes are proper by definition.
            return Ok(false);
        }
        Err(
            "Ideal::is_prime: deciding primality of a proper non-zero ideal requires primary \
             decomposition (Gianni–Trager–Zacharias), which is not implemented"
                .to_string(),
        )
    }

    /// Is this ideal radical, i.e. is `I = √I`?
    ///
    /// Decided by computing the radical and testing `√I ⊆ I` (the reverse inclusion is
    /// automatic). Returns `Err` whenever [`Ideal::radical`] cannot be computed.
    pub fn is_radical(&mut self) -> Result<bool, String>
    where
        R: Field,
    {
        if self.is_zero() || self.is_unit() {
            return Ok(true);
        }

        let rad = self.radical()?;
        for g in rad.generators() {
            if !self.contains(g)? {
                return Ok(false);
            }
        }
        Ok(true)
    }

    /// The radical `√I = { f : f^n ∈ I for some n }`.
    ///
    /// # What is actually implemented
    ///
    /// The signature was changed from `radical(&self) -> Ideal<R>` (which returned
    /// `self.clone()` — a facade) to a `Result`, because the honest answer for a general
    /// ideal is "not implemented". Returning a `Result` rather than making the old
    /// signature panic keeps the failure visible in the type and lets callers handle it.
    ///
    /// Two cases are computed for real:
    ///
    /// - **Principal, one variable**: `√(f) = (squarefree part of f)`, obtained as
    ///   `f / gcd(f, f′)`.
    /// - **Zero-dimensional**: by Seidenberg's lemma, for a zero-dimensional ideal over a
    ///   perfect field, `√I = I + (sqfree(f_1), …, sqfree(f_n))` where `f_i` generates the
    ///   elimination ideal `I ∩ k[x_i]`. Each `f_i` comes from a real elimination.
    ///
    /// Everything else — a positive-dimensional, non-principal ideal — returns `Err`,
    /// naming primary decomposition as the missing piece. It does **not** return `self`.
    pub fn radical(&mut self) -> Result<Ideal<R>, String>
    where
        R: Field,
    {
        self.radical_with_budget(&GroebnerBudget::default())
    }

    /// [`Ideal::radical`] with an explicit budget.
    pub fn radical_with_budget(&mut self, budget: &GroebnerBudget) -> Result<Ideal<R>, String>
    where
        R: Field,
    {
        if self.is_zero() {
            // √(0) = (0) in a reduced ring, and k[x] is a domain.
            return Ok(Ideal::zero(self.ordering));
        }
        if self.is_unit() {
            return Ok(Ideal::unit(self.ordering));
        }

        // Principal ideal in a single variable: the squarefree part.
        if self.generators.len() == 1 && self.generators[0].variables().len() <= 1 {
            let sf = univariate_squarefree_part(&self.generators[0])?;
            return Ok(Ideal::principal(sf, self.ordering));
        }

        let num_vars = self.ambient_variables();
        let dim = krull_dimension(self.generators.clone(), num_vars, budget)?;

        if dim != 0 {
            return Err(format!(
                "Ideal::radical: the ideal has dimension {}; the radical of a \
                 positive-dimensional non-principal ideal needs primary decomposition \
                 (Gianni–Trager–Zacharias), which is not implemented. Only the principal \
                 univariate case and the zero-dimensional case are available.",
                dim
            ));
        }

        // Zero-dimensional: Seidenberg. For each variable, the elimination ideal
        // I ∩ k[x_i] is a non-zero principal ideal; add its squarefree generator.
        let mut gens = self.generators.clone();
        for v in 0..num_vars {
            let others: Vec<usize> = (0..num_vars).filter(|w| *w != v).collect();
            let elim = eliminate_with_budget(self.generators.clone(), &others, budget)?;

            let univariate: Vec<_> = elim.into_iter().filter(|p| !p.is_zero()).collect();
            if univariate.is_empty() {
                return Err(format!(
                    "Ideal::radical: ideal reported dimension 0 but the elimination ideal \
                     in x{} is zero — internal inconsistency",
                    v
                ));
            }

            for f in &univariate {
                gens.push(univariate_squarefree_part(f)?);
            }
        }

        let reduced = reduced_groebner_basis_field(gens, self.ordering, budget)?;
        Ok(Ideal::new(reduced, self.ordering))
    }

    /// The Krull dimension of `k[x_0,…,x_{n-1}]/I`, with `n` inferred from the generators.
    ///
    /// See [`Ideal::dimension_in`] for the convention and the algorithm; use that when the
    /// ambient space is bigger than the variables the generators happen to mention.
    pub fn dimension(&mut self) -> Result<isize, String>
    where
        R: Field,
    {
        let n = self.ambient_variables();
        self.dimension_in(n)
    }

    /// The Krull dimension of `k[x_0,…,x_{num_vars-1}]/I`.
    ///
    /// The maximum size of a subset `U` of the variables such that no leading monomial of
    /// a Gröbner basis of `I` has all of its variables inside `U` (a maximal independent
    /// set). Conventions: the zero ideal in `n` variables has dimension `n`, a point has
    /// dimension `0`, and the unit ideal (the empty variety) has dimension `-1`.
    ///
    /// This replaces a `dimension()` that returned `None` unconditionally.
    pub fn dimension_in(&mut self, num_vars: usize) -> Result<isize, String>
    where
        R: Field,
    {
        krull_dimension(
            self.generators.clone(),
            num_vars,
            &GroebnerBudget::default(),
        )
    }
}

/// Construct the Cyclic n-roots ideal
///
/// The cyclic n-roots problem is a standard benchmark in computational algebra.
/// For n variables x₀, x₁, ..., xₙ₋₁, it is defined by:
/// - cₖ = x₀^k + x₁^k + ... + xₙ₋₁^k for k = 1, ..., n-1
/// - cₙ = x₀ * x₁ * ... * xₙ₋₁ - 1
///
/// # Examples
/// ```
/// use rustmath_polynomials::ideal::cyclic_ideal;
/// use rustmath_polynomials::groebner::MonomialOrdering;
/// use rustmath_integers::Integer;
///
/// // Cyclic-3 ideal
/// let ideal = cyclic_ideal::<Integer>(3, MonomialOrdering::Lex);
/// assert_eq!(ideal.num_generators(), 3);
/// ```
pub fn cyclic_ideal<R: Ring>(n: usize, ordering: MonomialOrdering) -> Ideal<R> {
    if n == 0 {
        return Ideal::zero(ordering);
    }

    let x = |i: usize| MultivariatePolynomial::<R>::variable(i % n);
    let mut generators = Vec::with_capacity(n);

    // c_d = Σ_i  x_i · x_{i+1} · … · x_{i+d-1}   (indices mod n),  d = 1 … n-1
    for d in 1..n {
        let mut sum = MultivariatePolynomial::zero();
        for i in 0..n {
            let mut prod = MultivariatePolynomial::constant(R::one());
            for k in 0..d {
                prod = prod * x(i + k);
            }
            sum = sum + prod;
        }
        generators.push(sum);
    }

    // c_n = x_0 · x_1 · … · x_{n-1} − 1
    let mut prod = MultivariatePolynomial::constant(R::one());
    for i in 0..n {
        prod = prod * x(i);
    }
    generators.push(prod - MultivariatePolynomial::constant(R::one()));

    Ideal::new(generators, ordering)
}

/// Construct the Katsura n ideal
///
/// The Katsura problem is another standard benchmark, arising from
/// magnetism applications. For n variables u₀, u₁, ..., uₙ:
/// - First equation: u₀ + 2(u₁ + u₂ + ... + uₙ) - 1 = 0
/// - Other equations involve products uᵢ * uⱼ
///
/// # Examples
/// ```
/// use rustmath_polynomials::ideal::katsura_ideal;
/// use rustmath_polynomials::groebner::MonomialOrdering;
/// use rustmath_integers::Integer;
///
/// let ideal = katsura_ideal::<Integer>(3, MonomialOrdering::Lex);
/// assert_eq!(ideal.num_generators(), 4);
/// ```
pub fn katsura_ideal<R: Ring>(n: usize, ordering: MonomialOrdering) -> Ideal<R> {
    if n == 0 {
        return Ideal::zero(ordering);
    }

    let ni = n as isize;
    // u_i is indexed by |i|, and is zero for |i| > n.
    let u = |i: isize| -> Option<MultivariatePolynomial<R>> {
        let a = i.unsigned_abs();
        if a <= n {
            Some(MultivariatePolynomial::variable(a))
        } else {
            None
        }
    };
    let two = R::one() + R::one();

    let mut generators = Vec::with_capacity(n + 1);

    // For m = 0 … n-1:   Σ_{i=-n}^{n} u_i · u_{m-i}  −  u_m
    for m in 0..ni {
        let mut sum = MultivariatePolynomial::zero();
        for i in -ni..=ni {
            let (Some(a), Some(b)) = (u(i), u(m - i)) else {
                continue;
            };
            sum = sum + a * b;
        }
        let um = u(m).expect("m < n");
        generators.push(sum - um);
    }

    // The linear relation:  Σ_{i=-n}^{n} u_i − 1  =  u_0 + 2(u_1 + … + u_n) − 1
    let mut lin = MultivariatePolynomial::<R>::variable(0);
    for i in 1..=n {
        lin = lin + MultivariatePolynomial::<R>::variable(i).scalar_mul(&two);
    }
    generators.push(lin - MultivariatePolynomial::constant(R::one()));

    Ideal::new(generators, ordering)
}

/// Check if an object is an Ideal
///
/// This is a type-checking function for compatibility with dynamic typing
pub fn is_ideal<R: Ring>(_obj: &Ideal<R>) -> bool {
    true
}

/// A field ideal is always the entire ring (unit ideal)
///
/// In a field F, every non-zero element is a unit, so every non-zero
/// ideal is the entire ring.
pub struct FieldIdeal<F: Field> {
    _phantom: std::marker::PhantomData<F>,
}

impl<F: Field> FieldIdeal<F> {
    /// Create a field ideal (always the unit ideal)
    pub fn new() -> Self {
        FieldIdeal {
            _phantom: std::marker::PhantomData,
        }
    }

    /// Field ideals are always the unit ideal
    pub fn is_unit() -> bool {
        true
    }
}

impl<R: Ring> fmt::Display for Ideal<R> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.is_zero() {
            write!(f, "⟨0⟩")
        } else if self.is_unit() {
            write!(f, "⟨1⟩")
        } else if self.generators.len() == 1 {
            write!(f, "⟨{}⟩", self.generators[0])
        } else {
            write!(f, "⟨")?;
            for (i, g) in self.generators.iter().enumerate() {
                if i > 0 {
                    write!(f, ", ")?;
                }
                write!(f, "{}", g)?;
            }
            write!(f, "⟩")
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rustmath_integers::Integer;
    use rustmath_rationals::Rational;

    /// The variable x_v over Q.
    fn rx(v: usize) -> MultivariatePolynomial<Rational> {
        MultivariatePolynomial::variable(v)
    }

    /// The constant 1 over Q.
    fn rone() -> MultivariatePolynomial<Rational> {
        MultivariatePolynomial::constant(Rational::from_integer(Integer::from(1)))
    }

    /// The variable x_v over Z.
    fn ix(v: usize) -> MultivariatePolynomial<Integer> {
        MultivariatePolynomial::variable(v)
    }

    #[test]
    fn test_create_zero_ideal() {
        let ideal: Ideal<Integer> = Ideal::zero(MonomialOrdering::Lex);
        assert!(ideal.is_zero());
        assert!(!ideal.is_unit());
        assert_eq!(ideal.num_generators(), 0);
    }

    #[test]
    fn test_create_unit_ideal() {
        let ideal: Ideal<Integer> = Ideal::unit(MonomialOrdering::Lex);
        assert!(ideal.is_unit());
        assert!(!ideal.is_zero());
        assert_eq!(ideal.num_generators(), 1);
    }

    #[test]
    fn test_principal_ideal() {
        let gen = MultivariatePolynomial::constant(Integer::from(5));
        let ideal = Ideal::principal(gen, MonomialOrdering::Lex);
        assert!(ideal.is_principal());
        assert_eq!(ideal.num_generators(), 1);
        assert!(!ideal.is_zero());
        assert!(!ideal.is_unit());
    }

    #[test]
    fn test_principal_ideal_zero() {
        let gen = MultivariatePolynomial::zero();
        let ideal: Ideal<Integer> = Ideal::principal(gen, MonomialOrdering::Lex);
        assert!(ideal.is_zero());
        assert!(ideal.is_principal());
    }

    #[test]
    fn test_ideal_sum() {
        let p1 = MultivariatePolynomial::zero();
        let p2 = MultivariatePolynomial::zero();
        let ideal1: Ideal<Integer> = Ideal::new(vec![p1], MonomialOrdering::Lex);
        let ideal2: Ideal<Integer> = Ideal::new(vec![p2], MonomialOrdering::Lex);

        let sum = ideal1.sum(&ideal2);
        assert!(sum.is_zero());
    }

    #[test]
    fn test_ideal_sum_with_generators() {
        let p1 = MultivariatePolynomial::constant(Integer::from(2));
        let p2 = MultivariatePolynomial::constant(Integer::from(3));
        let ideal1: Ideal<Integer> = Ideal::new(vec![p1], MonomialOrdering::Lex);
        let ideal2: Ideal<Integer> = Ideal::new(vec![p2], MonomialOrdering::Lex);

        let sum = ideal1.sum(&ideal2);
        assert_eq!(sum.num_generators(), 2);
    }

    #[test]
    fn test_ideal_product() {
        let ideal1: Ideal<Integer> = Ideal::unit(MonomialOrdering::Lex);
        let ideal2: Ideal<Integer> = Ideal::zero(MonomialOrdering::Lex);

        let product = ideal1.product(&ideal2);
        assert!(product.is_zero());
    }

    #[test]
    fn test_ideal_product_non_zero() {
        let p1 = MultivariatePolynomial::constant(Integer::from(2));
        let p2 = MultivariatePolynomial::constant(Integer::from(3));
        let ideal1: Ideal<Integer> = Ideal::new(vec![p1], MonomialOrdering::Lex);
        let ideal2: Ideal<Integer> = Ideal::new(vec![p2], MonomialOrdering::Lex);

        let product = ideal1.product(&ideal2);
        assert_eq!(product.num_generators(), 1);
        assert!(!product.is_zero());
    }

    #[test]
    fn test_ideal_intersection() {
        let ideal1: Ideal<Rational> = Ideal::zero(MonomialOrdering::Grevlex);
        let ideal2: Ideal<Rational> = Ideal::unit(MonomialOrdering::Grevlex);

        let intersection = ideal1.intersection(&ideal2).unwrap();
        assert!(intersection.is_zero());
    }

    /// The test that proves `intersection` is no longer `product`.
    ///
    /// I = J = (x). Then I ∩ J = (x) but I · J = (x²). The old facade returned the
    /// product, so it could not tell these apart.
    #[test]
    fn test_intersection_is_not_the_product() {
        let i: Ideal<Rational> = Ideal::principal(rx(0), MonomialOrdering::Grevlex);
        let j: Ideal<Rational> = Ideal::principal(rx(0), MonomialOrdering::Grevlex);

        let mut inter = i.intersection(&j).unwrap();
        let mut prod = i.product(&j);

        // x ∈ I ∩ J
        assert!(
            inter.contains(&rx(0)).unwrap(),
            "x must lie in (x) ∩ (x)"
        );
        // but x ∉ I · J = (x²)
        assert!(
            !prod.contains(&rx(0)).unwrap(),
            "x must NOT lie in (x)·(x) = (x²) — if it does, the product is broken"
        );

        // x² lies in both, so only the x-membership distinguishes them.
        let x_sq = rx(0) * rx(0);
        assert!(inter.contains(&x_sq).unwrap());
        assert!(prod.contains(&x_sq).unwrap());
    }

    #[test]
    fn test_ideal_quotient() {
        let ideal1: Ideal<Rational> = Ideal::unit(MonomialOrdering::Grevlex);
        let ideal2: Ideal<Rational> = Ideal::zero(MonomialOrdering::Grevlex);

        let quotient = ideal1.quotient_ideal(&ideal2).unwrap();
        assert!(quotient.is_unit());
    }

    /// (x², xy) : (x) = (x, y) — verified independently with sympy.
    /// The old facade returned `self`, i.e. (x², xy), which does not contain y.
    #[test]
    fn test_quotient_ideal_is_not_self() {
        let i: Ideal<Rational> = Ideal::new(
            vec![rx(0) * rx(0), rx(0) * rx(1)],
            MonomialOrdering::Grevlex,
        );
        let j: Ideal<Rational> = Ideal::principal(rx(0), MonomialOrdering::Grevlex);

        let mut quot = i.quotient_ideal(&j).unwrap();

        // y ∈ (x², xy) : (x), because y·x = xy ∈ I.
        assert!(
            quot.contains(&rx(1)).unwrap(),
            "y must lie in (x²,xy):(x) — the old facade returned self, which excludes y"
        );
        assert!(quot.contains(&rx(0)).unwrap(), "x must lie in the quotient");

        // And the quotient is strictly bigger than I: y ∉ I.
        let mut i2: Ideal<Rational> = Ideal::new(
            vec![rx(0) * rx(0), rx(0) * rx(1)],
            MonomialOrdering::Grevlex,
        );
        assert!(!i2.contains(&rx(1)).unwrap(), "y should not lie in (x²,xy)");
    }

    #[test]
    fn test_ideal_display() {
        let ideal: Ideal<Integer> = Ideal::zero(MonomialOrdering::Lex);
        let display = format!("{}", ideal);
        assert_eq!(display, "⟨0⟩");

        let ideal_unit: Ideal<Integer> = Ideal::unit(MonomialOrdering::Lex);
        let display_unit = format!("{}", ideal_unit);
        assert_eq!(display_unit, "⟨1⟩");
    }

    /// Cyclic-3 is `x0+x1+x2`, `x0x1+x0x2+x1x2`, `x0x1x2-1` (checked against sympy).
    /// The old placeholder returned three *zero* polynomials, which `Ideal::new` then
    /// filtered away — so the ideal was empty and the doctest asserting 3 generators
    /// had been failing (invisibly, behind an earlier hang).
    #[test]
    fn test_cyclic_ideal() {
        let ideal = cyclic_ideal::<Integer>(3, MonomialOrdering::Lex);
        assert_eq!(ideal.num_generators(), 3);
        assert!(!ideal.is_zero());

        let gens = ideal.generators();

        // c_1 = x0 + x1 + x2 : three linear terms.
        assert_eq!(gens[0].num_terms(), 3);
        assert_eq!(gens[0].degree(), Some(1));

        // c_2 = x0x1 + x0x2 + x1x2 : three quadratic terms.
        assert_eq!(gens[1].num_terms(), 3);
        assert_eq!(gens[1].degree(), Some(2));

        // c_3 = x0x1x2 - 1 : the cubic and the constant.
        assert_eq!(gens[2].num_terms(), 2);
        assert_eq!(gens[2].degree(), Some(3));

        // Every generator of cyclic-3 vanishes at the point (1, ω, ω²) only over C, but
        // over any ring the *sum* c_1 vanishes at (1, -1, 0) and c_2 does not — a cheap
        // check that these are not all the same polynomial.
        let pt = [Integer::from(1), Integer::from(-1), Integer::from(0)];
        assert!(gens[0].evaluate(&pt).is_zero(), "c_1(1,-1,0) = 0");
        assert!(!gens[2].evaluate(&pt).is_zero(), "c_3(1,-1,0) = -1 != 0");
    }

    #[test]
    fn test_cyclic_ideal_zero() {
        let ideal = cyclic_ideal::<Integer>(0, MonomialOrdering::Lex);
        assert!(ideal.is_zero());
    }

    /// Katsura-3, in u0..u3 (checked against sympy / the standard benchmark):
    ///   u0² - u0 + 2u1² + 2u2² + 2u3²
    ///   2u0u1 + 2u1u2 - u1 + 2u2u3
    ///   2u0u2 + u1² + 2u1u3 - u2
    ///   u0 + 2u1 + 2u2 + 2u3 - 1
    #[test]
    fn test_katsura_ideal() {
        let ideal = katsura_ideal::<Integer>(3, MonomialOrdering::Lex);
        assert_eq!(ideal.num_generators(), 4);
        assert!(!ideal.is_zero());

        let gens = ideal.generators();

        // The three quadratic relations.
        for g in gens.iter().take(3) {
            assert_eq!(g.degree(), Some(2));
        }
        // The linear relation u0 + 2u1 + 2u2 + 2u3 - 1.
        assert_eq!(gens[3].degree(), Some(1));
        assert_eq!(gens[3].num_terms(), 5);

        // Katsura's defining solution: all the u_i sum to 1 with u_0 = 1, rest 0.
        // Then the linear relation vanishes and so does every quadratic one:
        //   u0² - u0 = 0, and every cross term contains a zero factor.
        let pt = [
            Integer::from(1),
            Integer::from(0),
            Integer::from(0),
            Integer::from(0),
        ];
        for (i, g) in gens.iter().enumerate() {
            assert!(
                g.evaluate(&pt).is_zero(),
                "katsura-3 generator {} should vanish at (1,0,0,0), got {}",
                i,
                g.evaluate(&pt)
            );
        }
    }

    #[test]
    fn test_katsura_ideal_zero() {
        let ideal = katsura_ideal::<Integer>(0, MonomialOrdering::Lex);
        assert!(ideal.is_zero());
    }

    #[test]
    fn test_is_ideal() {
        let ideal: Ideal<Integer> = Ideal::zero(MonomialOrdering::Lex);
        assert!(is_ideal(&ideal));
    }

    #[test]
    fn test_field_ideal() {
        use rustmath_rationals::Rational;
        let _field_ideal = FieldIdeal::<Rational>::new();
        assert!(FieldIdeal::<Rational>::is_unit());
    }

    #[test]
    fn test_ideal_dimension() {
        // The zero ideal in no variables is the field itself: dimension 0.
        let mut ideal: Ideal<Rational> = Ideal::zero(MonomialOrdering::Grevlex);
        assert_eq!(ideal.dimension().unwrap(), 0);

        // The unit ideal is the empty variety: dimension -1.
        let mut ideal_unit: Ideal<Rational> = Ideal::unit(MonomialOrdering::Grevlex);
        assert_eq!(ideal_unit.dimension().unwrap(), -1);

        // dim k[x,y]/(x) = 1 — needs the ambient count, since (x) only mentions x.
        let mut line: Ideal<Rational> = Ideal::principal(rx(0), MonomialOrdering::Grevlex);
        assert_eq!(line.dimension_in(2).unwrap(), 1);

        // A point in the plane has dimension 0.
        let mut point: Ideal<Rational> =
            Ideal::new(vec![rx(0), rx(1)], MonomialOrdering::Grevlex);
        assert_eq!(point.dimension_in(2).unwrap(), 0);

        // The zero ideal in 3 variables: the whole ring, dimension 3.
        let mut whole: Ideal<Rational> = Ideal::zero(MonomialOrdering::Grevlex);
        assert_eq!(whole.dimension_in(3).unwrap(), 3);
    }

    #[test]
    fn test_ideal_is_prime() {
        // (0) is prime: k[x] is an integral domain. The old code said `false` here.
        let mut ideal: Ideal<Rational> = Ideal::zero(MonomialOrdering::Grevlex);
        assert!(ideal.is_prime().unwrap());

        // The unit ideal is not prime (primes are proper).
        let mut ideal_unit: Ideal<Rational> = Ideal::unit(MonomialOrdering::Grevlex);
        assert!(!ideal_unit.is_prime().unwrap());

        // Anything else is an honest refusal, not a fabricated `false`.
        let mut proper: Ideal<Rational> =
            Ideal::new(vec![rx(0) * rx(1)], MonomialOrdering::Grevlex);
        let err = proper.is_prime().unwrap_err();
        assert!(
            err.contains("primary decomposition"),
            "unexpected error: {}",
            err
        );
    }

    #[test]
    fn test_ideal_is_radical() {
        let mut ideal: Ideal<Rational> = Ideal::zero(MonomialOrdering::Grevlex);
        assert!(ideal.is_radical().unwrap());

        let mut ideal_unit: Ideal<Rational> = Ideal::unit(MonomialOrdering::Grevlex);
        assert!(ideal_unit.is_radical().unwrap());

        // (x²) is not radical: x ∉ (x²) but x² ∈ (x²).
        let mut sq: Ideal<Rational> =
            Ideal::principal(rx(0) * rx(0), MonomialOrdering::Grevlex);
        assert!(!sq.is_radical().unwrap());

        // (x) is radical.
        let mut lin: Ideal<Rational> = Ideal::principal(rx(0), MonomialOrdering::Grevlex);
        assert!(lin.is_radical().unwrap());
    }

    /// The old `radical` returned `self.clone()`. These check it returns the real thing.
    #[test]
    fn test_ideal_radical() {
        let mut ideal: Ideal<Rational> = Ideal::zero(MonomialOrdering::Grevlex);
        let rad = ideal.radical().unwrap();
        assert!(rad.is_zero());

        // √(x²) = (x). The facade would have returned (x²), which does not contain x.
        let mut sq: Ideal<Rational> =
            Ideal::principal(rx(0) * rx(0), MonomialOrdering::Grevlex);
        let mut rad = sq.radical().unwrap();
        assert!(
            rad.contains(&rx(0)).unwrap(),
            "√(x²) must contain x — a facade returning self would not"
        );
        assert!(!sq.contains(&rx(0)).unwrap(), "x is not in (x²) itself");

        // √((x-1)²(x+1)) = (x²-1), from f/gcd(f,f'). sympy: sqfree(x³-x²-x+1) = x²-1.
        let f = rx(0) * rx(0) * rx(0) - rx(0) * rx(0) - rx(0) + rone();
        let mut cube: Ideal<Rational> = Ideal::principal(f, MonomialOrdering::Grevlex);
        let mut rad = cube.radical().unwrap();
        let x2m1 = rx(0) * rx(0) - rone();
        assert!(rad.contains(&x2m1).unwrap());
        // and it is exactly (x²-1): x-1 alone is not in it
        let xm1 = rx(0) - rone();
        assert!(!rad.contains(&xm1).unwrap());

        // Zero-dimensional multivariate radical (Seidenberg): √(x², y²) = (x, y).
        let mut zd: Ideal<Rational> = Ideal::new(
            vec![rx(0) * rx(0), rx(1) * rx(1)],
            MonomialOrdering::Grevlex,
        );
        let mut rad = zd.radical().unwrap();
        assert!(rad.contains(&rx(0)).unwrap(), "√(x²,y²) must contain x");
        assert!(rad.contains(&rx(1)).unwrap(), "√(x²,y²) must contain y");
        assert!(!zd.contains(&rx(0)).unwrap(), "x ∉ (x²,y²)");
    }

    /// A positive-dimensional non-principal ideal must be an honest refusal.
    #[test]
    fn test_radical_refuses_what_it_cannot_do() {
        // (x*y, x*z) has dimension 2 in k[x,y,z]; its radical needs primary decomposition.
        let mut i: Ideal<Rational> = Ideal::new(
            vec![rx(0) * rx(1), rx(0) * rx(2)],
            MonomialOrdering::Grevlex,
        );
        let err = i.radical().unwrap_err();
        assert!(
            err.contains("primary decomposition"),
            "expected an honest refusal, got: {}",
            err
        );
    }

    #[test]
    fn test_multiple_generators() {
        let p1 = MultivariatePolynomial::constant(Integer::from(2));
        let p2 = MultivariatePolynomial::constant(Integer::from(3));
        let p3 = MultivariatePolynomial::constant(Integer::from(5));
        let ideal: Ideal<Integer> = Ideal::new(vec![p1, p2, p3], MonomialOrdering::Lex);

        assert_eq!(ideal.num_generators(), 3);
        assert!(!ideal.is_principal());
        assert!(!ideal.is_zero());
        assert!(!ideal.is_unit());
    }

    #[test]
    fn test_ideal_contains_zero() {
        let mut ideal: Ideal<Rational> = Ideal::unit(MonomialOrdering::Grevlex);
        let zero = MultivariatePolynomial::zero();
        assert!(ideal.contains(&zero).unwrap());
    }

    /// `contains` used to be `p.is_zero()` in disguise: `reduce_by_basis_static` never
    /// touched its accumulator, so the "remainder" was always `p` itself.
    #[test]
    fn test_contains_is_a_real_membership_test() {
        // I = (x² - 1). Then x² - 1 ∈ I and x⁴ - 1 = (x²+1)(x²-1) ∈ I, but x ∉ I.
        let mut i: Ideal<Rational> =
            Ideal::principal(rx(0) * rx(0) - rone(), MonomialOrdering::Grevlex);

        let x2m1 = rx(0) * rx(0) - rone();
        let x4m1 = rx(0) * rx(0) * rx(0) * rx(0) - rone();

        assert!(i.contains(&x2m1).unwrap(), "the generator must be a member");
        assert!(i.contains(&x4m1).unwrap(), "x⁴-1 = (x²+1)(x²-1) is a member");
        assert!(!i.contains(&rx(0)).unwrap(), "x is not in (x²-1)");
        assert!(!i.contains(&rone()).unwrap(), "1 is not in (x²-1)");
    }

    #[test]
    fn test_ideal_reduce() {
        let mut ideal: Ideal<Integer> = Ideal::zero(MonomialOrdering::Lex);
        let p = MultivariatePolynomial::constant(Integer::from(5));
        let reduced = ideal.reduce(&p);
        assert!(!reduced.is_zero());
    }

    /// BLOCKER: the two Gröbner engines used to share **one** cache field, so whichever
    /// ran first won it.
    ///
    /// `I = (x, x²)` over `Q`. The reduced Gröbner basis is `[x]` — `x²` is redundant. But
    /// `reduce()` runs the `R: Ring` engine, which caches the *non-reduced* basis
    /// `[x, x²]`; `reduced_basis()` then found the cache populated and handed that back,
    /// violating its own contract ("the canonical generating set: two ideals are equal iff
    /// these agree"). `contains` / `is_radical` / `radical` all route through
    /// `reduced_basis`, so they could be answered against a non-reduced basis.
    ///
    /// Revert the cache split and this test fails: the second `reduced_basis()` returns
    /// `["x0", "x0^2"]` instead of `["x0"]`.
    #[test]
    fn ideal_cache_split_reduced_basis_stays_reduced() {
        let budget = GroebnerBudget::default();
        let gens = vec![rx(0), rx(0) * rx(0)]; // (x, x²)

        // A fresh ideal: the reduced basis is [x].
        let mut fresh: Ideal<Rational> = Ideal::new(gens.clone(), MonomialOrdering::Grevlex);
        let expected = fresh.reduced_basis(&budget).unwrap();
        assert_eq!(
            expected.iter().map(|p| p.to_string()).collect::<Vec<_>>(),
            vec!["x0".to_string()],
            "the reduced Gröbner basis of (x, x²) is (x)"
        );

        // The same ideal, but the R: Ring engine runs first and fills *its* cache.
        let mut polluted: Ideal<Rational> = Ideal::new(gens, MonomialOrdering::Grevlex);
        let ring_basis = polluted.reduce(&(rx(0) * rx(0) * rx(0)));
        assert!(ring_basis.is_zero(), "x³ ∈ (x)");

        let after = polluted.reduced_basis(&budget).unwrap();
        assert_eq!(
            after.iter().map(|p| p.to_string()).collect::<Vec<_>>(),
            vec!["x0".to_string()],
            "reduced_basis() must still return the REDUCED basis [x] after reduce() has \
             populated the R: Ring cache — got a non-reduced basis, so the caches are \
             shared again"
        );
        assert_eq!(after, expected, "the cache must not change the answer");

        // The non-reduced engine really does return the redundant generator — this is what
        // used to leak into `reduced_basis`.
        let raw = polluted.get_groebner_basis();
        assert!(
            raw.len() > after.len(),
            "the R: Ring basis of (x, x²) is expected to keep the redundant x²; if it no \
             longer does, this test has stopped proving anything"
        );
    }

    /// `Ideal::reduce` used to loop forever whenever `deg(p) >= deg(g)` for some basis
    /// element `g` — this is the regression test for that hang, and it checks the
    /// reduction is actually performed.
    #[test]
    fn test_reduce_terminates_and_reduces() {
        // Z[x]/(x² - 1): x² reduces to 1.
        let mut i: Ideal<Integer> = Ideal::principal(
            ix(0) * ix(0) - MultivariatePolynomial::constant(Integer::from(1)),
            MonomialOrdering::Lex,
        );

        let x_sq = ix(0) * ix(0);
        let reduced = i.reduce(&x_sq);
        assert_eq!(
            reduced,
            MultivariatePolynomial::constant(Integer::from(1)),
            "x² should reduce to 1 modulo (x²-1)"
        );

        // x³ reduces to x.
        let x_cubed = ix(0) * ix(0) * ix(0);
        assert_eq!(i.reduce(&x_cubed), ix(0), "x³ should reduce to x modulo (x²-1)");
    }
}
