//! Quotient (vector-space) dimension via the *staircase* of a Gröbner basis.
//!
//! This is a NEW free function that fills the gap left by
//! [`crate::quotient::QuotientRing::dimension`], which currently returns `None`
//! ("Placeholder — requires more sophisticated analysis"). It is not ported from
//! `dessin_engine` (which has no Gröbner staircase); it is the standard
//! computational-algebra construction built on this crate's existing
//! [`groebner`](crate::groebner) module, listed as a stretch item for Agent P in
//! `/home/john/RustMath/DESSIN_REFACTOR_PLAN.md`.
//!
//! For a zero-dimensional ideal `I ⊆ k[x_0,…,x_{n-1}]`, the quotient `k[x]/I` is a
//! finite-dimensional `k`-vector space whose dimension (`vdim`) equals the number
//! of *standard monomials*: monomials not divisible by any leading monomial of a
//! Gröbner basis of `I`. If the ideal is positive-dimensional (some variable has
//! no pure power among the leading terms) the count is infinite and we return
//! `None`.
//!
//! ## Dependency note
//! This function counts the staircase of the Gröbner basis produced by this
//! crate's existing [`crate::groebner`] module. That Buchberger implementation
//! reduces using a unit quotient coefficient (a documented placeholder), so it
//! terminates and returns a correct basis for monomial ideals and ideals with
//! unit leading coefficients, but can loop on ideals whose reductions require
//! true coefficient division. Where the Gröbner basis is correct, the staircase
//! count here is exact; improving the underlying reducer would immediately widen
//! the set of ideals this handles, with no change needed here.

use crate::groebner::{reduced_groebner_basis, MonomialOrdering};
use crate::multivariate::{Monomial, MultivariatePolynomial};
use rustmath_core::Ring;
use std::cmp::Ordering;
use std::collections::BTreeMap;

/// Comparison closure for a [`MonomialOrdering`], built from the public
/// `Monomial::cmp_*` methods.
fn cmp_for(ordering: MonomialOrdering) -> impl Fn(&Monomial, &Monomial) -> Ordering + Copy {
    move |a: &Monomial, b: &Monomial| match ordering {
        MonomialOrdering::Lex => a.cmp_lex(b),
        MonomialOrdering::Grlex => a.cmp_grlex(b),
        MonomialOrdering::Grevlex => a.cmp_grevlex(b),
    }
}

/// The `k`-vector-space dimension of `k[x_0,…,x_{nvars-1}] / I`, where `I` is the
/// ideal generated by `generators`.
///
/// Returns:
/// * `Some(0)` if `I` is the whole ring (a Gröbner basis contains a unit);
/// * `Some(d)` if `I` is zero-dimensional, with `d` the number of standard
///   monomials (the exact `vdim`);
/// * `None` if `I` is positive-dimensional (the quotient is infinite-dimensional)
///   or if `generators` is empty / all zero (the quotient is the whole ring).
///
/// Meaningful over a field (matching Buchberger's algorithm in
/// [`crate::groebner`]); `nvars` is the ambient variable count of the polynomial
/// ring (needed for the zero-dimensionality test).
pub fn quotient_dimension<R: Ring>(
    generators: Vec<MultivariatePolynomial<R>>,
    nvars: usize,
    ordering: MonomialOrdering,
) -> Option<usize> {
    let cmp = cmp_for(ordering);
    let basis = reduced_groebner_basis(generators, ordering);

    // Collect leading monomials.
    let mut leads: Vec<Monomial> = Vec::new();
    for g in &basis {
        if let Some(lm) = g.leading_monomial(cmp) {
            leads.push(lm);
        }
    }

    // Empty ideal → whole ring, infinite-dimensional.
    if leads.is_empty() {
        return None;
    }

    // A unit in the ideal (constant leading monomial) → quotient is {0}.
    if leads.iter().any(|m| m.is_one()) {
        return Some(0);
    }

    // Zero-dimensionality: every variable must admit a *pure power* among the
    // leading monomials. The minimal such power bounds that variable's exponent
    // in any standard monomial.
    let mut bounds = vec![None::<u32>; nvars];
    for lm in &leads {
        // Is this leading monomial a pure power of a single variable?
        let vars = lm.variables();
        if vars.len() == 1 {
            let v = vars[0];
            if v < nvars {
                let e = lm.exponent(v);
                bounds[v] = Some(match bounds[v] {
                    Some(cur) => cur.min(e),
                    None => e,
                });
            }
        }
    }
    let mut caps = Vec::with_capacity(nvars);
    for b in &bounds {
        match b {
            Some(e) => caps.push(*e), // standard exponents are 0..e
            None => return None,      // no pure power ⇒ positive-dimensional
        }
    }

    // Count monomials in the box ∏ [0, caps[v]) not divisible by any leading
    // monomial.
    let mut count = 0usize;
    let mut exps = vec![0u32; nvars];
    'outer: loop {
        // Build the candidate monomial and test divisibility by each lead.
        let mut map = BTreeMap::new();
        for (v, &e) in exps.iter().enumerate() {
            if e > 0 {
                map.insert(v, e);
            }
        }
        let cand = Monomial::from_exponents(map);
        // `cand.div(lm).is_some()` ⇔ lm divides cand.
        let divisible = leads.iter().any(|lm| cand.div(lm).is_some());
        if !divisible {
            count += 1;
        }

        // Odometer increment over the box.
        let mut i = 0;
        loop {
            if i == nvars {
                break 'outer;
            }
            exps[i] += 1;
            if exps[i] < caps[i] {
                break;
            }
            exps[i] = 0;
            i += 1;
        }
    }

    Some(count)
}

#[cfg(test)]
mod tests {
    use super::*;
    use rustmath_rationals::Rational;

    type MP = MultivariatePolynomial<Rational>;

    fn c(n: i64) -> Rational {
        Rational::from_i64(n)
    }

    fn x(i: usize) -> MP {
        MP::variable(i)
    }

    fn constant(n: i64) -> MP {
        MP::constant(c(n))
    }

    #[test]
    fn dimension_maximal_ideal() {
        // I = (x, y); quotient ≅ k ⇒ vdim = 1.
        assert_eq!(
            quotient_dimension(vec![x(0), x(1)], 2, MonomialOrdering::Grevlex),
            Some(1)
        );
    }

    #[test]
    fn dimension_fat_point() {
        // I = (x^2, x*y, y^2); standard monomials {1, x, y} ⇒ vdim = 3.
        let x2 = x(0).clone() * x(0);
        let xy = x(0).clone() * x(1);
        let y2 = x(1).clone() * x(1);
        assert_eq!(
            quotient_dimension(vec![x2, xy, y2], 2, MonomialOrdering::Grevlex),
            Some(3)
        );
    }

    #[test]
    fn positive_dimensional_is_none() {
        // I = (x*y): y has no pure power ⇒ positive-dimensional ⇒ None.
        let xy = x(0).clone() * x(1);
        assert_eq!(
            quotient_dimension(vec![xy], 2, MonomialOrdering::Lex),
            None
        );
    }

    #[test]
    fn unit_ideal_is_zero() {
        // I = (1) is the whole ring ⇒ quotient {0} ⇒ vdim = 0.
        assert_eq!(
            quotient_dimension(vec![constant(1)], 2, MonomialOrdering::Lex),
            Some(0)
        );
    }

    #[test]
    fn empty_ideal_is_none() {
        // I = (0) ⇒ whole ring ⇒ infinite-dimensional ⇒ None.
        let empty: Vec<MP> = vec![];
        assert_eq!(quotient_dimension(empty, 2, MonomialOrdering::Lex), None);
    }
}
