//! Solvable towers: derived series, chief series, and elementary-abelian layers.
//!
//! Given the permutation generators of a **solvable** transitive group `G ≤ S₂₄`
//! (the CFT construction targets are solvable `24Tt`), this module decomposes `G`
//! into **abelian layers** — a normal series
//!
//! ```text
//! 1 = G_k ◁ … ◁ G_1 ◁ G_0 = G
//! ```
//!
//! with **abelian quotients** `G_i/G_{i+1}` — and refines it to a **chief series**
//! whose factors are **elementary abelian** (each `≅ (ℤ/p)^d`). This drives the
//! class-field-theory abelian-layer construction loop: each factor is a `ℤ/p`-module,
//! exactly the input an abelian-extension builder consumes.
//!
//! Spec mirror: Magma `DerivedSeries`, `ChiefSeries`, `AbelianQuotient`
//! (handbook Ch.63, *Finite Soluble Groups*, at `rustmath-lava/docs/`).
//!
//! # Algorithm
//!
//! - **Derived series** `G ⊇ G' ⊇ G'' ⊇ … ⊇ 1`, where `G' = [G,G]` is generated by
//!   all commutators `[a,b] = a⁻¹b⁻¹ab`. We take the *subgroup closure* of the
//!   commutators of every pair of elements of the (already enumerated) group — for a
//!   finite group this is exactly the derived subgroup, and it is automatically normal
//!   in `G`, so each derived term is normal in `G` and the quotients are abelian. For
//!   solvable `G` the series reaches `1`; if it does **not**, the input is not solvable
//!   and we report `solvable = false`.
//! - **Refine to elementary-abelian chief factors.** Between consecutive derived terms
//!   `A = G^{(i)} ⊋ B = G^{(i+1)}` the quotient `A/B` is a finite **abelian** group of
//!   order `m`. We split it prime-by-prime: for each prime `p | m`, the chain of
//!   subgroups
//!   ```text
//!   A ⊇ ⟨B, A^p, (p-power filtration)…⟩ ⊇ … ⊇ B
//!   ```
//!   built as preimages of the subgroups `p·(A/B) ⊆ A/B`, `p²·(A/B) ⊆ …` etc., yields
//!   successive quotients that are elementary abelian `(ℤ/p)^d`. Because every subgroup
//!   of the abelian quotient `A/B` is **characteristic** under the conjugation action of
//!   `G` only when it is verbal/marginal, we instead build each refinement step as the
//!   preimage of the **`G`-invariant** subgroup `p^j·(A/B)` (the image of the `p^j`-power
//!   map is characteristic in `A/B`, hence its preimage is normal in `G`). Each
//!   resulting factor is therefore a chief-style elementary-abelian layer, normal in `G`.
//!
//! Everything is done with **explicit element lists** (BFS closure), so it is exact and
//! enumerable only for `|G|` up to a configurable `cap`. The degree-24 solvable targets
//! have order `2³·3·… = 24·k` with `k` modest, well inside a few-hundred-thousand cap.

use crate::transitive24::{compose, group_closure, identity, Perm, DEG};
use std::collections::HashSet;

/// Inverse of a permutation given as an image array: `inverse(p)[p[i]] = i`.
pub fn inverse(p: &Perm) -> Perm {
    let mut q = [0u8; DEG];
    for i in 0..DEG {
        q[p[i] as usize] = i as u8;
    }
    q
}

/// The commutator `[a,b] = a⁻¹ b⁻¹ a b`.
pub fn commutator(a: &Perm, b: &Perm) -> Perm {
    let ai = inverse(a);
    let bi = inverse(b);
    // a⁻¹ b⁻¹ a b, with compose(x,y) = apply y then x.
    compose(&ai, &compose(&bi, &compose(a, b)))
}

/// Close a set of generators into a subgroup (BFS), returning its full element list.
/// `None` if the closure exceeds `cap` elements.
pub fn subgroup_closure(gens: &[Perm], cap: usize) -> Option<HashSet<Perm>> {
    group_closure(gens, cap)
}

/// The **derived subgroup** `H' = [H,H]` of the group generated by `gens`.
///
/// Returns a generating set of `H'` (the commutators of all pairs of *elements* of
/// `H`, whose subgroup closure is exactly `H'`). `None` if `⟨gens⟩` exceeds `cap`.
///
/// Because `H'` is generated by all commutators of `H`, it is fully invariant in `H`
/// and in particular **normal** in `H`; the quotient `H/H'` is abelian.
pub fn derived_subgroup(gens: &[Perm], cap: usize) -> Option<Vec<Perm>> {
    let elements = group_closure(gens, cap)?;
    let elems: Vec<Perm> = elements.into_iter().collect();
    let mut comm_gens: HashSet<Perm> = HashSet::new();
    let id = identity();
    for a in &elems {
        for b in &elems {
            let c = commutator(a, b);
            if c != id {
                comm_gens.insert(c);
            }
        }
    }
    Some(comm_gens.into_iter().collect())
}

/// The **normal closure** in `G = ⟨g_gens⟩` of the subgroup `⟨h_gens⟩`: the smallest
/// normal subgroup of `G` containing `⟨h_gens⟩`, i.e. `⟨ x⁻¹ h x : x ∈ G, h ∈ h_gens ⟩`.
///
/// Returns its full element set, or `None` if it exceeds `cap`.
pub fn normal_closure(g_gens: &[Perm], h_gens: &[Perm], cap: usize) -> Option<HashSet<Perm>> {
    let g = group_closure(g_gens, cap)?;
    let mut conj_gens: Vec<Perm> = Vec::new();
    for x in &g {
        let xi = inverse(x);
        for h in h_gens {
            // x⁻¹ h x
            conj_gens.push(compose(&xi, &compose(h, x)));
        }
    }
    group_closure(&conj_gens, cap)
}

/// An elementary-abelian chief factor `≅ (ℤ/p)^dim`, normal in `G`.
///
/// `quotient_gens` are coset representatives (elements of the larger term `top`) whose
/// images generate the factor as a `ℤ/p`-vector space; they are the module generators
/// the construction driver consumes for this layer.
#[derive(Clone, Debug)]
pub struct ChiefFactor {
    /// The prime `p`.
    pub p: usize,
    /// The dimension `d`, so the factor is `(ℤ/p)^d` of order `p^d`.
    pub dim: usize,
    /// The order `p^d` of this chief factor.
    pub order: usize,
    /// Coset representatives (in the upper term) whose images generate the factor.
    pub quotient_gens: Vec<Perm>,
}

/// The decomposition of `G` into a normal series with elementary-abelian factors.
#[derive(Clone, Debug)]
pub struct SolvableTower {
    /// The normal series, top (`G`) first, `{1}` last: `series[i] ⊇ series[i+1]`.
    /// Each entry is the full element list of that term.
    pub series: Vec<Vec<Perm>>,
    /// The chief factors, top-to-bottom: `factors[i] = series[i] / series[i+1]`,
    /// each elementary abelian `(ℤ/p)^d` and normal in `G`.
    pub factors: Vec<ChiefFactor>,
    /// `true` iff the derived series reached `{1}` within `cap` (i.e. `G` is solvable
    /// and enumerable).
    pub solvable: bool,
    /// The order `|G|` (the size of the enumerated group), if `G` was enumerable.
    pub order: Option<usize>,
}

/// Sort a permutation set into a stable element list (deterministic output).
fn sorted_elems(set: &HashSet<Perm>) -> Vec<Perm> {
    let mut v: Vec<Perm> = set.iter().copied().collect();
    v.sort_unstable();
    v
}

/// Trial-factor `n` into its distinct prime divisors (n is a group order, modest).
fn prime_divisors(mut n: usize) -> Vec<usize> {
    let mut ps = Vec::new();
    let mut d = 2usize;
    while d * d <= n {
        if n % d == 0 {
            ps.push(d);
            while n % d == 0 {
                n /= d;
            }
        }
        d += 1;
    }
    if n > 1 {
        ps.push(n);
    }
    ps
}

/// Given a subgroup `top` and a normal subgroup `bot ⊆ top` with **abelian** quotient
/// `top/bot`, together with the ambient group `g` (for normality of refinement steps),
/// refine `top/bot` into elementary-abelian chief factors and append them to `factors`.
///
/// Strategy: the abelian quotient `Q = top/bot` factors as `⊕_p Q_p`. For each prime
/// `p | |Q|` we peel off elementary-abelian layers via the `p`-power filtration
/// `Q ⊇ pQ ⊇ p²Q ⊇ … ⊇ 0`. The image `pᵏQ` is the set of `p`-th powers iterated, a
/// fully-invariant (hence `G`-normal) subgroup of `Q`; its preimage in `top` is normal
/// in `G`. Consecutive quotients `pᵏQ / pᵏ⁺¹Q` are elementary abelian `(ℤ/p)^d`.
///
/// Returns the refined chain of subgroups (element sets) from `top` down to `bot`,
/// excluding `top` itself (so the caller can stitch series terms), most-recent last;
/// pushes one [`ChiefFactor`] per refinement step into `factors`.
fn refine_abelian_layer(
    g_gens: &[Perm],
    top: &HashSet<Perm>,
    bot: &HashSet<Perm>,
    cap: usize,
    factors: &mut Vec<ChiefFactor>,
    series_terms: &mut Vec<Vec<Perm>>,
) {
    let index = top.len() / bot.len();
    if index == 1 {
        return;
    }
    let primes = prime_divisors(index);

    // Current "upper" subgroup we are peeling factors off of, as we descend toward bot.
    let mut cur: HashSet<Perm> = top.clone();

    for &p in &primes {
        // Peel the entire p-part: repeatedly form the subgroup generated by bot together
        // with the p-th powers of cur (i.e. preimage of p·(cur/bot)). Each step's factor
        // cur / next is elementary abelian (ℤ/p)^d.
        loop {
            // next = ⟨ bot, { x^p : x ∈ cur } ⟩ ∩ (within cur). Since cur/bot is abelian,
            // {x^p} together with bot generates the preimage of p·(cur/bot).
            let mut gens: Vec<Perm> = bot.iter().copied().collect();
            for x in &cur {
                gens.push(pow(x, p));
            }
            let next = match group_closure(&gens, cap) {
                Some(s) => s,
                None => return,
            };
            let step_index = cur.len() / next.len();
            if step_index == 1 {
                // No p-torsion left at this level; move to next prime.
                break;
            }
            // step_index must be a power of p (elementary abelian (ℤ/p)^d).
            let dim = ilog(step_index, p);
            // Coset representatives of next in cur whose images generate cur/next.
            let qgens = quotient_generators(&cur, &next);
            factors.push(ChiefFactor {
                p,
                dim,
                order: step_index,
                quotient_gens: qgens,
            });
            series_terms.push(sorted_elems(&next));
            cur = next;
            // Ensure each refinement term is normal in G. The preimage of pᵏ·(cur/bot)
            // is fully invariant in the abelian quotient, hence G-normal; we keep using
            // it directly. (g_gens reserved for an explicit normal-closure guard.)
            let _ = g_gens;
        }
    }
    debug_assert_eq!(cur.len(), bot.len());
}

/// `p`-th power of a permutation.
fn pow(x: &Perm, k: usize) -> Perm {
    let mut acc = identity();
    for _ in 0..k {
        acc = compose(x, &acc);
    }
    acc
}

/// Integer log base `p` of `n` when `n = p^d` (panics in debug if `n` is not a power).
fn ilog(mut n: usize, p: usize) -> usize {
    let mut d = 0;
    while n > 1 {
        debug_assert_eq!(n % p, 0, "elementary-abelian factor order must be a prime power");
        n /= p;
        d += 1;
    }
    d
}

/// Choose coset representatives of `sub` in `top` whose images **generate** `top/sub`.
/// Greedy: walk elements of `top`; pick `x` if its coset is not yet in the subgroup
/// spanned (in `top/sub`) by previously chosen reps together with `sub`.
fn quotient_generators(top: &HashSet<Perm>, sub: &HashSet<Perm>) -> Vec<Perm> {
    let mut spanned: HashSet<Perm> = sub.clone();
    let mut gens: Vec<Perm> = Vec::new();
    for x in sorted_elems(top) {
        if spanned.contains(&x) {
            continue;
        }
        gens.push(x);
        // Re-span: subgroup generated by current gens together with sub.
        let mut g: Vec<Perm> = sub.iter().copied().collect();
        g.extend(gens.iter().copied());
        // Closure cannot exceed |top|.
        if let Some(s) = group_closure(&g, top.len() + 1) {
            spanned = s;
        }
        if spanned.len() == top.len() {
            break;
        }
    }
    gens
}

/// Build the solvable tower of `G = ⟨gens⟩`: derived series refined to elementary-abelian
/// chief factors. See the module docs.
///
/// `cap` bounds the number of enumerated elements (BFS closure). If `|G| > cap`, the
/// result has `order = None`, `solvable = false`, empty series/factors.
pub fn solvable_tower(gens: &[Perm], cap: usize) -> SolvableTower {
    // Enumerate G.
    let g = match group_closure(gens, cap) {
        Some(s) => s,
        None => {
            return SolvableTower {
                series: Vec::new(),
                factors: Vec::new(),
                solvable: false,
                order: None,
            }
        }
    };
    let g_order = g.len();
    let g_gens: Vec<Perm> = gens.to_vec();

    // ---- Derived series: G ⊇ G' ⊇ G'' ⊇ … ----
    // derived_terms[i] = element set of G^{(i)}; current generating set tracked alongside.
    let mut derived_sets: Vec<HashSet<Perm>> = vec![g.clone()];
    let mut cur_gens: Vec<Perm> = g_gens.clone();
    let mut solvable = true;

    loop {
        let last = derived_sets.last().unwrap();
        if last.len() == 1 {
            break; // reached the trivial group
        }
        let dgens = match derived_subgroup(&cur_gens, cap) {
            Some(d) => d,
            None => {
                solvable = false;
                break;
            }
        };
        let dset = match group_closure(&dgens, cap) {
            Some(s) => s,
            None => {
                solvable = false;
                break;
            }
        };
        if dset.len() == last.len() {
            // Perfect group reached (G = G'): derived series stalls above 1 ⇒ not solvable.
            solvable = false;
            break;
        }
        derived_sets.push(dset);
        cur_gens = dgens;
    }

    if !solvable {
        // Non-solvable (or non-terminating): report the derived series we have, no factors.
        let series: Vec<Vec<Perm>> = derived_sets.iter().map(sorted_elems).collect();
        return SolvableTower {
            series,
            factors: Vec::new(),
            solvable: false,
            order: Some(g_order),
        };
    }

    // ---- Refine each abelian derived quotient into elementary-abelian chief factors ----
    let mut factors: Vec<ChiefFactor> = Vec::new();
    let mut series_terms: Vec<Vec<Perm>> = vec![sorted_elems(&g)];

    for i in 0..derived_sets.len() - 1 {
        let top = &derived_sets[i];
        let bot = &derived_sets[i + 1];
        refine_abelian_layer(&g_gens, top, bot, cap, &mut factors, &mut series_terms);
    }

    SolvableTower {
        series: series_terms,
        factors,
        solvable: true,
        order: Some(g_order),
    }
}

/// Convenience: the multiset `[(p, d), …]` of chief factors, top-to-bottom — the layer
/// list the construction driver iterates over (each a `ℤ/p`-module of dimension `d`).
pub fn factor_signature(tower: &SolvableTower) -> Vec<(usize, usize)> {
    tower.factors.iter().map(|f| (f.p, f.dim)).collect()
}

/// Product of the chief-factor orders. For a solvable, enumerated `G` this equals `|G|`.
pub fn factors_order_product(tower: &SolvableTower) -> usize {
    tower.factors.iter().map(|f| f.order).product()
}

/// Map points to a permutation from 0-indexed image slice (helper for tests).
#[allow(dead_code)]
fn perm_from_images(images: &[usize]) -> Perm {
    let mut p = identity();
    for (i, &im) in images.iter().enumerate() {
        p[i] = im as u8;
    }
    p
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::transitive24::perm_from_cycles;

    /// S₃ acting on {0,1,2} embedded in S₂₄ (points 1,2,3 in 1-indexed cycle notation).
    fn s3_gens() -> Vec<Perm> {
        // (012) and (01) in 0-indexed; as 1-indexed cycles: (1 2 3) and (1 2).
        vec![
            perm_from_cycles(&[vec![1, 2, 3]]),
            perm_from_cycles(&[vec![1, 2]]),
        ]
    }

    /// S₄ on {0,1,2,3}: generators (0123) and (01) → 1-indexed (1 2 3 4), (1 2).
    fn s4_gens() -> Vec<Perm> {
        vec![
            perm_from_cycles(&[vec![1, 2, 3, 4]]),
            perm_from_cycles(&[vec![1, 2]]),
        ]
    }

    /// A₅ on {0,…,4}: generators (012) and (234) → 1-indexed (1 2 3), (3 4 5).
    fn a5_gens() -> Vec<Perm> {
        vec![
            perm_from_cycles(&[vec![1, 2, 3]]),
            perm_from_cycles(&[vec![3, 4, 5]]),
        ]
    }

    #[test]
    fn inverse_and_commutator() {
        let a = perm_from_cycles(&[vec![1, 2, 3]]);
        let ai = inverse(&a);
        assert_eq!(compose(&a, &ai), identity());
        // [a,a] = 1
        assert_eq!(commutator(&a, &a), identity());
        // For a transposition b and 3-cycle a, [a,b] is a 3-cycle (in S₃, A₃ is derived).
        let b = perm_from_cycles(&[vec![1, 2]]);
        let c = commutator(&a, &b);
        assert_ne!(c, identity());
    }

    #[test]
    fn s3_tower() {
        let t = solvable_tower(&s3_gens(), 10_000);
        assert!(t.solvable);
        assert_eq!(t.order, Some(6));
        // Factors should be (Z/2) and (Z/3) in some order; product of orders = 6.
        assert_eq!(factors_order_product(&t), 6);
        let mut sig = factor_signature(&t);
        sig.sort();
        assert_eq!(sig, vec![(2, 1), (3, 1)]);
        // Derived series: S₃ ⊃ A₃ ⊃ 1 — three terms (G, G', 1).
        // The refined series has the same three terms here (both factors prime).
        assert_eq!(t.series.first().unwrap().len(), 6);
        assert_eq!(t.series.last().unwrap().len(), 1);
        // The factor adjacent to G is the top quotient G/G' = Z/2.
        assert_eq!(t.factors.first().unwrap().order, 2);
    }

    #[test]
    fn s4_tower() {
        let t = solvable_tower(&s4_gens(), 10_000);
        assert!(t.solvable);
        assert_eq!(t.order, Some(24));
        assert_eq!(factors_order_product(&t), 24);
        // S₄ ⊃ A₄ ⊃ V₄ ⊃ 1 with factors Z/2, Z/3, (Z/2)². Top-to-bottom signature.
        let sig = factor_signature(&t);
        assert_eq!(sig, vec![(2, 1), (3, 1), (2, 2)]);
        // Verify each factor is elementary abelian and orders multiply to 24.
        let orders: Vec<usize> = t.factors.iter().map(|f| f.order).collect();
        assert_eq!(orders, vec![2, 3, 4]);
        // First refined term below G is A₄ (order 12).
        assert_eq!(t.series[1].len(), 12);
    }

    #[test]
    fn a5_not_solvable() {
        let t = solvable_tower(&a5_gens(), 10_000);
        // A₅ is perfect: derived series stalls (A₅' = A₅) ⇒ not solvable.
        assert!(!t.solvable);
        assert_eq!(t.order, Some(60));
        assert!(t.factors.is_empty());
    }

    #[test]
    fn a5_derived_is_itself() {
        // derived_subgroup(A₅) generates A₅ again (order 60).
        let d = derived_subgroup(&a5_gens(), 10_000).unwrap();
        let dset = group_closure(&d, 10_000).unwrap();
        assert_eq!(dset.len(), 60);
    }

    #[test]
    fn normal_closure_of_3cycle_in_s3_is_a3() {
        let g = s3_gens();
        let h = vec![perm_from_cycles(&[vec![1, 2, 3]])];
        let nc = normal_closure(&g, &h, 10_000).unwrap();
        assert_eq!(nc.len(), 3); // ⟨(123)⟩ = A₃, already normal.
    }

    /// A solvable degree-24 group from the atlas: assert chief factors multiply to |G|
    /// and each factor is elementary abelian. Prints |G| and the (p,d) list for GAP diff.
    #[test]
    fn atlas_solvable_24t() {
        use crate::transitive24::Db;
        let db = match Db::load_default() {
            Ok(db) => db,
            Err(_) => {
                eprintln!("atlas_solvable_24t: atlas not found, skipping");
                return;
            }
        };
        // Pick the smallest-order solvable group of degree 24 (skip the cyclic/tiny ones
        // would be uninteresting — pick the smallest order ≥ 24 that is solvable and
        // enumerable). 24T1 = C24 (order 24), a good first sanity target.
        let cap = 500_000;
        let mut tested = 0;
        // Try a handful of small solvable groups so the cross-check has variety.
        for g in db.groups.iter().filter(|g| g.solvable) {
            let t = solvable_tower(&g.gens, cap);
            if t.order.is_none() {
                continue; // exceeded cap
            }
            let n = t.order.unwrap();
            assert!(t.solvable, "24T{} reported non-solvable but atlas says solvable", g.t);
            let prod = factors_order_product(&t);
            assert_eq!(
                prod, n,
                "24T{}: chief factor orders {:?} product {} != |G| {}",
                g.t,
                t.factors.iter().map(|f| f.order).collect::<Vec<_>>(),
                prod,
                n
            );
            // Each factor elementary abelian: order = p^dim.
            for f in &t.factors {
                assert_eq!(f.order, f.p.pow(f.dim as u32));
            }
            println!(
                "24T{}  |G|={}  factors(p,d)={:?}",
                g.t,
                n,
                factor_signature(&t)
            );
            tested += 1;
            if tested >= 5 {
                break;
            }
        }
        assert!(tested > 0, "no enumerable solvable 24Tt found within cap");
    }
}
