//! The maximal order `O_K` of a number field `K = ℚ[x]/(f)` as a Dedekind
//! context, backed by the verified ideal arithmetic of `rustmath-numberfields`
//! (HNF fractional ideals, ideal inverses via SNF colon computation, and the
//! bounded LLL principality search of `classgroup::is_principal`).
//!
//! Elements of `K` are stored in **integral-basis coordinates** with a
//! denominator: `x = (Σᵢ nᵢωᵢ)/d`, canonically reduced (`d > 0`,
//! `gcd(n₀,…,d) = 1`), so derived `PartialEq` is mathematical equality.

use super::{DedekindContext, DedekindError, Principality};
use rustmath_integers::Integer;
use rustmath_matrix::Matrix;
use rustmath_numberfields::classgroup::is_principal;
use rustmath_numberfields::ideals::{ideal_from_generators, ideal_inverse, ideal_mul, one_ideal, Ideal};
use rustmath_numberfields::round2::{maximal_order_data, OrderData};
use rustmath_rationals::Rational;

/// An element of `K` in integral-basis coordinates over a denominator.
#[derive(Debug, Clone, PartialEq)]
pub struct NfElem {
    num: Vec<Integer>,
    den: Integer,
}

impl NfElem {
    /// Canonical construction: `den > 0` and `gcd(num…, den) = 1`.
    ///
    /// # Panics
    /// Panics if `den = 0` (not a field element).
    pub fn new(mut num: Vec<Integer>, mut den: Integer) -> Self {
        assert!(!den.is_zero(), "NfElem denominator must be nonzero");
        if den.signum() < 0 {
            den = -den;
            for c in &mut num {
                *c = -c.clone();
            }
        }
        let mut g = den.clone();
        for c in &num {
            if !c.is_zero() {
                g = g.gcd(c);
            }
        }
        let g = g.abs();
        if !g.is_one() && !g.is_zero() {
            den = den / g.clone();
            for c in &mut num {
                *c = c.clone() / g.clone();
            }
        }
        NfElem { num, den }
    }

    /// Integral-basis numerator coordinates.
    pub fn numerator(&self) -> &[Integer] {
        &self.num
    }

    /// The (positive) denominator.
    pub fn denominator(&self) -> &Integer {
        &self.den
    }

    /// Is this the zero element?
    pub fn is_zero_elem(&self) -> bool {
        self.num.iter().all(|c| c.is_zero())
    }
}

/// The maximal order of `K = ℚ[x]/(f)` as a [`DedekindContext`].
pub struct NfDedekind {
    f: Vec<Integer>,
    ord: OrderData,
}

impl NfDedekind {
    /// Build the context for `K = ℚ[x]/(f)`.
    ///
    /// `f` is given by ascending coefficients `[c₀, …, c_{n-1}, 1]` and **must
    /// be monic and irreducible over ℚ** (irreducibility is a precondition,
    /// not verified here; a reducible `f` makes `K` a non-field and element
    /// inversion will fail on zero divisors).
    pub fn new(f: Vec<Integer>) -> Self {
        let ord = maximal_order_data(&f);
        NfDedekind { f, ord }
    }

    /// Convenience: build from `i64` coefficients.
    pub fn from_i64_poly(f: &[i64]) -> Self {
        Self::new(f.iter().map(|&c| Integer::from(c)).collect())
    }

    /// Field degree `n = [K : ℚ]`.
    pub fn degree(&self) -> usize {
        self.ord.n
    }

    /// The underlying maximal-order data (integral basis + structure constants).
    pub fn order_data(&self) -> &OrderData {
        &self.ord
    }

    /// Element from `i64` integral-basis coordinates over a denominator.
    pub fn elem(&self, coords: &[i64], den: i64) -> NfElem {
        assert_eq!(coords.len(), self.ord.n, "coordinate length must equal degree");
        NfElem::new(
            coords.iter().map(|&c| Integer::from(c)).collect(),
            Integer::from(den),
        )
    }

    /// The rational `q` as an element of `K`.
    pub fn from_rational(&self, q: &Rational) -> NfElem {
        let one = self.ord.one();
        let num: Vec<Integer> = one.iter().map(|c| c.clone() * q.numerator().clone()).collect();
        NfElem::new(num, q.denominator().clone())
    }

    /// The `O_K`-ideal generated by the given elements of `K`; `None` iff all
    /// generators are zero.
    pub fn ideal_from_elems(&self, gens: &[NfElem]) -> Option<Ideal> {
        let nonzero: Vec<&NfElem> = gens.iter().filter(|g| !g.is_zero_elem()).collect();
        if nonzero.is_empty() {
            return None;
        }
        // common denominator D, integral generators D·gᵢ, then divide by (D)
        let mut dd = Integer::one();
        for g in &nonzero {
            dd = lcm(&dd, &g.den);
        }
        let int_gens: Vec<Vec<Integer>> = nonzero
            .iter()
            .map(|g| {
                let s = dd.clone() / g.den.clone();
                g.num.iter().map(|c| c.clone() * s.clone()).collect()
            })
            .collect();
        let ideal = ideal_from_generators(&self.ord, &int_gens);
        Some(self.divide_by_rational_integer(ideal, &dd))
    }

    /// `𝔞·(1/d)` for a positive integer `d`, via multiplication by `(d)⁻¹`.
    fn divide_by_rational_integer(&self, a: Ideal, d: &Integer) -> Ideal {
        if d.is_one() {
            return a;
        }
        let d_one: Vec<Integer> = self.ord.one().iter().map(|c| c.clone() * d.clone()).collect();
        let d_ideal = ideal_from_generators(&self.ord, &[d_one]);
        ideal_mul(&self.ord, &a, &ideal_inverse(&self.ord, &d_ideal))
    }

    /// Membership of the *integer vector* `t` in the ℤ-lattice spanned by the
    /// lower-triangular columns `basis` scaled by `s` (forward substitution on
    /// the canonical HNF shape: column `i` has pivot at row `i`, zeros above).
    fn lattice_member(basis: &[Vec<Integer>], s: &Integer, t: &[Integer], n: usize) -> bool {
        let mut c = vec![Integer::zero(); n];
        for i in 0..n {
            let mut acc = t[i].clone();
            for (j, cj) in c.iter().enumerate().take(i) {
                acc = acc - basis[j][i].clone() * s.clone() * cj.clone();
            }
            let piv = basis[i][i].clone() * s.clone();
            if piv.is_zero() {
                if !acc.is_zero() {
                    return false;
                }
                continue;
            }
            if !(acc.clone() % piv.clone()).is_zero() {
                return false;
            }
            c[i] = acc / piv;
        }
        true
    }
}

fn lcm(a: &Integer, b: &Integer) -> Integer {
    if a.is_zero() || b.is_zero() {
        return Integer::zero();
    }
    ((a.clone() / a.gcd(b)) * b.clone()).abs()
}

impl DedekindContext for NfDedekind {
    type Elem = NfElem;
    type Ideal = Ideal;

    fn zero(&self) -> NfElem {
        NfElem::new(vec![Integer::zero(); self.ord.n], Integer::one())
    }

    fn one(&self) -> NfElem {
        NfElem::new(self.ord.one(), Integer::one())
    }

    fn add(&self, a: &NfElem, b: &NfElem) -> NfElem {
        let num: Vec<Integer> = a
            .num
            .iter()
            .zip(&b.num)
            .map(|(x, y)| x.clone() * b.den.clone() + y.clone() * a.den.clone())
            .collect();
        NfElem::new(num, a.den.clone() * b.den.clone())
    }

    fn neg(&self, a: &NfElem) -> NfElem {
        NfElem::new(a.num.iter().map(|c| -c.clone()).collect(), a.den.clone())
    }

    fn mul(&self, a: &NfElem, b: &NfElem) -> NfElem {
        NfElem::new(self.ord.mul(&a.num, &b.num), a.den.clone() * b.den.clone())
    }

    /// Inverse via the multiplication matrix: solve `M_x·y = 1` over ℚ.
    /// `None` iff `x = 0` (or `x` is a zero divisor, which violates the
    /// irreducibility precondition).
    fn inv(&self, a: &NfElem) -> Option<NfElem> {
        if a.is_zero_elem() {
            return None;
        }
        let n = self.ord.n;
        // column j = num·ωⱼ in integral-basis coordinates
        let mut data: Vec<Rational> = Vec::with_capacity(n * n);
        let mut cols: Vec<Vec<Integer>> = Vec::with_capacity(n);
        for j in 0..n {
            let mut ej = vec![Integer::zero(); n];
            ej[j] = Integer::one();
            cols.push(self.ord.mul(&a.num, &ej));
        }
        for i in 0..n {
            for col in cols.iter() {
                data.push(Rational::from_integer(col[i].clone()));
            }
        }
        let m = Matrix::from_vec(n, n, data).expect("square multiplication matrix");
        let one_coords: Vec<Rational> = self
            .ord
            .one()
            .iter()
            .map(|c| Rational::from_integer(c.clone()))
            .collect();
        let y = m.solve(&one_coords).ok().flatten()?;
        // x⁻¹ = den·y : clear rational denominators
        let mut dd = Integer::one();
        for q in &y {
            dd = lcm(&dd, q.denominator());
        }
        let num: Vec<Integer> = y
            .iter()
            .map(|q| {
                q.numerator().clone() * a.den.clone() * (dd.clone() / q.denominator().clone())
            })
            .collect();
        Some(NfElem::new(num, dd))
    }

    fn unit_ideal(&self) -> Ideal {
        one_ideal(&self.ord)
    }

    fn ideal_mul(&self, a: &Ideal, b: &Ideal) -> Ideal {
        ideal_mul(&self.ord, a, b)
    }

    /// `𝔞 + 𝔟`: scale both to a common denominator, take the `O_K`-span of the
    /// union of their ℤ-bases, divide the denominator back out.
    fn ideal_add(&self, a: &Ideal, b: &Ideal) -> Ideal {
        let dd = lcm(&a.denom, &b.denom);
        let sa = dd.clone() / a.denom.clone();
        let sb = dd.clone() / b.denom.clone();
        let mut gens: Vec<Vec<Integer>> = Vec::with_capacity(2 * self.ord.n);
        for col in &a.basis {
            gens.push(col.iter().map(|c| c.clone() * sa.clone()).collect());
        }
        for col in &b.basis {
            gens.push(col.iter().map(|c| c.clone() * sb.clone()).collect());
        }
        let sum = ideal_from_generators(&self.ord, &gens);
        self.divide_by_rational_integer(sum, &dd)
    }

    fn ideal_inv(&self, a: &Ideal) -> Ideal {
        ideal_inverse(&self.ord, a)
    }

    fn principal_ideal(&self, x: &NfElem) -> Option<Ideal> {
        if x.is_zero_elem() {
            return None;
        }
        let num_ideal = ideal_from_generators(&self.ord, &[x.num.clone()]);
        Some(self.divide_by_rational_integer(num_ideal, &x.den))
    }

    /// `x ∈ 𝔞 = (1/d_𝔞)·span(B)` ⟺ `d_𝔞·num(x) ∈ span(den(x)·B)`.
    fn ideal_contains(&self, a: &Ideal, x: &NfElem) -> bool {
        let n = self.ord.n;
        let target: Vec<Integer> = x.num.iter().map(|c| c.clone() * a.denom.clone()).collect();
        Self::lattice_member(&a.basis, &x.den, &target, n)
    }

    /// `𝔞 ⊆ 𝔟` ⟺ every ℤ-basis element of `𝔞` lies in `𝔟`.
    fn ideal_subset(&self, a: &Ideal, b: &Ideal) -> bool {
        a.basis
            .iter()
            .all(|col| self.ideal_contains(b, &NfElem::new(col.clone(), a.denom.clone())))
    }

    /// Solve `u + v = 1` with `u ∈ 𝔠₁`, `v ∈ 𝔠₂` by expressing the coordinates
    /// of `1` as a ℤ-combination of the stacked lattice bases (via SNF).
    fn idempotents(&self, c1: &Ideal, c2: &Ideal) -> Result<(NfElem, NfElem), DedekindError> {
        if !c1.denom.is_one() || !c2.denom.is_one() {
            return Err(DedekindError::NotCoprime(
                "idempotents need integral ideals".into(),
            ));
        }
        let n = self.ord.n;
        // M: n×2n, columns = c1.basis ++ c2.basis (row-major data)
        let mut data: Vec<Integer> = Vec::with_capacity(n * 2 * n);
        for i in 0..n {
            for col in c1.basis.iter().chain(c2.basis.iter()) {
                data.push(col[i].clone());
            }
        }
        let m = Matrix::from_vec(n, 2 * n, data)
            .map_err(|e| DedekindError::Internal(format!("matrix shape: {e:?}")))?;
        let snf = m
            .smith_normal_form()
            .map_err(|e| DedekindError::Internal(format!("snf: {e:?}")))?;
        // Solve M·z = t with t = coords of 1: S = P·M·Q, y_i = (P·t)_i / s_ii, z = Q·y
        let t = self.ord.one();
        let not_coprime =
            || DedekindError::NotCoprime("1 is not in the lattice sum: ideals not coprime".into());
        let mut y = vec![Integer::zero(); 2 * n];
        for i in 0..n {
            let mut pt = Integer::zero();
            for (k, tk) in t.iter().enumerate() {
                pt = pt + snf.p.get(i, k).expect("p entry").clone() * tk.clone();
            }
            let s_ii = snf.s.get(i, i).expect("s entry").clone();
            if s_ii.is_zero() {
                if !pt.is_zero() {
                    return Err(not_coprime());
                }
            } else {
                if !(pt.clone() % s_ii.clone()).is_zero() {
                    return Err(not_coprime());
                }
                y[i] = pt / s_ii;
            }
        }
        let mut z = vec![Integer::zero(); 2 * n];
        for (j, zj) in z.iter_mut().enumerate() {
            for (i, yi) in y.iter().enumerate() {
                if !yi.is_zero() {
                    *zj = zj.clone() + snf.q.get(j, i).expect("q entry").clone() * yi.clone();
                }
            }
        }
        // u = Σ_{j<n} z_j · c1.basis[j], v = 1 - u
        let mut u_coords = vec![Integer::zero(); n];
        for (j, col) in c1.basis.iter().enumerate() {
            if !z[j].is_zero() {
                for i in 0..n {
                    u_coords[i] = u_coords[i].clone() + z[j].clone() * col[i].clone();
                }
            }
        }
        let u = NfElem::new(u_coords, Integer::one());
        let v = self.sub(&self.one(), &u);
        // verify honestly (catches any transform-convention mistake)
        if !self.ideal_contains(c1, &u) || !self.ideal_contains(c2, &v) {
            return Err(DedekindError::Internal(
                "idempotent verification failed".into(),
            ));
        }
        Ok((u, v))
    }

    /// Bounded principality search (LLL on the Minkowski embedding, from
    /// `rustmath-numberfields`). A returned generator is re-verified here by
    /// canonical ideal equality; failure of the bounded search is reported as
    /// [`Principality::Unresolved`] — never as a non-principality decision.
    fn principal_generator(&self, a: &Ideal) -> Principality<NfElem> {
        // scale to the integral part: 𝔞 = (1/d)·A, gen(𝔞) = gen(A)/d
        let integral = Ideal {
            basis: a.basis.clone(),
            denom: Integer::one(),
            n: a.n,
        };
        match is_principal(&self.f, &self.ord, &integral) {
            Some(coords) => {
                let g = NfElem::new(coords, a.denom.clone());
                match self.principal_ideal(&g) {
                    Some(pg) if pg == *a => Principality::Principal(g),
                    // a bad certificate is treated conservatively
                    _ => Principality::Unresolved,
                }
            }
            None => Principality::Unresolved,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rustmath_numberfields::ideals::ideal_norm;

    fn qi() -> NfDedekind {
        // K = ℚ(i), f = x² + 1
        NfDedekind::from_i64_poly(&[1, 0, 1])
    }

    fn qsqrt_m5() -> NfDedekind {
        // K = ℚ(√-5), f = x² + 5; O_K = ℤ[√-5], h(K) = 2
        NfDedekind::from_i64_poly(&[5, 0, 1])
    }

    #[test]
    fn elem_arithmetic_in_qi() {
        let k = qi();
        // (1+i)(1-i) = 2
        let a = k.elem(&[1, 1], 1);
        let b = k.elem(&[1, -1], 1);
        assert_eq!(k.mul(&a, &b), k.elem(&[2, 0], 1));
        // (1+i)⁻¹ = (1-i)/2
        let inv = k.inv(&a).unwrap();
        assert_eq!(inv, k.elem(&[1, -1], 2));
        assert_eq!(k.mul(&a, &inv), k.one());
        assert!(k.inv(&k.zero()).is_none());
        // canonical form: 2/2 = 1
        assert_eq!(k.elem(&[2, 0], 2), k.one());
    }

    #[test]
    fn principal_ideal_and_membership_qi() {
        let k = qi();
        let one_plus_i = k.elem(&[1, 1], 1);
        let p2 = k.principal_ideal(&one_plus_i).unwrap();
        assert_eq!(ideal_norm(&p2), Integer::from(2));
        // 2 ∈ (1+i), 1 ∉ (1+i)
        assert!(k.ideal_contains(&p2, &k.elem(&[2, 0], 1)));
        assert!(!k.ideal_contains(&p2, &k.one()));
        assert!(k.ideal_contains(&p2, &k.zero()));
        // (1+i)² = (2)
        let sq = k.ideal_mul(&p2, &p2);
        assert_eq!(sq, k.principal_ideal(&k.elem(&[2, 0], 1)).unwrap());
        // (1+i)·(1+i)⁻¹ = O
        assert_eq!(k.ideal_mul(&p2, &k.ideal_inv(&p2)), k.unit_ideal());
    }

    #[test]
    fn fractional_ideal_ops_qi() {
        let k = qi();
        let half = k.from_rational(&Rational::new(1, 2).unwrap());
        let a = k.principal_ideal(&half).unwrap(); // (1/2)
        assert!(!k.ideal_is_integral(&a));
        // (1/2) + (1/3)·O ... use (1/2)O + (2)O = (1/2)O since (2) ⊆ (1/2)O
        let two = k.principal_ideal(&k.elem(&[2, 0], 1)).unwrap();
        assert_eq!(k.ideal_add(&a, &two), a);
        // membership: 1/2 ∈ (1/2), 1/4 ∉ (1/2)
        assert!(k.ideal_contains(&a, &half));
        assert!(!k.ideal_contains(&a, &k.from_rational(&Rational::new(1, 4).unwrap())));
        // subset: O ⊆ (1/2)O
        assert!(k.ideal_subset(&k.unit_ideal(), &a));
        assert!(!k.ideal_subset(&a, &k.unit_ideal()));
    }

    #[test]
    fn idempotents_coprime_primes_qsqrt_m5() {
        let k = qsqrt_m5();
        // 𝔭₂ = (2, 1+w), 𝔮₃ = (3, 1+w) with w = √-5: coprime primes
        let p2 = k
            .ideal_from_elems(&[k.elem(&[2, 0], 1), k.elem(&[1, 1], 1)])
            .unwrap();
        let q3 = k
            .ideal_from_elems(&[k.elem(&[3, 0], 1), k.elem(&[1, 1], 1)])
            .unwrap();
        assert_eq!(ideal_norm(&p2), Integer::from(2));
        assert_eq!(ideal_norm(&q3), Integer::from(3));
        let (u, v) = k.idempotents(&p2, &q3).unwrap();
        assert!(k.ideal_contains(&p2, &u));
        assert!(k.ideal_contains(&q3, &v));
        assert_eq!(k.add(&u, &v), k.one());
        // non-coprime: 𝔭₂ and (2) share the factor 𝔭₂
        let two = k.principal_ideal(&k.elem(&[2, 0], 1)).unwrap();
        assert!(matches!(
            k.idempotents(&p2, &two),
            Err(DedekindError::NotCoprime(_))
        ));
    }

    #[test]
    fn principality_honest_tristate_qsqrt_m5() {
        let k = qsqrt_m5();
        // 𝔭₂ = (2, 1+w) is famously non-principal (x²+5y² = 2 unsolvable):
        // the bounded search must stay Unresolved, never fabricate a generator.
        let p2 = k
            .ideal_from_elems(&[k.elem(&[2, 0], 1), k.elem(&[1, 1], 1)])
            .unwrap();
        assert_eq!(k.principal_generator(&p2), Principality::Unresolved);
        // 𝔭₂² = (2) is principal and the certificate is verified
        let p2sq = k.ideal_mul(&p2, &p2);
        assert_eq!(p2sq, k.principal_ideal(&k.elem(&[2, 0], 1)).unwrap());
        match k.principal_generator(&p2sq) {
            Principality::Principal(g) => {
                assert_eq!(k.principal_ideal(&g).unwrap(), p2sq);
            }
            Principality::Unresolved => panic!("bounded search must find the generator 2"),
        }
    }
}
